### ISSUE TITLE
consult-error: missing errors + ‘recenter’ing a window that does not display current-buffer

### ISSUE THREAD

**Issue by oantolin** [minad/consult#101]
I just tried `consult-error` together with `M-x grep` without much success.

First, in my configuration it just hangs until I press `C-g`, but that might be just a problem in my configuration.

Then I tried in `emacs -Q`:

1. Run `emacs -Q` from the consult source directory.
2. `M-x package-initialize`, to later use consult.
3. Optionally load a completion UI. I tried both default tab completion and icomplete-vertical.
4. `M-x grep RET def *.el RET`, and switch to the grep buffer.
5. `M-x consult-error`

Only five error are available as completions, even though there are tons of matches of `def`. That's one problem. A second problem is that no matter which of the five available completions I pick, I don't get taken there, instead I get that error:

```
‘recenter’ing a window that does not display current-buffer
```

**Comment by minad** [comment]
@oantolin Oh, okay. Thanks for reporting this! I should haved test this better. Right now I only used `consult-error` together with flycheck/flymake errors but not in other buffers like compilation or grep. I somehow had hoped that it just works :sweat_smile: 

The problem is that the next-error commands used to obtain the candidates are not a solid api, basically the backends can do whatever they want. I will check if there is an easy fix in the case you described!

**Comment by minad** [comment]
I already reproduced: 

1. The endless loop (this is due to the bad next-error API), I thought I had this fixed, but obviously not. This is not a problem in your config.
2. The missing items

I didn't yet see the recenter problem - where do you see this? With all icomplete/embark-live-occur/default completion?

**Comment by oantolin** [comment]
The endless loop problem is a little strange then, since in the case I described with grep, I do get it with my config but I don't get the endless loop with `emacs -Q`.

I see the recentering problem with icomplete and with default tab completion, if I select the completion from the `*Completions*` buffer.

**Comment by minad** [comment]
The problem is that I am using the `next-error-function` to try to obtain the errors. This only works with very well behaved functions which don't switch the buffer. It does not even work with the compile buffer error function (like in the grep buffer), and this is arguably the most important ones. I just checked counsel - it only provides `counsel-compilation-errors`, which is special cased only for compile buffers. I guess I should rewrite `consult-error` such that it only works in compile-buffers instead of trying to cover the general case which simply cannot be trusted.

**Comment by minad** [comment]
@oantolin I changed `consult-error` such that it only works in compile buffers. Please test! The compile.el code seems to me like a big non-reusable mess...

**Comment by oantolin** [comment]
> @oantolin I changed `consult-error` such that it only works in compile buffers. Please test!

Will do.

> The compile.el code seems to me like a big non-reusable mess...

That's a shame.

**Comment by minad** [comment]
>> The compile.el code seems to me like a big non-reusable mess...
> That's a shame.

Well, I guess it is kind of old. My main problem with it is the message data structure which is used there. They are gluing the messages as properties inside the text and then the data structure has some kind of fluid format which changes in weird ways depending on the status.

By doing this

~~~ elisp
                     ;; taken from compile.el
                     (apply #'compilation-find-file
                            (point-marker)
                            (caar (compilation--loc->file-struct loc))
                            (cadar (compilation--loc->file-struct loc))
                            (compilation--file-struct->formats
                             (compilation--loc->file-struct loc)))
~~~

you can get the buffer from the location and then you still have to do your own goto-char forward-line etc to get a marker out of that...

**Comment by oantolin** [comment]
Works fine with grep now! Thanks! It does ask you where a file is sometimes, but it works.
