### ISSUE TITLE
Warnings in consult-selectrum

### ISSUE THREAD

**Issue by hmelman** [minad/consult#105]
consult-selectrum.el:90:1:Warning: the following functions are not known to be
        defined: consult--async-split-string, consult--async-split-setup

**Comment by minad** [comment]
There is something wrong with your setup. The functions are defined in consult.el.

**Comment by hmelman** [comment]
Ah, I'm installing from melpa so I guess it compiled `consult-selectrum` first.  Restart fixed it.  "Invalid" seems a little harsh :)

**Comment by minad** [comment]
Well, "invalid" is everything which is not a "bug" but has been reported as one. I've not been the one who gave the name to this label, it is a github default.

But tbh I think being a bit "harsh" is also appropriate in this case ;) I should say, I very much value your feedback! It has been great and thank you for that! But since you are a very advanced Emacs user - this issue is something you've probably seen before (compilation warnings due to messed up compilation order) and you could also check it yourself in a second. I hope you don't mind ;)

**Comment by hmelman** [comment]
Fair enough, I haven't run across it before.  FWIW I did check.  I looked for the symbols in consult.el and didn't find them.  I evidently was still looking in the old consult.el file.  I quickly assumed the separate consult-selectrum was missing a declare (I found such a thing in embark yesterday) and I'm still having my morning coffee. :) Apologies for the time sink.

**Comment by minad** [comment]
> Fair enough, I haven't run across Invalid before.

Any suggestion to rename it to sth more friendly?

> FWIW I did check. I looked for the symbols in consult.el and didn't find them. 

Maybe you looked via describe-symbol? Since the you still have the old version loaded? This is something very weird about the Emacs compilation model that you are still having the old files loaded. I think async by jwiegley has a fix for this, where new packages are compiled outside the current process. This is much more solid.

> I quickly assumed the separate consult-selectrum was missing a declare (I found such a thing in embark yesterday) and I'm still having my morning coffee. :) 

I think we only have very few declares in consult.el for some icomplete functions, but that's it. I am using an explicit require style, see also issue #89.

> Apologies for the time sink.

No need to apologize! I didn't mean it in a "harsh" way only because the label sounds like it.

**Comment by minad** [comment]
Renamed to "not a bug". Better?

**Comment by hmelman** [comment]
"not a bug" is better.  Thanks.

I had looked with isearch.  I had consult.el open in a buffer and after updating and seeing the warning didn't switch to the new consult.el via `find-library`.
