### ISSUE TITLE
keybdings not shown in M-x with consult-annotate mode

### ISSUE THREAD

**Issue by smsegal** [minad/consult#12]
First of all, great stuff! I'd been using the selectrum wiki commands with some of my own modifications and this package has totally replaced all of that cruft I included. 

On to the actual issue: I see in the screenshot showing `M-x` with `consult-annotate-mode` enabled that keybindings are shown as part of the annotations. But I don't see any such keybindings when this package is enabled.

**Comment by minad** [comment]
Cool thank you! Yes M-x is a bit of a weirdo. Emacs 28 shows you those keybindings if you set `suggest-key-bindings t`. Then it will also be shown here. 

Alternatively I could tweak consult-annotate-mode such that it always adds the keybinding even if you are not running on Emacs 28. I have to think about those things a bit better. `consult-annotate-mode` is very new, only wrote it a few hours ago and it only works on Selectrum since it uses the Selectrum annotation properties. Note also that the annotation api of Emacs 28 is very much in flux (they added affixation-function #5 just a few days ago).

-----

In case you need a fix for Emacs 27.1 - I am running 27 with the patch copied verbatim from Emacs 28 to my init.el

~~~ elisp
(defun read-extended-command ()
  "Read command name to invoke in `execute-extended-command'."
  (minibuffer-with-setup-hook
      (lambda ()
        (add-hook 'post-self-insert-hook
                  (lambda ()
                    (setq execute-extended-command--last-typed
                              (minibuffer-contents)))
                  nil 'local)
	(set (make-local-variable 'minibuffer-default-add-function)
	     (lambda ()
	       ;; Get a command name at point in the original buffer
	       ;; to propose it after M-n.
	       (with-current-buffer (window-buffer (minibuffer-selected-window))
		 (and (commandp (function-called-at-point))
		      (format "%S" (function-called-at-point)))))))
    ;; Read a string, completing from and restricting to the set of
    ;; all defined commands.  Don't provide any initial input.
    ;; Save the command read on the extended-command history list.
    (completing-read
     (concat (cond
	      ((eq current-prefix-arg '-) "- ")
	      ((and (consp current-prefix-arg)
		    (eq (car current-prefix-arg) 4)) "C-u ")
	      ((and (consp current-prefix-arg)
		    (integerp (car current-prefix-arg)))
	       (format "%d " (car current-prefix-arg)))
	      ((integerp current-prefix-arg)
	       (format "%d " current-prefix-arg)))
	     ;; This isn't strictly correct if `execute-extended-command'
	     ;; is bound to anything else (e.g. [menu]).
	     ;; It could use (key-description (this-single-command-keys)),
	     ;; but actually a prompt other than "M-x" would be confusing,
	     ;; because "M-x" is a well-known prompt to read a command
	     ;; and it serves as a shorthand for "Extended command: ".
	     "M-x ")
     (lambda (string pred action)
       (if (and suggest-key-bindings (eq action 'metadata))
	   '(metadata
	     (annotation-function . read-extended-command--annotation)
	     (category . command))
         (let ((pred
                (if (memq action '(nil t))
                    ;; Exclude obsolete commands from completions.
                    (lambda (sym)
                      (and (funcall pred sym)
                           (or (equal string (symbol-name sym))
                               (not (get sym 'byte-obsolete-info)))))
                  pred)))
           (complete-with-action action obarray string pred))))
     #'commandp t nil 'extended-command-history)))

(defun read-extended-command--annotation (command-name)
  (let* ((function (and (stringp command-name) (intern-soft command-name)))
         (binding (where-is-internal function overriding-local-map t)))
    (when (and binding (not (stringp binding)))
      (format " (%s)" (key-description binding)))))
~~~

**Comment by minad** [comment]
@smsegal I decided to solve this cleanly, see https://github.com/minad/consult/commit/b8c228fa99a02f0bfe9add62d1dd46bd8014afbc. There is now `consult-annotate-command` and `consult-annotate-command-only-binding`.

**Comment by smsegal** [comment]
Great stuff! Works perfectly. 

![2020-11-29T18:08:48,161713386-05:00](https://user-images.githubusercontent.com/7110093/100556175-652a6280-326e-11eb-964f-b91c36cf5251.png)

**Comment by minad** [comment]
Thanks! But I find that to noisy, therefore I am using just `consult-annotate-command-only-binding` :)
