### ISSUE TITLE
vterm and consult-history

### ISSUE THREAD

**Issue by ram535** [minad/consult#121]
Is it possible to add `consult-history` to work with `vterm`?

**Comment by minad** [comment]
I am not sure. vterm seems kind of special since it integrates a widget in contrast to the usual term modes. Is there some vterm history exposed as a history variable? It is probably better to ask on the emacs vterm plugin issue tracker.

I am often using term/ansi-term, but I am going to use eshell more. I tried vterm shortly but it didn't work well for me.

**Comment by minad** [comment]
It seems vterm does not support this currently.

* https://github.com/akermu/emacs-libvterm/issues/336
* https://github.com/akermu/emacs-libvterm/pull/377

Maybe @jixiuf can tell more. But it seems to me this must be sorted out first on the vterm side before we can add support here.
