### ISSUE TITLE
Chance to recommend user-level wrappers for consult--grep commands?

### ISSUE THREAD

**Issue by protesilaos** [minad/consult#156]
Hello @minad!  In light of our [previous discussion on find/grep](https://github.com/minad/consult/issues/123#issuecomment-753877434), what would you say about the current state of `consult--grep` wrappers?  Apart from `consult-grep`, we also get those:

```elisp
;;;###autoload
(defun consult-git-grep (&optional dir initial)
  "Search for regexp with grep in DIR with INITIAL input.

See `consult-grep' for more details."
  (interactive "P")
  (consult--grep "Git-grep" consult-git-grep-command dir initial))

;;;###autoload
(defun consult-ripgrep (&optional dir initial)
  "Search for regexp with rg in DIR with INITIAL input.

See `consult-grep' for more details."
  (interactive "P")
  (consult--grep "Ripgrep" consult-ripgrep-command dir initial))
```

**Comment by minad** [comment]
You mean I should consider removing these too?

**Comment by protesilaos** [comment]
> You mean I should consider removing these too?

I just noticed them and thought I would bring them to your attention.

**Comment by minad** [comment]
Yes, I know that I am not entirely consistent and objective here. I mentioned this before in the discussion regarding fdfind and in the wishlist.

Ripgrep, grep, git-grep are justified since they all add something specific:

* grep is ubiquitous
* ripgrep is much faster and already widespread, ignores files and has other enhancements, but besides that behaves like grep from my perspective. ripgrep quickly entered my workflow. Fortunately the rg name does not clash with anything.
* git-grep is optimized to work well with git repositories (gitignore), also always available if you have git.

So these are all justified. fdfind in contrast is not as justified for me, for some subjective reasons:

* It has a bad name which already prevents me from just offering it as is. fd means also floppy disk and file descriptor. For this reason it is not available on some linux distributions under the fd name. This means we already need some configuration for fd.
* It has certain quirks. When given the full-path option, it should search for the regexp in the full-path. This means when I am in directory /home/user and search for user it will find all files. I would want it to search only the path below the root directory.
* I find it weird that it uses regular expressions in contrast to wildcards, even if regular expressions are better. In our context regular expressions are also better, since you can just type #org# to find all org files. But somehow due to all these quirks, fd did not (yet) manage to become a drop-in replacement for find in my use cases.

But given all these arguments - if there wouldn't be the name problem I would have included fdfind here.

**Comment by protesilaos** [comment]
Thanks for the detailed explanation!
