### ISSUE TITLE
Straight.el package installation is broken

### ISSUE THREAD

**Issue by doolio** [minad/consult#162]
The [README configuration example](https://github.com/minad/consult#example-configuration) I presume to be agnostic to the completion system does not configure one. How should one tell consult to use a non-default completion system? 

Edit: I guess something like the following but is that the optimum way?

```
(use-package consult
  :config
  (require 'consult-selectrum))
```

or

```
(use-package consult
  :config
  (require 'consult-icomplete))
```

**Comment by minad** [comment]
No you don't have to do anything. Consult performs the autoconfiguration by itself.

**Comment by doolio** [comment]
Hmm, okay. I get the message:

`Cannot open load file: No such file or directory, consult-selectrum`

I'll continue to investigate my configuration.

**Comment by minad** [comment]
Please ensure that you have the newest version and ensure that no consult-selectrum package is installed.

**Comment by doolio** [comment]
I have the latest [d534539](https://github.com/minad/consult/commit/d53453917ef2281be6ee3dad0915f96907c69ff8) commit installed via `straight` and no separate "consult-selectrum" package installed. My issue is for some reason straight is not adding the symlink to `consult-selectrum` in its build directory. It is not adding it for `consult-flycheck` either. The other symlinks are present though.

**Comment by minad** [comment]
Ah okay, I see. Please tell me if you come up with a fix. Do I have to add some kind of package descriptor to make this work out of the box for straight users?

The consult MELPA package is made up of the four files:

* consult.el
* consult-flymake.el
* consult-selectrum.el
* consult-icomplete.el

Then there is a consult-flycheck package with a single file:

* consult-flycheck.el

**Comment by doolio** [comment]
Ah I had presumed you were a `straight` user as well. I believe there is something odd with `straight` then as my `straight` repos  directory for `consult` contains all the files in your repository here including `consult-flycheck.el`. The `straight` (melpa) receipe for `consult` does specify to exclude `consult-flycheck.el` though (along with `consult-pkg.el` which I presume is to be expected) which would match what you state above for it to be classed as a separate package on melpa.

**Comment by minad** [comment]
> Ah I had presumed you were a straight user as well.

No, I am a simple user :-P

I also don't have that many packages installed any most of them are pretty trustworthy. So I am okay with MELPA.

> I presume not as the symlink was built for consult-icomplete.el.

Could it be that straight somehow caches a broken recipe? The recipe has recently been updated when we got rid of the consult-selectrum MELPA package in order to enable auto configuration.

**Comment by pavel-popov** [comment]
Same for happened today after I updated packages from Melpa, combo Selectrum+Consult doesn't work anymore. I first thought the reason is Selectrum, so I switched to Icomplete, but the error is the same, only different hook name:

```
Error in post-command-hook (selectrum--minibuffer-post-command-hook): (wrong-type-argument number-or-marker-p nil)

Error in post-command-hook (icomplete-post-command-hook): (wrong-type-argument number-or-marker-p nil)
```

I then found few issues saying that need to install the latest commits, so I switched from Melpa to straight.el, no luck - the last thing I saw is that straight doesn't create symlinks in `build` to `consult-selectrum.el` as it does for `consult-complete.el` and others. I tried to create symlinks manually, no luck.

I temporarily switched back to Ivy+Counsel. Sorry that I can't invest more time in investigation.

**Comment by minad** [comment]
@pavel-popov I am not sure if your issue is related. These symlinks should be fixed in any case, but the errors you are seeing seem to be something different. I would need some reproduction steps in emacs -Q in order to investigate this.

**Comment by doolio** [comment]
OK, so as mentioned in #163 a clean log out and in again seems to have forced `straight` to have rebuilt the `consult` package and all symlinks appear in the `straight` build/consult directory as expected. 

Sorry, for the noise. Thanks for your time and this package.
