### ISSUE TITLE
consult-async: Better behavior for default TAB completion

### ISSUE THREAD

**Issue by minad** [minad/consult#164]
The problem is that when pressing TAB the current input is deleted. ~Improve async-split-style?~ ~Advise minibuffer-complete?~ Overwrite keymaps?

The bad functions are:
* minibuffer-complete (TAB)
* minibuffer-complete-word (SPC)

The fix turns out to be pretty simple:
~~~ elisp
(define-key minibuffer-local-completion-map " " #'self-insert-command)
(define-key minibuffer-local-completion-map "\t" #'minibuffer-completion-help)
~~~

However this should be done only for the async commands. @oantolin @protesilaos how does this work in your setup with the Embark live-occur. You probably have space on self-insert and you never press TAB in the async setting?

**Comment by oantolin** [comment]
😆 I never noticed! Indeed, I do have `SPC` bound to `self-insert` and I never press TAB when using `consult-grep` or `consult-git-grep`. I usually don't even see the completions until the second `#`, then I popup the embark collect completions buffer, narrow a bit and scroll through the candidates to enjoy the preview.

I think it's instinctive for me not to press `TAB` in `consult-grep` because I think of `TAB` as (potentially) replacing my input with the candidate, but the candidate clearly has the wrong syntax for `consult-grep`, so I don't want to do replace the input with it.

**Comment by minad** [comment]
> I think it's instinctive for me not to press TAB in consult-grep because I think of TAB as (potentially) replacing my input with the candidate, but the candidate clearly has the wrong syntax for consult-grep, so I don't want to do replace the input with it.

I hope every default completion user has your instincts so I don't have to do anything here :rofl:

But if it turns out that something should be done, rebinding the keys as I wrote above works around the issues. The only problem is that the overwrite should only be done locally for the async functions, so this should added somewhere in the consult--setup-keymap function.

**Comment by minad** [comment]
One idea I had before is the following: Add a `:keymap` argument to consult--read which allows to merge an arbitrary keymap into the local completion keymap. This is very easy to do since I already have the preview and narrow keymaps. Then the async commands could be individually modified via the `consult-config` variable.

**Comment by protesilaos** [comment]
What Omar wrote covers my case as well:

+ SPC to self insert.
+ Never use TAB in such a case because it will expand the candidate and thus remove the results from the live collection.

> minad: The fix turns out to be pretty simple: [...] `(define-key minibuffer-local-completion-map "\t" #'minibuffer-completion-help)`

This would come with the downside of making TAB not complete in cases where it should.

> minad: The only problem is that the overwrite should only be done locally for the async functions, so the keybindings should be added somewhere in the consult--setup-keymap function.

Correct!

> minad: One idea I had before is the following: Add a :keymap argument to consult--read which allows to merge an arbitrary keymap into the local completion keymap. This is very easy to do since I already have the preview and narrow keymaps. Then the async commands could be individually modified via the consult-config variable.

Sounds like a plan!  Thinking about it, I never press TAB for the likes of `consult-line`, `consult-imenu` because of the multiple matches (I do press it with `consult-outline` in Org buffers because my headings are almost always unique).

**Comment by minad** [comment]
I am not very used to default completion. Therefore I am more inclined to press TAB all the time. I replaced the problematic keys dynamically for the async functions and cleaned up the keymap setup on the way. We could still add a :keymap argument if we find a use case for it.
