### ISSUE TITLE
Default consult-project-root-function

### ISSUE THREAD

**Issue by astoff** [minad/consult#167]
Any reason why there is no default? A reasonable value relying on the built-in project.el would be
``` elisp
(lambda () (let ((p (project-current))) (when p (project-root p))))
```
Or, as a super bare-bones version, `vc-root-dir` might be better than nothing.

**Comment by minad** [comment]
It seems in my current setup I have neither of these loaded by default since I am using projectile.Is there a big downside of having this set to nil? I stated before that consult does not aim for the best out of the box experience, rather for configurability and flexibility. Having to configure the project root additionally to bindings seems to be a small effort.

**Comment by astoff** [comment]
Hah, I thought `vc-root-dir` was loaded at startup, since the vc mode line thing is always there.

> Is there a big downside of having this set to nil?

I don't know, it's just a little nicety. Or maybe the nil default is actually less surprising.

Anyway, if you want to mention project.el in the config example, that's the function.

**Comment by minad** [comment]
> Anyway, if you want to mention project.el in the config example, that's the function.

Yes, I should put this in the readme!
