### ISSUE TITLE
Future history in consult-lines

### ISSUE THREAD

**Issue by astoff** [minad/consult#172]
When press `M-n` in `consult-lines` several times, I first see the entire current line, an only after that what I really expected: symbol at point and last search string.

Maybe `consult-lines` should have nil `:default` and a special case in the `:preview` function for when the minibuffer contents is empty?

**Comment by minad** [comment]
> When press M-n in consult-lines several times, I first see the entire current line, an only after that what I really expected: symbol at point and last search string.

Yes, this happens since :default must be added to the future history. First I tried to work around this, but it is not possible without serious hacks. See in particular the discussion in #151 and the original proposal of future histories in #96.

> Maybe consult-lines should have nil :default and a special case in the :preview function for when the minibuffer contents is empty?

The special casing for empty minibuffer contents is not possible since preview does not use the minibuffer contents but the currently selected candidate as obtained from the completion system. You can hack this by advising `consult--selectrum-candidate` if you like and return `nil` in the case of an empty minibuffer.

For the given reasons I would live to keep the current behavior, at the cost of a slightly less convenient future history. Note that you can also set :default for consult-line to nil. Furthermore you can create your own consult-line-symbol-at-point wrapper.

~~~ elisp
(setq consult-config '((consult-line :default nil)))
~~~

**Comment by astoff** [comment]
Fair enough. Sorry for missing that from the previous issues.

**Comment by minad** [comment]
No problem, there have been many discussions scattered over many issues. Please just ask or create issues. And it could always have happened that we missed something in prior discussions.

**Comment by jiacai2050** [comment]
The new API is as follows:

```el
(consult-customize consult-line :default nil)
```
