### ISSUE TITLE
consult-line ignore `initial`

### ISSUE THREAD

**Issue by WorldsEndless** [minad/consult#176]
Verifying I'm on the latest master code, consult-line doesn't change behavior in any way when I supply an arg, which I would expect to have the same result as manually entering that arg after doing an arg-less `consult-line`. 

```lisp
fun bar
not bar
not function-key-map

(consult-line "fun") ;; same results as plain (consult-line)
```

**Comment by minad** [comment]
Do you use selectrum? Which Emacs version are you using? Did you reproduce it with emacs -Q? Which configuration did you load?

**Comment by minad** [comment]
I suspect, you are using a very outdated Selectrum version. Please check.

**Comment by WorldsEndless** [comment]
Ah -- you were right. Apparently my selectrum was a bit out-dated. For my education, why was that the issue?

**Comment by minad** [comment]
Selectrum originally simply ignored the initial input argument for some reason. See https://github.com/raxod502/selectrum/pull/254. I had forgotten about this too otherwise I would have told you directly to check specifically Selectrum. But in general, please try to always update the relevant packages and provide more information with your bugreports. I just added a section to the readme, see https://github.com/minad/consult/commit/4f878b44f495417f0a4f2b5b90be2c36c27ebfc5
