### ISSUE TITLE
consult-find: Automatically add wildcards around input string

### ISSUE THREAD

**Issue by ambihelical** [minad/consult#180]
consult-find with the default consult-find-command produced no results for me.  Replacing the binding of consult-find with find-fd as in the Readme worked fine as I already had fd installed. 

I'm using Ubuntu 16.04, Emacs 27.1. Let me know if I can provide any other information.

**Comment by minad** [comment]
Did you enter wildcards? See the documentation here https://github.com/minad/consult#grep-and-find. For example if I enter `*consult*` it works for me.

**Comment by ambihelical** [comment]
I did not try that, probably having to do that would make me not want to use consult at all, as I'm just trying it out atm. The fd based solution doesn't require wildcards, why is there a difference?

**Comment by minad** [comment]
> The fd based solution doesn't require wildcards, why is there a difference?

The difference is because of POSIX. `find` is POSIX and `fd` is something else, non-standardized, `fd` uses regular expressions. Therefore `fd` is more user friendly in this context, but has other problems. It is not widely installed and the command name differs between operating systems. For this reason there is no `consult-fd` command. But as you see in the README with `find-fd`, you can quickly create your own command. Alternatively configure the variable `consult-find-command` such that it uses `fd`.

It has been discussed to add wildcards automatically around the `consult-find` search expression but the sentiment has been to not add it in order to not modify the UI of the underlying command. You would also have to type the wildcards on the shell.
But maybe I will change this and just always add the wildcards, I also find them kind of annoying.

**Comment by minad** [comment]
I fixed this in https://github.com/minad/consult/commit/63f11667cf38ee3ca597a01c41e5d4ca04ca3d61. Now it is possible to configure if wildcards should be added or not. The default is to add wildcards to consult-find. cc @inigoserna

**Comment by inigoserna** [comment]
> I fixed this in [63f1166](https://github.com/minad/consult/commit/63f11667cf38ee3ca597a01c41e5d4ca04ca3d61). Now it is possible to configure if wildcards should be added or not. The default is to add wildcards to consult-find. cc @inigoserna

I understand it's very difficult to please everyone, even new users with quite different ideas or concepts.
I'd prefer consult commands keep same behaviour as CLI equivalent ones, but I'm ok with these changes, of course.

Btw, after a month since my migration from helm, I want to thank you (and @oantolin, @raxod522, @clemera, etc) again for these packages, I feel my emacs use somehow different, smoother. Keep on this good work!
