### ISSUE TITLE
consult-register candidates for multiline text registers or rectangles are flattened to one line

### ISSUE THREAD

**Issue by oantolin** [minad/consult#187]
This is probably something you do on purpose, but consider keeping them multiline, just like the candidates in the `consult-yank` family. I just added `list` initial embark collect view for `consult-register`, but would change that to `zebra` if you made these multiline.

I think the candidates are exactly the string returned by `consult-register-preview`, but I think those might look nice as multiline previews too.

If you like them better flattened to a single line, that's okay, but might I suggest representing the newlines graphically somehow, like with ⏎?

**Comment by minad** [comment]
* For the register preview I assume that the strings should be single line, but I can try multiline candidates too. However previews are usually heavily truncated. So maybe keep it as is.
* For completing-read, I agree multi line would be better for Embark collect, zebra mode etc. However Selectrum prints verboses prefixes for multiline candidates (see https://github.com/raxod502/selectrum/pull/266). The registers would then be printed as "(10 lines) <register-key> ...". My main problem with this is that I would like to see the register key in the beginning. I would prefer if Selectrum printed something like "⏎..." in the end instead. For my taste this number-of-candidate-lines prefix is too heavy, too intrusive and too verbose. The number of lines is not an important information, so why is it in the beginning? Probably there is a way to turn it off. But I would like to see Consult working nicely with the default settings of Selectrum (cc @clemera).

**Comment by oantolin** [comment]
Keeping single line previews would be fine, but even for those some indication of whether the string is actually multiline would be nice, which is why I suggested using `⏎` to represent the newline.

And using the same format for preview and for the `consult-register` candidates is very sensible, so if you keep the preview single-line, I wouldn't really want you to write a different formatting function just for `consult-register`.

I agree that selectrum could choose a less intrusive display for multiline candidates.

**Comment by minad** [comment]
Okay I tried multiline previews. This works nicely. I should limit the number of lines, but besides that I don't see a problem with just showing the content as is. Regarding the completing-read interface I would also prefer to just show the strings as they are, but this would require Selectrum to reduce the multi line noise. Let's see what @clemera says about that. Having two different functions is no problem - I will implement it such that there won't be large code duplication.

**Comment by minad** [comment]
@oantolin, maybe you would want to write a zebra mode for the register preview? :)

**Comment by oantolin** [comment]
Sure. I can do that.

**Comment by minad** [comment]
I am not sure about the approach for the zebra mode. Maybe it requires replacing the entire `register-preview` function via `fset`.

Note that I already have that in the configuration in order to make adjustments. We could also perform the zebra here.

~~~ elisp
  (advice-add #'register-preview :around
              (lambda (fun buffer &optional show-empty)
                (let ((register-alist (seq-sort #'car-less-than-car register-alist)))
                  (funcall fun buffer show-empty))
                (when-let (win (get-buffer-window buffer))
                  (with-selected-window win
                    (setq-local mode-line-format nil)
                    (setq-local window-min-height 1)
                    (fit-window-to-buffer)))))
~~~

However given that this is the full register preview function, maybe a full replacement makes more sense? When the advice becomes longer than the original function the reuse argument becomes kind of pointless :laughing: 

~~~ elisp
(defun register-preview (buffer &optional show-empty)
  (when (or show-empty (consp register-alist))
    (with-current-buffer-window
     buffer
     (cons 'display-buffer-below-selected
	   '((window-height . fit-window-to-buffer)
	     (preserve-size . (nil . t))))
     nil
     (with-current-buffer standard-output
       (setq cursor-in-non-selected-windows nil)
       (mapc (lambda (elem)
               (when (get-register (car elem))
                 (insert (funcall register-preview-function elem))))
             register-alist)))))
~~~

**Comment by clemera** [comment]
I need the number of lines myself because otherwise I often don't know which kill ring entry I'm currently looking at (I don't enable automatic preview functionality). Displaying the number of lines in the right margin would also be okay but this would require a bit of work.

**Comment by minad** [comment]
Yes, I agree that it is good to have some visual indication about the multiline candidates, maybe even the number of lines as of now since it can be helpful. 

However as things stand now we can either pass formatted single-line candidates or unformatted multi-line candidates to Selectrum. In the case of single-line candidates, Selectrum does not apply any adjustments which is good to allow heavy formatting as I did in Consult. But in the multiline case, Selectrum applies many adjustments and replacements. It seems to introduce dots, arrows, escaped newlines. I have a hard time with this honestly. As you know I prefer to have less visual noise - but this is surely a matter of taste. I don't mind having noisy options available, this is good to have. But in particular for the defaults, I prefer less noise. As I mentioned before, the line number prefix is particularly problematic here since it modifies the line beginning, where the most crucial information is shown, in this case the register key.

Maybe you want to give the `consult-register-load/store` commands a try and also `consult-register`.  I think these are very handy commands with very fast access if you put them on good keys :) See for yourself - maybe you have some ideas on how to proceed?

**Comment by clemera** [comment]
I tried the commands now and they are nice indeed! I also see that the number of line prefix first would be annoying here. I think/hope the other transformations we do are pretty useful in general to make multi line candidate matches manageable within the minibuffer. We could check if the candidates already provide prefixes via affixiation and omit the prefixes in this case, would that be good enough?

**Comment by minad** [comment]
These are not affixation prefixes, but just plain strings, so you can select a register by pressing `^a RET`.

**Comment by minad** [comment]
I think my favorite solution would be if Selectrum does not modify the candidates as heavily and only adds something like `(3 lines)` in the end instead of the beginning. Then I could just pass the unmodified register values to completing-read. This would improve the interplay with the Embark collect :zebra:.

But maybe I am asking too much and this behavior would not be good enough for you. I hope we come up with a good solution. We always have, right? :smile:

**Comment by clemera** [comment]
Currently we display the matched line first and then the beginning of the multi line string as an annotation. The ideas is that you see the actual line match and from which chunk of text it is coming from. I guess the number of lines could also be shown as a prefix of the annotation, they wouldn't be at a constant place any more but I think now this would be also okay. If the matched line is to long it would need to be truncated so the number of lines is still visible but this should be a rare case.

**Comment by clemera** [comment]
I just noticed that this approach would still hide the register key prefixes as they are part of the candidates :(

**Comment by minad** [comment]
What about the following format?

`truncated first line...truncated matching line...truncated last line (numbers of lines)`

At the beginning the truncated matching line would be the second line since. The first and last line should be truncated to only a handful of characters.

**Comment by clemera** [comment]
I'm started to work on improving it [here](https://github.com/raxod502/selectrum/pull/398)

**Comment by minad** [comment]
@clemera I just tried it. This looks pretty good. I like it much more, in particular since the content does not jump around and it looks much less noisy, also for the kill ring. And the register preview would also just work out of the box like this!

The display looks like this `truncated first line...(5 lines)->matching line1\nmatching line2`

A few possible improvements:

* Unicode ellipsis
* Why the arrow? The (5 lines) plus a space is already a pretty good separator.
* The matching lines don't seem to be truncated in any way, would that be possible.

**Comment by clemera** [comment]
Thanks for trying, the arrow is there because we have it in `selectrum-multiline-display-settings` and I tried to keep the settings working. The matching lines are already truncated. Is there a simple way to check if the unicode ellipsis can be displayed?

**Comment by clemera** [comment]
Just remembered that the truncation (unicode ellipsis) can also be configured via `selectrum-multiline-display-settings`

**Comment by minad** [comment]
> Is there a simple way to check if the unicode ellipsis can be displayed?

I am not sure, one could check for the graphical UI. But these day most people also use pretty advanced terminals too. In Marginalia and Consult I do not care much about this and just use the Unicode ellipsis. But I am also a GUI user and don't see a point of using Emacs in a terminal. And I have yet to see a complaint.

But I can also configure this myself, that's okay!

> Thanks for trying, the arrow is there because we have it in selectrum-multiline-display-settings

Okay good, I guess I can switch it off. But I would probably kick it out from the defaults too since you are already changing the display. But maybe you like the arrow?

> The matching lines are already truncated.

Okay, I guess I missed that!

**Comment by minad** [comment]
@clemera I just looked up how you do this formatting with all these settings, match, nline, whitespace, etc. I like this design! It is very configurable. I should not have complained about it!

**Comment by clemera** [comment]
Okay nice, I will update the docs and then this should be good to go :)

**Comment by minad** [comment]
Great! After you merged it into Selectrum, I will update consult-register too.

**Comment by clemera** [comment]
Okay, I will ping you then, I still need to change something because of a mismatch between single/multi line refinements.

**Comment by minad** [comment]
@clemera One thing maybe - as long as the user has not typed anything, wouldn't it make sense to also show some more text from the remaining lines? I feel right now that we waste too much space and don't show enough.

~~~
truncated first line...(3 lines) remaining lines somehow truncated...
truncated first line...(3 lines)-> matching lines truncated...
~~~

In that case maybe reconsider moving the (3 lines) fully to the right as I proposed before? But having the (3 lines) in between is also a nice indicator that some more text follows. I am not sure.

**Comment by minad** [comment]
And another one - when the match is on the first line, it is not highlighted. In that case maybe the first line should not be truncated or the match should be shown after ->?

**Comment by clemera** [comment]
Okay, thanks, it's better to put some more work in it. It's easier for me to keep the `(3 lines)` in the middle because this would complicate things to ensure it is always displayed (also for horizontal display).  Showing the remaining lines when there is no input is a good idea. The missing highlighting of the first line is when the highlighted part is truncated but also when the mismatch I referred to above happens, I will look into it.

**Comment by minad** [comment]
Yes, the (3 lines) in between is okay. It is an indicator that more follows. I think I like it!

**Comment by minad** [comment]
@clemera I decided to go forward with this 7930839, since your adjustments will soon hit Selectrum and the change is non critical.

I am using these settings now:

~~~ elisp
(setf (alist-get 'match selectrum-multiline-display-settings) '("" default))
(setf (alist-get 'truncation selectrum-multiline-display-settings) '("…" shadow))
(setf (alist-get 'whitespace selectrum-multiline-display-settings) '(" " default))
~~~

Maybe I can convince you to adopt this one into Selectrum? Whitespace is whitespace.

~~~ elisp
(setf (alist-get 'whitespace selectrum-multiline-display-settings) '(" " default))
~~~

**Comment by clemera** [comment]
> Maybe I can convince you to adopt this one into Selectrum as default? Whitespace is whitespace.

I'm not sure, this indicates that multiple spaces have been replaced by `..` if using " " you have no indication of the changed space width.

**Comment by minad** [comment]
> I'm not sure, this indicates that multiple spaces have been replaced by .. if using " " you have no indication of the changed space width.

Yes, but this is not something I care about while doing completion. I prefer a less strict, less noisy display. I don't think I am the only one feeling this way :laughing: But this should not be over discussed, since it is configurable.

**Comment by clemera** [comment]
After trying it I think I prefer it as well, it is indeed less visual noise. I discovered a weird bug that when using `default` face the highlighting of the selection is messed up. If I keep the `shadow` face everything works.
