### ISSUE TITLE
Improving consult-imenu colors

### ISSUE THREAD

**Issue by Alexander-Miller** [minad/consult#195]
One thing I liked about `helm-imenu` is that it could fontify different keys with different colors. "Functions" would then use `font-lock-function-name-face`, "Variables" would use `font-lock-variable-name-face` etc. I think that makes it much easier to find your way around an imenu for a file you haven't much used before.

As a bonus I think it'd be nice if there was also an option to just use a different face for every different key. That would be useful in cases where imenu's keys are not statically known, like treemacs' own imenu integration:
![imenu](https://user-images.githubusercontent.com/5951157/106492077-d200e980-64b7-11eb-9028-7d382e20071a.png)

**Comment by minad** [comment]
Yes, this should be considered. I can define a set of faces, `consult-candidate-face-0..9` and use them in `consult-bookmark-narrow`, `consult-register-narrow`, `consult-imenu-narrow` and for the `consult-buffer-sources`. These faces would replace the existing semantic faces `consult-buffer`, `consult-file` etc. 

* Is it a good idea to replace the semantic faces? I like semantic faces but if it is open ended I am not so sure anymore.
* For consult-bookmark-narrow the downside would be that the bookmark candidate strings would be modified, such that we would have to fix the bookmark history afterwards. (NOTE: I should enhance the marginalia annotator with the bookmark types).
* Should the faces be hard-coded in the `consult-*-narrow` and in the sources or should I just apply them in cycles?

cc @protesilaos, since we just discussed faces.

**Comment by Alexander-Miller** [comment]
> Is it a good idea to replace the semantic faces?

Does it have to be a replacement? It should be possible to cover both cases simultaneously. First try to match against a static list of keywords like "Functions". Those get the semantic colors. If that doesn't work fall back to assigning `consult-candidate` faces. Tracking which key got which face in the latter case could be a bit tedious, but doable with a ring and a table.

**Comment by minad** [comment]
If I am using explicitly configured (semantic) faces I would rather not apply any arbitrary other faces to the other candidates, since this somehow defeats the purpose of the explicitly configured ones.

Right now the status is that we have explicit semantic faces in consult-buffer, since consult-buffer uses multiple sources. In the other cases we do not apply such faces to the individual candidates depending on their type.

Note also the discussion on reddit, where @clemera and I talked about narrowing vs multiple-sources. https://www.reddit.com/r/emacs/comments/l99xc8/consult_got_support_for_multiple_candidate_sources/glh24er/?utm_source=share&utm_medium=web2x&context=3

**Comment by protesilaos** [comment]
Hello! Just to note that I am keeping track of this. If you implement new faces I am prepared to extend support accordingly.

**Comment by minad** [comment]
@Alexander-Miller Please give it a test!

**Comment by Alexander-Miller** [comment]
Hmm. You have applied the faces to values, not keys like helm. Not sure what I think of that yet. Probably something to get used to.

The faces aren't quite right, "Types" should use `font-lock-type-face`.

Other than that everything looks to be in order.

**Comment by minad** [comment]
Ah okay, I missed that you meant the "keys". Note that I am not familar with Helm. I think it makes more sense to apply it to the actual names.
