### ISSUE TITLE
Using consult-buffer-sources with async commands like consult-find?

### ISSUE THREAD

**Issue by indigoviolet** [minad/consult#196]
Hi, 

Thanks for this great package and the continued iteration on it.

I would really like to combine `consult-buffers` and `consult-find` to extend the file portion of `consult-buffers` to include project files not in recent - this would give me back functionality like `helm-mini` to open a buffer without thinking about whether I have already opened it, recently opened it etc. 

Are there examples of creating sources like this?

I imagine the simplest implementation of this would be a source that reads from a command that lists all files in the project, but this would slow down `consult-buffers` annoyingly -- better would be an async source that merged in candidates as the async command returned, exactly like `consult-find` does so today. Has this been considered already?

**Comment by minad** [comment]
Sure I have considered combining async sources with static sources. For now my stance is that it is not worth the complexity.

Right now consult multi sources (consult--multi) are a very thin layer on top of consult--read, which itself is a thin layer on top of completing-read. consult--read has async support, consult--multi supports only static sources, but this is not a necessity - we could support async sources here too. Consult is different from Helm where everything is modelled as sources.

About the use case you have in mind - I see the appeal, it is a nice idea. I just don't think it will work well in practice. I would want to switch buffers and have to wait until some async candidates come in. Therefore I don't really find that convincing. Are you using such a setup with helm?

There are other scenarios which might be more convincing - combining multiple async search sources. But this is more on the abstract level I don't have a concrete use case in mind.

So for now I tend to keep things simple - only allowing static sources. Maybe also because the focus is on features that I really consider useful in contrast to adding features only for its own sake.

But while writing this response you still got me thinking how it would be done. Maybe it is even possible to implement this without much additional code. But I am still missing where I would really want this 😆

**Comment by indigoviolet** [comment]
> I would not want to switch buffers and have to wait until some async candidates come in. Therefore I don't really find that convincing. 

I agree with you, the buffer switching use case should not be blocked on the async candidates, which is why I think it needs special support: I would want buffers + recentf etc to load as soon as I hit `consult-buffer`, and the async sources to load "in the background"/as I type characters - so that if my buffer/recent file reaches the top of the list I hit return and switch immediately; but if I run out of buffers/recent files I can still get some candidate upon waiting for a bit.

> Are you using such a setup with helm?

I'm using consult now 😁 but yes, I was using such a setup with helm and I feel like it did work well.

```elisp
      (setq helm-mini-default-sources '(
                                        helm-source-buffers-list
                                        helm-ls-git-status-source
                                        helm-source-recentf
                                        ;; helm-source-projectile-files-list
                                        helm-ls-git-source
                                        helm-source-find-files
                                        helm-tramp--source
                                        helm-source-buffer-not-found
                                        helm-source-projectile-projects
                                        ))
```

**Comment by minad** [comment]
Okay, one technical difficulty I am seeing is that the async consult commands split the input string in an async filter and a synchronous filter. Something like this would not be desired I assume? This means the async multi sources would not receive any input and simply produce candidates.

**Comment by indigoviolet** [comment]
Just so I'm on the same page, you're referring to this ?:

>The input string is split into two parts, if the first character is a punctuation character, like #. For example #grep-regexp#filter->string, is split at the second #. The string “grep-regexp” is passed to Grep, the “filter-string” is passed to the fast Emacs filtering >to further narrow down the list of matches.

I think you're saying that in this context, the async command would have to return "all" project files (ie. no counterpart of `grep-regexp` from above), and all filtering would happen inside emacs (ie. only `filter-string` from above).

I'm guessing that's because you don't have the clear distinction between the "async input" and the "sync input" as above, and you'd have to think of the input to `consult-buffer` as the sync input (to match how it is used today). So I think it'd be fine for many small-to-moderate projects to just have (for example) `fd` generate the entire list of files and then do the filtering synchronously, like you're suggesting. 

Another approach to consider could be to debounce async candidate generation, and filter synchronously in between candidate generations. (I think you'd also want to kick off an async generation if the sync filter leads to an empty set). This is probably a bigger change, so it makes sense to start with what you suggested at first.

**Comment by minad** [comment]
> Just so I'm on the same page, you're referring to this ?:

Yes, this is what I referred to.

> So I think it'd be fine for many small-to-moderate projects to just have (for example) fd generate the entire list of files and then do the filtering synchronously, like you're suggesting.

In the case of small projects it might just be easier to generate everything statically and cache it. This brings us back to square one, the missing motivation for async multi sources.

> Another approach to consider could be to debounce async candidate generation, and filter synchronously in between candidate generations. (I think you'd also want to kick off an async generation if the sync filter leads to an empty set).

This sounds pretty complicated and would require a lot of hacks around completion styles and hooking into the completion system. Probably I would not want to have something like this. How is Helm solving this problem? Does it generate the async candidates right away? Does it pass the filter expression to the async sources?

**Comment by indigoviolet** [comment]
> How is Helm solving this problem? 

I haven't read helm code that deeply, but I believe it is [debouncing the candidates](https://github.com/emacs-helm/helm/blob/21443f6b037ad1b3554cdad7267625601416c9e0/helm.el#L394) and passing the pattern into the async [source](https://github.com/emacs-helm/helm/blob/7023ed51ee839806adb07537e23351326ce04fd2/helm-fd.el#L66-L100)

> In the case of small projects it might just be easier to generate everything statically and cache it. This brings us back to square one, the missing motivation for async multi sources.

How would you invalidate this cache? Or would you generate it each time `consult-buffer` is called -- in which case we break the buffer-switching use case, no?

**Comment by minad** [comment]
> How would you invalidate this cache? Or would you generate it each time consult-buffer is called -- in which case we break the buffer-switching use case, no?

Sure, this is a problem.

But overall my sentiment regarding this issue remains - I don't find the use case you are proposing compelling. Async is relatively heavy in comparison to static sources. I would not want to use async sources in consult-buffer even if debounced or delayed. Maybe I should have called the sources instead "collections" or "groups", not something dynamic like "sources", since this is what they are as of now.

The proposal you made with debouncing and only starting async when no candidates exist is something which could either be solved by manually switching from consult-buffer to consult-find via embark-become. Alternatively one could implement an automatic embark-become if no candidates are found in the consult-buffer sources. However if one really goes this route the async multi sources are probably easier to implement.

**Comment by indigoviolet** [comment]
Ok thanks, let's leave it here for now. I will explore `embark-become`.

**Comment by minad** [comment]
Okay, I will keep this issue open. Maybe more people will express there interest in this.

**Comment by minad** [comment]
@indigoviolet, did you look into embark-become? Does this help for your use case?

After reconsideration and asking some other people for opinions, if such a feature would be desired, I decided to close this issue since as of now there is no intention to implement it as of now and I don't foresee this changing in the near future. The focus is on simplicity, robustness and performance for the multi source commands. Having asynchronous sources will work against these goals. There are multiple scenarios when this feature will be reconsidered:

1. Someone comes up with a convincing use case for multi async sources, and maybe provides a patch. 
2. I stumble upon use case for multi async sources I would like to use myself, such that I would feel inclined to implement this myself.
3. Emacs gets support for async worker threads, which would allow offloading some computational work to worker threads running their own elisp interpreter via a message passing mechanism. Right now Emacs threading capabilities are severely limited. There are GIL threads (which are or were broken) and which are of no use if you want to offload computational work. Furthermore there is the possibility to asynchronously run processes or start web queries, which is quite heavy and can be used with the consult--read async support. There is the async package by John Wiegley, but as far as I know this also starts an extra heavy Emacs process for each async future.

**Comment by minad** [comment]
Some links:

* https://github.com/jwiegley/emacs-async
* https://github.com/skeeto/emacs-aio
* https://github.com/skeeto/thriter
* Blog post by Christopher Wellons about threads and generators: https://nullprogram.com/blog/2018/05/31/
* Blog post by Tom Tromey about threads: https://tromey.com/blog/?p=305, http://tromey.com/blog/?p=654

**Comment by indigoviolet** [comment]
Closing it is fine.

I tried embark-become, and while it is cool I don't think it really provides a better solution to the original problem I mentioned - having to distinguish between buffers/recently opened files and files that I haven't opened. When I encounter one of the latter, I have to go `embark-act` -> `embark-become` -> `consult-find`, and it mainly saves me the effort of retyping the search prefix at the cost of chaining three other shortcuts, which isn't that helpful imo.

**Comment by oantolin** [comment]
You can save one shortcut by binding embark-become to a key directly. You don't need to go through embark-act.

**Comment by minad** [comment]
It should even be possible to bind embark-become+consult-find to a single key. Maybe there is a direct way. If not unread-command-events will do the trick.

**Comment by minad** [comment]
Asynchronous `consult--multi` sources have arrived: https://github.com/minad/consult/discussions/1007#discussioncomment-11726712
