### ISSUE TITLE
Consult locate on OSX

### ISSUE THREAD

**Issue by mclearc** [minad/consult#205]
I use OSX/macOS (Catalina 10.15.7), which uses `mdfind` to search files. It used to be the case that I could do this: `(setq consult-locate-command '("mdfind" "-name"))` to utilize `mdfind` with consult. But this is no longer the case. Now, when I call consult locate (I'm using the most current version of consult) I get the error `split-string-and-unquote: Wrong type argument: stringp, ("mdfind" "-name")`.  Any idea what's wrong?  There have been so many changes to consult I'm not sure when this started being a problem.

**Comment by oantolin** [comment]
You just need to change it to `(setq consult-locate-command "mdfind -name")`.

**Comment by mclearc** [comment]
Yes, I should have said I already tried that. In such a case I get `/usr/bin/mdfind: no query specified` in the minibuffer, along with a list of the various options that can be input along with the query (such as "-name")

**Comment by minad** [comment]
See how consult-locate-command is written for the required format.

**Comment by oantolin** [comment]
Oh, sorry, I forgot the ARG and OPTS, `(setq consult-locate-command "mdfind -name ARG OPTS")`.

**Comment by oantolin** [comment]
@minad the docstring for `consult-locate-command` should mention ARG and OPTS.

**Comment by mclearc** [comment]
Thanks for this -- especially helpful since the format of the command has changed and the only other reference to `mdfind` in discussions here is [this comment](https://github.com/minad/consult/issues/103#issuecomment-752803942).

**Comment by minad** [comment]
Honestly, I don't think it would have helped in this case. The help buffer shows the following:

~~~
consult-locate-command is a variable defined in ‘consult.el’.
Its value is ("mdfind" "-name")
Original value was 
"locate --ignore-case --existing --regexp ARG OPTS"
~~~

Second, if you check the source of the variable you see it immediately. But I agree that it would be nice to document why we have ARG and OPTS. If you look at the consult-find-command, there I am adding wildcards to the ARG argument in order to increase the user friendliness of consult-find (#180).

**Comment by mclearc** [comment]
Thanks -- it might also be worth noting that I took `ARG` and `OPTS` to be relevant to the `locate` command and not to consult itself. But I'm also not a programmer so ¯\_(ツ)_/¯. Thanks for your work here!
