### ISSUE TITLE
Make `C-s C-s` recall last search

### ISSUE THREAD

**Issue by MicahElliott** [minad/consult#214]
With isearch, pressing `C-s C-s` pulls up the last search term. With consult-line, it's necessary to do `C-s M-r` to get the same effect.

**Comment by minad** [comment]
You mean if you use `consult-line` instead of isearch?

**Comment by minad** [comment]
You can bind `previous-history-element` to `C-s` in the consult-line local keymap, if this is desired.

~~~ elisp
(setf (alist-get #'consult-line consult-config)
      (list :keymap (let ((map (make-sparse-keymap)))
                      (define-key map "\C-s" #'previous-history-element)
                      map)))
~~~

**Comment by MicahElliott** [comment]
Awesome, that works!!

**Comment by minad** [comment]
Okay, I am glad this helps. You can add arbitrary keybindings to commands using this configuration method. I will add the example to the wiki.

**Comment by minad** [comment]
Wiki: https://github.com/minad/consult/wiki#add-command-local-keybinding

Note that I just pushed https://github.com/minad/consult/commit/d4232cc301e29396a14d730da55ce3ceaf68a810 which is needed for the version in the wiki.

**Comment by MicahElliott** [comment]
Sorry, just wanted to say, OMG this is fantastic! And thank you thank you again!! Last couple weeks been really stumbling over trying to train myself to do `C-s M-r`, and now I can suddenly re-search quickly without thinking again. Your work on this and selectrum and marginalia are so appreciated.

**Comment by minad** [comment]
Great to hear and thank you for the kind words! I guess we can close this issue here? If you have further questions/issues please let me know. Note that Selectrum is not my work (I am not sure, but I think did not commit a single line to Selectrum, only a bit of review help). Thanks should go to @raxod502 and @clemera! Marginalia has been co-written by @oantolin, who also develops the excellent Embark and Orderless packages!
