### ISSUE TITLE
Make (other-buffer) the default for consult-buffer

### ISSUE THREAD

**Issue by oantolin** [minad/consult#217]
What do you think about giving `consult-buffer` the same default that `switch-to-buffer` has, namely the buffer given by `(other-buffer)`? Some people (*cough, cough*) might have `C-x b RET` in their muscle memory and it would be nice if that worked the same way for `consult-buffer`.

On the other hand that might be a little awkward now that `consult-buffer` has configurable sources, I guess having that as default only makes sense if the use has not removed `consult--source-buffer` from the list of sources. Can a source have a `:default`? If not maybe that's the nicer fix, and `consult-multi` can collect all defaults from sources that have them into a single list-valued default.

**Comment by minad** [comment]
Okay, I thought it behaves similarly since the current buffer is moved to the end of the list and the last buffer appears at the top. I guess this works only on Selectrum like this? Is default=other-buffer all that is needed? One can set the default for consult-buffer by setting consult-config, but this is obviously insufficient since it is static. The only possibility as of now is to advise consult-buffer and set consult-config in the advice. Since completing-read default can be a list it would work to collect the defaults from the sources calling the corresponding default functions. Alternatively I could only use the first non-nil default when trying the sources in order. I have to think a bit about it.

**Comment by oantolin** [comment]
Ha! Selectrum strikes again: you are right, in Selectrum pressing `RET` immediately does take you to `(other-buffer)`.  But in Icomplete and default completion and initial `RET` does not accept the first candidate but the `default` argument to `completing-read`; so pressing `RET` immediately actually doesn't do anything in `consult-buffer`.

I'm currently using this to get the behavor I want but I feel that it should be easier to configure than this, which is why I opened this issue:

```elisp
(defun config-default-buffer (fn &rest args)
  (let* ((idx (seq-position consult-buffer-sources 'consult--source-buffer))
         (buf (buffer-name (other-buffer)))
         (def (concat (char-to-string (+ consult--tofu-char idx)) buf)))
    (add-text-properties 0 1
                         `(invisible t consult-multi (buffer . ,buf))
                         def)
    (cl-letf (((alist-get 'consult-buffer consult-config)
               `(:default ,def)))
      (apply fn args))))

(advice-add 'consult-buffer :around #'config-default-buffer)
```

**Comment by oantolin** [comment]
Oh, since `consult-buffer` interprets un-tofu-ed strings as buffers I can get away with the much simpler:

```elisp
(defun config-default-buffer (fn &rest args)
  (cl-letf (((alist-get 'consult-buffer consult-config)
             `(:default ,(buffer-name (other-buffer)))))
    (apply fn args)))

(advice-add 'consult-buffer :around #'config-default-buffer)
```

Maybe that's already simple enough.

**Comment by oantolin** [comment]
Oh, by the way, the docstring for `consult-config` doesn't specify the format for the variable. I thought it was an alist of command names to alists, but it is an alist of command names to **plists**.

**Comment by oantolin** [comment]
Plists are a much more natural choice for this, so I don't know why I first guessed alists, but the point is that the docstring should say it's plists.

**Comment by minad** [comment]
Okay, you are using exactly what I described above. This is certainly not what is intended and just an oversight of mine given my unfair Selectrum bias. This should definitely be fixed since Consult aims to work as well with Icomplete and default completion. I am just not yet sure about the best way. I don't want to overcomplicate the multi sources. Maybe it would be sufficient to specify a :default flag field. The first item of the first source specifying :default=t could be used.

**Comment by oantolin** [comment]
Or you could just decide that the first candidate in the first source is the default, without making it configurable. I think that would be fine.

**Comment by minad** [comment]
Well but that would imply that there is always a default which may not be desired.

**Comment by oantolin** [comment]
It does bother me a tiny bit that configuring the default I wanted is only simple because I happened to want a buffer and `consult-buffer` interprets strings with no prefix as buffers. If I wanted to make some bookmark the default, I would need to add the tofu myself as in the first function.

**Comment by minad** [comment]
Yes sure. This is not good. So far I think using a default flag for the source is the best solution.

**Comment by oantolin** [comment]
Yeah, that seems like it would comfortable to use..
