### ISSUE TITLE
consult-outline loses focus when one hits <TAB>

### ISSUE THREAD

**Issue by revrari** [minad/consult#220]
If I search for a headline in an orgmode file using `consult-outline`, and that headline contains tags, it loses focus if I hit `<TAB>`. I sometimes prefer to hit `<TAB>` first before `<RET>` to make sure I have the correct headline.

I am using Emacs 27, icomplete, consult and marginalia

**Comment by minad** [comment]
I seem to be unable to reproduce this. I am usually using Selectrum, so my familiarity with Icomplete is a bit limited. Can you please create a minimal configuration showing the issue, see https://github.com/minad/consult#bug-reports. It would also be good if you show me an org mode snippet which has the problem. You often send videos, and I often have problems to play these (video codec issues etc). Text snippets are often better since they give me a direct way to reproduce. Only in rare cases where these explanations do not suffice, an image or a video is necessary.

**Comment by oantolin** [comment]
It sounds like the issue I described [in this comment](https://github.com/minad/consult/pull/218#issuecomment-778825306).

**Comment by minad** [comment]
@revrari Any success in creating a minimal reproducible example?

**Comment by revrari** [comment]
@minad will submit presently.

**Comment by revrari** [comment]
I can reproduce a minimal example with this:
;; Minimal setup using the default completion system
```
(package-initialize)
(require 'consult)
(setq completion-styles '(substring))
(require 'icomplete)
```
I cannot with this:
;; Minimal setup using Selectrum
```
(package-initialize)
(require 'consult)
(require 'selectrum)
(selectrum-mode)
(setq completion-styles '(substring))
```
The problems seems to me to be the way consult interacts here with `icomplete`.
It is similar to this issue:
https://github.com/minad/consult/pull/218#issuecomment-778825306

**Comment by revrari** [comment]
It is not a big issue for me. I am happy to close it.

**Comment by minad** [comment]
And how do I exactly reproduce the issue? Do you have an org file showing the problem? What do I have to press in order to reproduce the issue?

**Comment by minad** [comment]
The minimal example

~~~ elisp
(package-initialize)
(require 'consult)
(setq completion-styles '(substring))
(require 'icomplete)
~~~

does not use icomplete btw, since you do not activate icomplete-mode.

**Comment by minad** [comment]
I managed to watch the video. I think the issue is that in your case when you complete the long headline 

~~~
* TODO Some headline                                                                                                                                                    :tag:
~~~

then when you press TAB the point jumps to the right and the actual headline text is not shown anymore. Instead you see this small `<-` arrow indicator. Did you mean that by "losing focus"? For me losing focus usually means that some other window/widget gets the focus, which is not the case here. If there is an issue here after all it is rather a problem of the completion system, Icomplete/Selectrum or default completion. I hope this helps. If not, please tell me.

**Comment by revrari** [comment]
Yes, I did mean that the actual headline text is not shown anymore. It could be a problem with `icomplete`, but I do not have the problem when I use `icomplete` on its own and use another outline function to access the menu. It only occurs with consult-outline. Thanks for your helpful answer.

**Comment by revrari** [comment]
Cannot reproduce with just this:
```
(package-initialize)
(require 'consult)
(setq completion-styles '(substring))

```

**Comment by minad** [comment]
> Yes, I did mean that the actual headline text is not shown anymore.

Okay. This is an Icomplete rendering issue then. The only thing I could do is to modify consult-outline to replace many consecutive whitespaces by fewer whitespaces. Would that be desired?

> It could be a problem with icomplete, but I do not have the problem when I use icomplete on its own and use another outline function to access the menu. 

Which other outline function do you mean? Please be precise. I need very reproducible steps.

**Comment by minad** [comment]
I could apply such a regular expression to the outline candidates for example:

~~~ elisp
(replace-regexp-in-string "[[:space:]]\\{4,\\}" "    " ...)
~~~

**Comment by minad** [comment]
Unfortunately the idea to replace multiple consecutive spaces with a fewer spaces does not work. The problem is that consult-outline jumps to the position of the first match. If spaces are deleted the positions will be wrong. It would be possible to work around this using string properties but I think this is a bit too much of a hack.

~~~ elisp
                    (replace-regexp-in-string
                     "[[:space:]]\\{2,\\}" (lambda (s) (propertize s 'display " "))
                     (consult--buffer-substring (line-beginning-position) (line-end-position))))
~~~

I tried this for a while and I think it is unexpected if the candidate looks different than the line which is selected. For these reasons I think it is better to keep it as is and live with the downsides. It would probably be better if the scrolling behavior of the completion system is fixed instead.
