### ISSUE TITLE
Calling consul-compile-error from any buffer

### ISSUE THREAD

**Issue by astoff** [minad/consult#222]
Shouldn't this be possible? I don't think `*compilation*` buffers are explicitly associated to a buffer or a project, but one could collect the compilation errors from the most recent compilation buffer, or all compilation buffers. If I have already switched to a compilation buffer, I see less value in calling `consult-compile-error`.

Then there's the case of auctex, which seems to have reinvented the compilation buffer. I wonder if `consult-compile--error-candidates` would be easy to adapt to this case (not that you go out of your way for compatibility with reinvented things).

**Comment by minad** [comment]
Yes, this command is not super useful and fully baked in its current form. However I am also unsure if it makes sense to iterate over all compilation buffers, since for example grep buffers are also compilation buffers. Maybe one could use some filter function which selects the compilation buffers. But then it would also be neat if one could somehow use the consult-project-root-function to check if the current compile buffer belongs to the current project, but I have no idea if this is possible. Any ideas?

**Comment by minad** [comment]
Regarding auctex, if it is not using the same compilation--message, compilation--loc structs, I don't have much hope in reusing code. I would rather try to modify auctex such that it uses the standard infrastructure. If this is not possible there is no other way than writing an extra consult-auctex package, if it is needed after all.

**Comment by astoff** [comment]
The first line of ancompilation buffer reads
> But then it would also be neat if one could somehow use the consult-project-root-function in the filter function to check if the buffer belongs to the current project, but I have no idea if this is possible. Any ideas?

Sure: check the  `default-directory` of the compilation buffer. Also, the major mode of a compilation buffer and a grep buffer are different.

As to auctex, I agree. I think it's a recent TeX feature (meaning, from after 1982) to print error messages in a format compatible with other compilers. Still, it's funny how much stuff auctex reinvents.

**Comment by minad** [comment]
> Sure: check the default-directory of the compilation buffer. Also, the major mode of a compilation buffer and a grep buffer are different.

Right, makes sense. Maybe then using a simple filter function would be the way to go. Either use all compilation buffers or if there is a project root function, check the default-directory. Are you interested in creating a PR?

**Comment by astoff** [comment]
All right, I've sketched this and I will test it a bit before making the PR. Couple of questions in the meanwhile:

1. What's your preferred way to check that a file belongs to a project? We can select a compilation buffer by comparing its directory with the return value of `consult-project-root-function`, or just check that the current buffer's directory is a subdirectory of the compilation buffer's directory.
2. If we consider as compilation buffers those whose major mode is `eq` to `compilation-mode`, we correctly get rid of grep buffers and the like, but we will also miss things like `emacs-lisp-compilation-mode`. Maybe those false negatives are not too interesting anyway, but we could also check both the result of `compilation-buffer-p` and whether the major mode name contains `"compilation"`; or `compilation-buffer-p` and whether the buffer name contains `"compil\\(ation\\|e\\)"`. What do you think?
3. Do you care about a scenario where there are multiple compilation buffers for the current project? I think typically there will be only one `*compilation*` buffer, which is actually shared by all projects.

**Comment by minad** [comment]
> What's your preferred way to check that a file belongs to a project? We can select a compilation buffer by comparing its directory with the return value of consult-project-root-function, or just check that the current buffer's directory is a subdirectory of the compilation buffer's directory.

I don't understand what you mean here. If we want to determine if a compilation buffer belongs to the current project, we call the consult-project-root-function in the current buffer (could be any kind of buffer), then iterate over all compilation buffers and compare their default-directory with the root. If there is no root, just use all compilation buffers.

> If we consider as compilation buffers those whose major mode is eq to compilation-mode, we correctly get rid of grep buffers and the like, but we will also miss things like emacs-lisp-compilation-mode. Maybe those false negatives are not too interesting anyway, but we could also check both the result of compilation-buffer-p and whether the major mode name contains "compilation"; or compilation-buffer-p and whether the buffer name contains "compil\\(ation\\|e\\)". What do you think?

Yes, that's one of the problem why I have avoided this until now. There seems to be also a compilation-minor-mode, which we may want to handle. It is really not clear to me what the best way is. Use all buffers which are either derived from compilation mode or have the minor mode activated and then use an exclusion filter, preconfigured to exclude for example grep buffers, since they should not be included in any case? The filter could either be a regexp on the mode or a list of mode symbols or a function. Many possibilities I guess.

> Do you care about a scenario where there are multiple compilation buffers for the current project? I think typically there will be only one *compilation* buffer, which is actually shared by all projects.

Yes, I would like to handle multiple compilation buffers per project. And each project could have multiple buffers. I am not sure how common this is. But maybe if a @oantolin's epithet package is used, such a scenario can occur when all the buffers are renamed right away. I don't think that this multi-buffer handling will introduce significant complexity, so why not?

**Comment by astoff** [comment]
> There seems to be also a compilation-minor-mode, which we may want to handle.

I don't know where those are used; apparently nowhere in Emacs itself. But `compilation-buffer-p` succeeds in this case, so we should be covered.

> use an exclusion filter, preconfigured to exclude for example grep buffers, since they should not be included in any case?

What if we just embrace the confusion Emacs makes here, and jumble together all compile-like stuff pertinent to the current buffer, be it grep, compile or whatever else?

> I don't think that this multi-buffer handling will introduce significant complexity, so why not?

Sure, this is easy to do. Now, you seem to suggest to use *all* compilation buffers when we can't find anything specific to the current buffer. I'd rather throw an error in this case, "No compilation buffers found for this buffer".

**Comment by minad** [comment]
>      I don't know where those are used; apparently nowhere in Emacs itself. 

Okay, I was confused when I saw this minor mode. But you are right, we are covered.

> What if we just embrace the confusion Emacs makes here, and jumble together all compile-like stuff pertinent to the current buffer, be it grep, compile or whatever else?

I am not perfectly happy with that decision, but let's keep it for now like this and see how it goes. I could imagine that I would like to exclude some buffers, e.g., in particular grep buffers.

> Sure, this is easy to do. Now, you seem to suggest to use all compilation buffers when we can't find anything specific to the current buffer. I'd rather throw an error in this case, "No compilation buffers found for this buffer".

That's also okay given that you solved the project detection differently in a better way. I had in mind that we should show all errors if no project is found for example. It is good as it is now!
