### ISSUE TITLE
consult-yank-pop doesn't work correctly on rectangle mode

### ISSUE THREAD

**Issue by TxGVNN** [minad/consult#229]
Hi @minad,

I see consult-yank-pop can not paste exactly as `yank` built-in when I want to paste text that I copied from rectangle mode.

**Comment by oantolin** [comment]
Oh no, completing-read with its bad habit of stripping properties strikes again! I think the problem is that rectangle have a `yank-handler` text properties, that the consult-yank functions miss because they get the string from `completing-read`.

It should be easy to fix: `consult--yank-read` shouldn't directly return the return value from `consult--read`, but instead look it up again in the kill ring.
