### ISSUE TITLE
Toggling preview during completion

### ISSUE THREAD

**Issue by dalgong** [minad/consult#233]
Sometimes I want to enable/disable preview while running a consult command, not pre-configuring with consult-config or preview-key. For example, while M-x consult-recent-file, I enjoy looking the preview of files until I hit files mounted from sshfs, etc which is very slow and I want to disable preview momentarily.

**Comment by minad** [comment]
Thank you for the feature proposal. I have considered this but decided against it. It is not possible to configure Consult such that it supports enabling/disabing preview during the session and I am not inclined to change this. The use case you are describing won't work well, since at the point where you have hit a sshfs file it is already to late and you are already observing the slowdown. 

In other cases related to `consult-buffer` there are similar bad side effects (e.g. when using EXWM or Tramp), where Emacs hangs or the windows are rearranged in an undesired way. There are multiple solutions for the problem:

* Filter the candidates such that the problematic candidates do not appear in the list. This is the preferred solution for Tramp and EXWM when using `consult-buffer`, see the wiki configuration https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers. However this solution won't work directly for `consult-recent-file`, which is not based on multi sources. But we can adapt it as follows:

~~~ elisp
(defun consult-recent-file-with-filter ()
  (interactive)
  (let ((recentf-list (compute-the-filtered-recentf-list-here))) ;; filter the list of recent files
     (consult-recent-file)
~~~

* Alternatively one can overwrite the `:state` function of the `consult-recent-file` command, such that sshfs files are filtered there, but this goes a bit deeper into the internals of the library.

* You may still want to reconsider disabling automatic previews for `consult-recent-file` only. You can even set two manual preview keys `S-up` and `S-down` for example, such that you can scroll over the candidate list with preview. See https://github.com/minad/consult/wiki#configure-s-ups-down-preview-keys.

**Comment by minad** [comment]
I experimented a bit and it is actually easy to enable/disable preview during an active session. I documented this in the wiki, see https://github.com/minad/consult/wiki#toggle-preview-during-active-completion-session. I won't support this officially but it should be possible to use this in your case.

~~~ elisp
(defvar-local consult-toggle-preview-orig nil)

(defun consult-toggle-preview ()
  "Command to enable/disable preview."
  (interactive)
  (if consult-toggle-preview-orig
      (setq consult--preview-function consult-toggle-preview-orig
            consult-toggle-preview-orig nil)
    (setq consult-toggle-preview-orig consult--preview-function
          consult--preview-function #'ignore)))

(define-key selectrum-minibuffer-map (kbd "M-P") #'consult-toggle-preview)
~~~

**Comment by floli** [comment]
I may add a question to this issue: Is is possible to show previews only for files that are already opened, e.g. no preview for recent files? Use case it that whenever I have a recent python or c++ file accidentely previews lsp-mode starts up which needs some time for large projects and slows down selection.

**Comment by minad** [comment]
@floli Yes, such a configuration is documented in the README.

**Comment by agzam** [comment]
@minad I'd like to set `consult-preview-key` for everything but keep `'any` for consult-line`, i.e., disable auto-preview everywhere except "swiper". Do I have to tweak it using `consult-customize`? Can't figure this out.

**Comment by minad** [comment]
@agzam Yes, `consult-customize` is the answer. See the examples in the README.

**Comment by agzam** [comment]
Oh, yes, I figured it out. It was obscured by Doom's internals. 

```
(consult-customize +default/search-buffer :preview-key 'any)
```

worked for me. Thank you!

**Comment by agzam** [comment]
@minad I'm sorry, one more question (I really couldn't figure out where to post it).

for grouped results e.g., search results across buffers - is there a way to jump to previous/next group? Thank you.

**Comment by minad** [comment]
Yes, there is. Please read the Consult and Vertico READMEs. I am afraid, but sometimes there is no other way than reading the manual or at least use grep/consult-line on them. :shrug:

**Comment by agzam** [comment]
Yes, I apologize for the noise. I feel stupid, I knew this, but somehow for a moment I forgot. I'm trying to multi-task here, and it's not working well :).

I just needed to check vertico-map keybindings. vertico-next-group is right there. Sorry for being a nuisance.

**Comment by minad** [comment]
> And if you need to type square bracket (which let's admit, doesn't happen very often), you can do C-q [

Yes, this is something I find interesting. One could make much greater use of `C-q` and free more of the normal insert keys for specialized commands. I recently considered using this approach more in my config but so far didn't come up with actual scenarios where I would want to use that. Messing with keybindings is an endless rabbit hole.

**Comment by agzam** [comment]
Oh, yes, my favorite trick is this:

```
(map! :map flyspell-mode-map
      :i ",," #'flyspell-auto-correct-previous-word
      :i ", SPC" #'comma-smart-insert)
```

Sorry for the Doom-syntax, I think it's obvious what's happening here.

**Comment by minad** [comment]
Indeed, this looks like a nice trick one could use for all kinds of characters which appear mostly in combination with something else. But then, I think overall such behavior would annoy me more than I would actually profit from the additional prefix key. The root problem is really that the Emacs key map is just too crowded out of the box. It would be so nicer if more keybindings would be organized under mnemonic prefix keys such that we get more free space. I mean not even the C-c keymap is fully at the disposal of the user.

**Comment by vspinu** [comment]
Shouldn't the `consult-toggle-preview` function be part of the core? It seems like a very common requirement.  

In helm and ivy I am using it all the time (`helm-follow-mode` and `ivy-toggle-calling` respectively).

**Comment by minad** [comment]
@vspinu It doesn't seem to me that this feature has been widely requested. The Consult preview configuration is already quite flexible (manual/auto, debouncing), so there is no need to put another mechanism on top.

**Comment by vspinu** [comment]
If I understand correctly currently there is no easy way to start with deactivated preview and then turn it on demand. In fact the current `:preview-key` mechanism is orthogonal to what I am after.

A complete API in my opinion would involve a global boolean state, say `consult-preview` which I can activate/deactivate globally or per command like so:

```el
(setq consult-preview nil)

(consult-customize
 consult-line
 :preview t
 :preview-key '(:debounce 0.4 any))
```

I think that for `consult-line` and `grep` the auto preview is warranted, but for buffers or files it is not except of rare circumstances. I personally don't like my current buffer to be covered with no good reason - it's distracting, not very useful in general and there might be text in the original buffer useful for the completion.

One extra reason for the global option is that the current default (of auto-activating preview everywhere) is inconsistent with non-consult tooling (like `find-file` or `switch-to-buffer`) or even `consult-dir` which uses `find-file` underneath.

**Comment by minad** [comment]
@vspinu 

> If I understand correctly currently there is no easy way to start with deactivated preview and then turn it on on-demand. The :preview-key mechanism is somewhat orthogonal to what I am after.

Consult supports manual preview keys. This is as good or even better. You can invoke preview manually for candidates of interest instead of first toggling and then scrolling through candidates. I understand that you want to replicate your workflow, but I don't see the point of the addition. Note that Consult and the other packages are somewhat more restricted and opinionated than Helm and Counsel. It is okay if there is no exact equivalent for every functionality.

> A complete API in my opinion would involve a global boolean state, say consult-preview which I can activate/deactivate globally or per command like so:

It would only make sense to add a flag which affects the `any` preview key. If we specify a manual preview key, we want the key to invoke preview in any case, even if the flag is false.

> I think that for consult-line and grep the auto preview is warranted, but for buffers or files it is not except of rare circumstances. I personally don't like my current buffer to be covered for no good reason - it's distracting, not very useful in general and there might be text in the original buffer useful for the completion.

I disagree. I like the buffer preview. But it is configurable for this reason. You can configure a manual preview key or set the preview key to nil.

> One extra reason for the global option is that the current default (of auto-activating preview everywhere) is inconsistent with non-consult tooling (like find-file or switch-to-buffer) or even consult-dir which uses find-file underneath.

I am aware of that inconsistency. Preview is only enabled by default such that the users become aware of the feature. My recommendation is to configure debounced preview for the commands where preview is potentially slow. This is documented in the README.

Ideally one could extract the preview code from Consult and create a Marginalia-like package which extends existing commands with preview. But that will be quite complicated.

**Comment by hmelman** [comment]
FWIW, I would like this functionality as well.  I'm not a big fan of live previews and would prefer to keep them off and turn them on only when I feel like it in a specific circumstance.  I don't think this is hold over from other completion systems but a reasonable workflow to want.  I've been making due by just turning off preview for `consult-buffer` via `(consult-customize consult-buffer :preview-key nil)` which has worked pretty well for me.

**Comment by minad** [comment]
@hmelman You could configure a manual preview key, e.g., even M-up/down to move and preview. up/down will still only move without preview. I think that's better than the toggle.

**Comment by vspinu** [comment]
@minad 
> You could configure a manual preview key, e.g., even M-up/down to move and preview.

I don't think this works ATM. I have tried setting "C-n", "C-p" to preview but they got disabled in the map (set to `#'ignore`).   So I couldn't both move and preview simultaneously. If that works then the problem is indeed solved.

It's too late for me to re-try and reproduce this but I will re-visit this tomorrow.

**Comment by vspinu** [comment]
I see, so explicit mapping into vertico is really necessary. Just with configuration `(consult-customize xyz :preview-key (list (kbd "C-n") (kbd "C-p")))` it would not work.

Relatedly, how do I set the configuration for all functions at once? There doesn't a whitelisting options like:

```el
  (consult-customize t :preview-key (list (kbd "C-n") (kbd "C-p")))
```

**Comment by vspinu** [comment]
Nevermind. There is a global for that:

```el
  (setq consult-preview-key (list (kbd "C-n") (kbd "C-p")))
```

**Comment by mrcnski** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1363467?v=4&amp;size=80">@vspinu](https://github.com/vspinu?rgh-link-date=2022-12-19T09%3A50%3A29.000Z) It doesn't seem to me that this feature has been widely requested. The Consult preview configuration is already quite flexible (manual/auto, debouncing), so there is no need to put another mechanism on top.

Well, here's another vote for this feature. :) I've tried the examples in the wiki, linked above, but seems to me like they don't work.

https://github.com/minad/consult/wiki#toggle-preview-during-active-completion-session kind of works, but only for consult commands that are configured to have an initial preview. And there's no way to run those commands without the initial preview and enable the preview on-demand with `consult-toggle-preview`.

https://github.com/minad/consult/wiki#configure-s-ups-down-preview-keys doesn't work for me at all.

**Comment by minad** [comment]
@mrcnski Oh, I believe the wiki needs an update regarding the new keybinding syntax and keymap API introduced in Emacs 29:

~~~ elisp
(keymap-set vertico-map "S-<up>" #'vertico-previous)
(keymap-set vertico-map "S-<down>" #'vertico-next)
(consult-customize consult-recent-file :preview-key '("S-<up>" "S-<down>"))
~~~
