### ISSUE TITLE
some unexpected behaviors about  consult-focus-lines

### ISSUE THREAD

**Issue by jixiuf** [minad/consult#243]
I would like using `consult-focus-lines` filter lines for dired and package, but there are some unexpected
behaviors 
 suppose the point is on `consult.el` and call `consult-focus-lines` with `git` as keyword 
before
<img width="695" alt="image" src="https://user-images.githubusercontent.com/461743/110211593-3c031900-7ed2-11eb-8d38-56045370241c.png">

after:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/461743/110211387-538dd200-7ed1-11eb-931b-2e9a9625b316.png">
the point is at end of buffer, 
1. I hope it can move the point to `.git` after `RETURN` is pressed 

2. call `dire-previous-line`  to move the point to `.git`, it looks like this, 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/461743/110211469-a9fb1080-7ed1-11eb-9daa-25f99c80a822.png">
but  `what-cursor-position` report the point is `1`
 and I press "RETURN" it report 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/461743/110211559-09f1b700-7ed2-11eb-9ba2-bfc0b94638d9.png">

**Comment by minad** [comment]
I just tried this and the cursor movement is indeed unexpected. But I am unsure if there is anything we can do about it. We could add some special dired workarounds, but I am not eager to do that. Dired moves the cursor itself and tries to ensure that the cursor is on top of a filename. In the case you mentioned if you move the cursor to the right it will work. If you have multiple files, and filter using `consult-focus-lines` you can still move between the filtered file names with the up and down keys. The weird cursor jumping only happen when you move the cursor to the end.

**Comment by minad** [comment]
I just tried `list-packages` and there everything seems to work well. When rebinding the commands in `dired` to `previous-line/next-line` instead of `dired-previous-line/dired-next-line` it seems to work in a more expected way. That is the workaround I would recommend for now. Maybe `dired-previous-line/dired-next-line` could be improved such that it works better?

**Comment by oantolin** [comment]
A different thing I noticed while trying this out is that `consult-focus-lines` also matches text in the invisible portions of lines. I like using `dired-hide-details-mode` which works by putting a property of `invisible` with value `dired-hide-details-detail` on part of each file line.

I think it would probably be more intuitive to match only against visible text.

**Comment by minad** [comment]
This function seems to work around the problem with the invisible overlays. 

~~~ elisp
(defun dired-next-line (arg)
  (interactive "^p")
  (beginning-of-line)
  (forward-line arg)
  (while (and (not (eobp)) (not (bobp)) (invisible-p (point)))
    (forward-line arg))
  (dired-move-to-filename))
~~~

**Comment by minad** [comment]
> I like using dired-hide-details-mode which works by putting a property of invisible with value dired-hide-details-detail on part of each file line.

That might be better, but I would say that this is out of scope of `consult-focus-lines`. I think it is better to keep the command generic instead of adding special handling per major mode. But dired may be important enough to make an exception?

> I think it would probably be more intuitive to match only against visible text, but it's not really a big deal.

Are there bad side effects due to that? As it currently works, if you filter multiple times using `consult-focus-lines` it only makes more lines invisible, but the already invisible lines are kept.

**Comment by minad** [comment]
> A different thing I noticed while trying this out is that consult-focus-lines also matches text in the invisible portions of lines.

Ah, you meant *invisible portions*. That's right. It may make sense to filter that out by skipping the invisible content. There are many more commands affected by that. `consult-line`, `consult-keep-lines`, ...

**Comment by oantolin** [comment]
> That might be better, but I would say that this is out of scope of `consult-focus-lines`.

I'm confused, what did you think I was proposing that is dired specific? My only proposal was that `consult-focus-lines` should only match visible text.

**Comment by oantolin** [comment]
Oh, crossed messages! You already reread what I wrote earlier. :)

**Comment by oantolin** [comment]
So right now `consult-focus-lines` skips lines that are completely invisible but if only a part of a line is invisible, it does allow matches in that invisible part? Is that right?

**Comment by minad** [comment]
What I meant about *mode specific* is that dired has its own invisibility mechanism and it seems the overlay mechanism used by `consult-focus-lines` does not work well together with how dired usually hides its things. So I thought you meant that one could use the dired specific mechanism to hide using `consult-focus-lines`, but this is probably not a good idea.

**Comment by minad** [comment]
> So right now consult-focus-lines skips lines that are completely invisible but if only a part of a line is invisible, it does allow matches in that invisible part? Is that right?

Yes.

**Comment by minad** [comment]
We could use `selectrum--display-string` to obtain the strings for filtering, see https://github.com/raxod502/selectrum/blob/21cee863a07f9114172d5b9bd33eeed7f11bcf66/selectrum.el#L1633.

**Comment by oantolin** [comment]
> > So right now consult-focus-lines skips lines that are completely invisible but if only a part of a line is invisible, it does allow matches in that invisible part? Is that right?
> 
> Yes. Lines which are already completely invisible are filtered too, but they are simply not affected by making them invisible again.

Oh, I see. So `consult-focus-lines` (without `C-u`) only ever makes lines invisible. For invisible matching lines it doesn't ensure they become visible.

**Comment by minad** [comment]
> Oh, I see. So consult-focus-lines (without C-u) only ever makes lines invisible. For invisible matching lines it doesn't ensure they become visible.

Yes, the intention of this was that you can do multiple filterings to narrow down in each step.

**Comment by oantolin** [comment]
> Yes, the intention of this was that you can do multiple filterings to narrow down in each step.

I was aware of that behavior but didn't know how it was implemented. Instead of matching against all lines and making non-matching lines invisible (whether they were or not), an alternative would be to not match against invisible text. That would have the same effect of allowing successive filtering. I hadn't thought about it very much, but I sort of had the idea that was how it worked and was surprised when I discovered that it does match against invisible text, that's all.

**Comment by minad** [comment]
> Instead of matching against all lines and making non-matching lines invisible (whether they were or not), an alternative would be to not match against invisible text. That would have the same effect of allowing successive filtering.

If I recall correctly, I think I considered checking if a line is already invisible and exclude it from the matching and decided against it to keep things simpler. But I didn't consider cutting out invisible parts of the text. I am unsure if this is easy to do, since if you use `buffer-substring` you get invisible properties, but you do not get the invisibility information from the overlays.

**Comment by oantolin** [comment]
Yeah, I'm not sure cutting out invisible parts is worth it, probably not. I think dired buffers with hidden details are the only place I've wanted this. But I don't even usually use `consult-focus-lines` there, since dired has its own mechanisms to remove lines and I use those.

**Comment by minad** [comment]
@jixuf I close this issue since there is not much we can do to work around the issue.

1. You may want to use a modified `dired-next-line` command
2. Maybe the upstream movement commands could even be improved to cooperate better with overlays added by third party libraries
3. You can use the mechanism to omit lines,which is provided by dired-x.el. I think @oantolin mentioned that already. These are the `dired-omit-*` commands

**Comment by jixiuf** [comment]
the `(point-at-bol)` is 81 for `.git`
<img width="860" alt="image" src="https://user-images.githubusercontent.com/461743/110244816-7e445d00-7f9b-11eb-8975-118e52f5a1df.png">


suppose the point is at any position of line 1 , before `consult-focus-lines` is called
<img width="656" alt="image" src="https://user-images.githubusercontent.com/461743/110244683-d7f85780-7f9a-11eb-8c0f-7003cf68e2fe.png">

then   call `consult-focus-lines` with `git` as keyword

<img width="557" alt="image" src="https://user-images.githubusercontent.com/461743/110244739-23ab0100-7f9b-11eb-9620-f79f1e228c67.png">

I think the point should move to `81` instead of `1`

**Comment by minad** [comment]
@jixiuf 

> I think the point should move to 81 instead of 1

Why? `consult-focus-lines` does not move the point at all. It only manipulates overlays.

**Comment by jixiuf** [comment]
> > I think the point should move to 81 instead of 1
> 
> Why? `consult-focus-lines` does not move the point at all. It only manipulates overlays.

Ok , I don't know that.
> Did you try the modified `dired-next-line` command, which I posted above?

I tried, it works , I will use the modified version of dire-next-line. 

Thanks.
