### ISSUE TITLE
How can make a function to choose a label for a latex file?

### ISSUE THREAD

**Issue by linwaytin** [minad/consult#250]
Sorry for so many questions. I'm switching from `ivy` to this package.
Because the live preview of `Consult` is awesome, I feel this function is possible and want to implement it.

The idea is that in a latex file, we define `\label{name}` for equations.
Later in the document we can use `\eqref{name}` to reference the equation.
I'm thinking to make a function which can show a list of all labels in the file, and allow live preview so we know what equation it refers to. This is where the live preview is very useful, because when you have a lot of equations, it's hard to imagine the equation by just a label.
After selecting a candidate, that function should automatically insert `\eqref{name}` for the selected label.

I'm not an advanced Emacs user but would like to learn how to do this.
Could anyone please give me some hint?
Thank you.

**Comment by minad** [comment]
I try to be helpful but the question is a bit too broad. Such a command is definitely possible. I suggest you do the following:

1. Play with the `completing-read` or the more advanced `consult--read` API:

~~~ elisp
(consult--read '(eq1 eq2 eq3) :prompt "Equation: ")
~~~

2. Then you check out the commands which do something related to the functionality you are interested in. This is `consult-yank-pop` and in particular the `consult--yank-read` helper function. This function implements candidate preview.

3. Since the task you are planning requires extracting the equations/labels from the buffers you should also familiarize yourself with the `re-search-forward` API to search the current buffer. See for example https://www.emacswiki.org/emacs/ElispCookbook#h5o-35 and https://www.gnu.org/software/emacs/manual/html_node/eintr/re_002dsearch_002dforward.html#re_002dsearch_002dforward.

But may I ask why the labels you are using for the equations are not meaningful?

**Comment by linwaytin** [comment]
Thanks a lot. I will study these materials.

For your question, sometimes it is hard to make a good label for an equation within a long derivation.
Say we are solving a lengthy physics problem using `F=ma`.
After a few steps, we transform `F=ma` to something like `d^2 x/dt^2 = x - x^3`. 
To fully describe this equation and so I can remember what I refer to, I need a lengthy name like `newton-with-normalized-force`, which is not convenient and is a mental burden.
Thus I usually call it like `newton3`, but then I need a helper to remind me what it is.

There is a function in `AucTeX` called `RefTeX`, which can show the LaTeX code of the corresponding equation in the minibuffer.
`RefTeX` is nice and I use it. The only drawback is that when the equation is complicated and long, it is still not easy to know what the equation is by just looking at the code.
This is why I think the live preview of `consult` can be very helpful in this situation, which can jump temporarily to the position of the equation.

Thank you for making this great package.
