### ISSUE TITLE
counsel-outline equivalent that shows parent headings

### ISSUE THREAD

**Issue by noctuid** [minad/consult#264]
Is there an equivalent of `counsel-outline` and `counsel-org-goto`? These commands show the full heading path including parent headings (e.g. "parent/child1/child2..."). `consult-imenu` is somewhat similar but only shows up to depth 2 and isn't as readable (I tried customizing `org-imenu-depth` but that doesn't seem to change things).

Also, I've noticed `consult-outline` does not show the correct face/color for all results (e.g. some level 3 headings are correctly blue, others are just white). Is this a known issue? I can make another issue and try to provide a reproducible example if this is not easy to reproduce.

**Comment by minad** [comment]
> Is there an equivalent of counsel-outline and counsel-org-goto? 

No, it does not exist. Maybe you want to discuss it on the consult wishlist (#6), then other people may also chime in there. There have been proposals for `consult-org-*` commands before, but I have not really found a use for those. I think org is fine as is and would not benefit much from additional commands. 

Therefore my current tendency is to *not* add an additional outline commands which shows the heading path. We have `consult-outline`, `consult-imenu` and `consult-project-imenu`, which should cover most use cases. Maybe `consult-project-imenu` could benefit from a generalisation, such that we could also offer `consult-org-agenda-imenu`, while reusing most of the infrastructure?

> These commands show the full heading path including parent headings (e.g. "parent/child1/child2..."). consult-imenu is somewhat similar but only shows up to depth 2 and isn't as readable (I tried customizing org-imenu-depth but that doesn't seem to change things).

If you increase `org-imenu-depth` it should work. It works for me. You may have to close and reopen the file after adjustment since `consult-imenu` caches the menu.

> Also, I've noticed consult-outline does not show the correct face/color for all results (e.g. some level 3 headings are correctly blue, others are just white). Is this a known issue? I can make another issue and try to provide a reproducible example if this is not easy to reproduce.

There could be some face-lock issue? But it is more likely that you are browsing a very large files. In that case `consult-outline` does not apply the font-locking. Please try to increase `consult-fontify-max-size`.

**Comment by noctuid** [comment]
I don't think `consult-org-*` is necessary either, at least not for me. `counsel-org-goto` is just an alias for `counsel-outline`, and although some of the `counsel-org-*` functions seem potentially useful, I've never used them. `consult-imenu` works exactly the way I want after reopening the file; the cache was the issue.

> consult-fontify-max-size

I will experiment with this. `worf-goto` doesn't have any issues with large files, but I believe it propertizes the candidates itself knowing they are org mode headings.

One thing I've noticed after replacing `worf-goto` with `consult-outline` is that `consult-outline` takes 6+ seconds to appear in many of my files after first opening them whereas `worf-goto` is instant from the first run . Does `consult-outline` do some extra work the first run?

As a side note, I was planning on creating a package called `consul` but am now dropping that name. I keep accidentally typing `counsel` as `consult`, `consult` as `consul`, etc.

**Comment by minad** [comment]
> Does consult-outline do some extra work the first run?

Fontification. The rest it is very fast. Therefore we have `consult-fontify-max-size`. But please try to obtain a profile.

> As a side note, I was planning on creating a package called consul but am now dropping that name. I keep accidentally typing counsel as consult, consult as consul, etc.

Yes, it is probably better to not use the name consul for anything if you also intend to use consult. The nice thing about the consult name is that the commands are like sentences, consult this, consult that ;)

**Comment by noctuid** [comment]
Yes, it was the fontification. Some packages I have enabled make it worse but not by much. Is it not viable to just fontify the candidate lines instead of the whole buffer? Or is there some other downside to that?
