### ISSUE TITLE
consult-imenu may jump to a wrong position when items have same names

### ISSUE THREAD

**Issue by zbelial** [minad/consult#299]
As it searches candidate using `assoc`, which returns the first item matched.

**Comment by minad** [comment]
Yes. But notably the built-in `imenu` command also cannot handle with duplicates. The problem here is that duplicates in the imenu datastructure are probably not well defined. Therefore I am not sure if we should handle them in Consult. In which realistic scenarios do you see duplicate items?

You can try the following unrealistic examples with `imenu` and `consult-imenu`:

~~~ elisp
(defun x ())
(defun x ())
(defun y ())
~~~

~~~ org
* header
* header
* header
~~~

**Comment by zbelial** [comment]
It's not unusual to see duplicate items when using programming languages that support override, such as java, cpp, etc.
Actually I found this problem when I wrote Java code.

**Comment by minad** [comment]
> It's not unusual to see duplicate items when using programming languages that support override, such as java, cpp, etc.
Actually I found this problem when I wrote Java code.

Okay, I agree that this is an important use case then if many imenu backends generate ambiguous items. (Still it would be better if these backends disambiguate the items with some signatures).
