### ISSUE TITLE
Do not define face specs inside of a defcustom

### ISSUE THREAD

**Issue by manuel-uberti** [minad/consult#3]
Hi,

first of all thanks for this package and the effort put into keeping `selectrum` as simple as possible.

One thing to consider is faces definition in `defcustom`s. See the discussion with @protesilaos here: https://gitlab.com/protesilaos/modus-themes/-/issues/123

You should check with him a possibly better approach.

**Comment by minad** [comment]
Regarding this issue: Do you propose to separate the string definition from the face definition? Since I would like to have both the prefix string customizable and the face. 

---

Regarding the modus-themes: It would be great to have support for consult in the modus-themes by @protesilaos. I am also using the themes! But I agree, that we should wait longer to have support. At first I think consult should go to melpa, but I guess it will be at least a week (more realistically a few weeks) until this thing stabilizes enough for a first release. Also the melpa review process will take time. In the next days @clemera will do another review and then I know more.

**Comment by minad** [comment]
@manuel-uberti @protesilaos please let me know if you are happy with the fix. Sometimes I am wondering about how fine grained all these face definitions should be. This is the reason why I made `consult-on/off` a single defcustom.

**Comment by manuel-uberti** [comment]
@minad Sure, don't worry, take your time and do your checks with @protesilaos. No rush. :)

**Comment by protesilaos** [comment]
Thank you @minad for looking into this (and @manuel-uberti for the feedback)!  Yes, the plan is to add support for `consult` and we shall do so once the MELPA package is available (ping me if you feel it can be done earlier).

> please let me know if you are happy with the fix. Sometimes I am wondering about how fine grained all these face definitions should be. This is the reason why I made consult-on/off a single defcustom.

Looks good to me, though I have not installed your code yet: it is on my to-do list.  The point is not to hard-wire colours.
