### ISSUE TITLE
consult-compile-error starts recursive minibuffers

### ISSUE THREAD

**Issue by astoff** [minad/consult#301]
`consult-compile-error` stopped working for me unless I enable recursive minibuffers. And even if I do, a query with prompt `Find this error in (default ...):` appears each time I highlight a different candidate.

Does that happen to you? If not I'll try to provide more specific details.

**Comment by minad** [comment]
I haven't seen this recently. The problem is that the compilation buffer has to guess somehow where the file is located. If this fails, it starts to ask the user. This is what you are observing here probably.

The problematic code which asks the user:

https://github.com/minad/consult/blob/2e5b280001e7c22204ae538234efc4a107fa423d/consult-compile.el#L72-L77

The function `compilation-find-file` is not really a good solution here. At least in the case of preview it would be better if no question is asked. The function accesses `compilation-search-path`, maybe it should be called in the context of the compilation buffer? But why do we have to pass the marker argument then.

**Comment by minad** [comment]
@astoff Did you manage to narrow this down a bit?
