### ISSUE TITLE
Mention Future History More Prominently in the README

### ISSUE THREAD

**Issue by hmelman** [minad/consult#307]
Since it seems a lot of people don't know about using future history with `M-n` and several issues have been resolved by mentioning it, I suggest mentioning it more prominently in the README.  Currently it's just mentioned once in the description of `consult-line`, I'd move it to the top section of "Available commands", something like:

> Many consult commands implement a little known but useful Emacs feature called "future history" which guesses what input the user wants.  At a command prompt type `M-n` and typically consult will insert the symbol or thing at point into the input.  It's very convenient.

**Comment by oantolin** [comment]
I sometimes wonder if a more discoverable UI would be better for the future history. For the first element of the future history I guess pre-emptively inserting it in the minibuffer, marking it and temporarily enabling `delete-selection-mode` (as requested in #306) might be a good option. Personally I find it very annoying for Consult commands because it immediately previews something I'm usually not be interested in, but for more primitive non-previewing commands it might be a good fit. But there's another problem: that only shows you the first future history element and doesn't indicate whether there are any others. Maybe a `M-n -> element1, ...` in the prompt would be better? That sounds like it would look ugly and take up too much horizontal space.

(Personally, I'm happy to exchange needing to read the manual for a more minimalistic UI.)

**Comment by hmelman** [comment]
FWIW it's just right for me.  It's guess is correct (in a variety of commands consult and otherwise) to some degree that it's merely often right (I can't quantify it, probably 50-80%).  That's often enough that I don't always want it there but want a quick way to get to it which `M-n' is.  `M-p' should be well-known and `M-n' after doing `M-p' would be as well. It's not obvious, but it's a cute hack to make `M-n' without an `M-p' do something and do something clever.

I probably would be fine with a UI that filled in the default and highlighted it so if I type, it is replaced.  That's technically the same number of keystrokes in both cases.  I agree previewing complicates things, which is why I often disable it by default.

**Comment by minad** [comment]
@oantolin 

> Personally I find it very annoying for Consult commands because it immediately previews something I'm usually not be interested in, but for more primitive non-previewing commands it might be a good fit.

I agree with that observation. But for example consult-buffer often immediately "previews" exactly the buffer you want to go to. I don't think there is a good general solution. You may want to experiment with disabling the preview if the minibuffer is empty?

**Comment by oantolin** [comment]
I'm sorry, I think I worded my earlier comment confusingly. I love automatic previews in Consult and I think the choice of what to preview initially is wel done (in particular, I agree that `consult-buffer` very often previews exactly where I want to go).

What I was trying to explain is that if you use this alternative more "discoverable" UI of automatically insert the first element of the future history at the minibuffer prompt, then Consult would preview _that_ instead, and this is what I don't like. For example, `consult-outline` normally starts by previewing the first heading, it would switch to attempting to preview the symbol at point, usually failing. For some commands like `consult-line` or `consult-buffer` it would make no difference, since for them the first candidate is also the first element of the future history (under default configurations). But when it does make a difference I think the first candidate (which is what Consult currrently does) is a better choice.

**Comment by minad** [comment]
Sorry, I am kind of slow to understand what you have in mind for this. Do you mean that you want to have a way to browse the future history without previewing the history item directly?

When I scroll through the future (or also the actual) history in Vertico, the current minibuffer input is replaced with the history string. This leads to the set of candidates being narrowed to candidates matching this history string. Furthermore it may lead to an unexpected preview.

If there would be a way to browse the future history, for example by displaying the future history candidate in an overlay, these problems would go away. Only when you press some key you commit the history string as the input into the minibuffer. 

There are more weird UI possibilities, e.g., one could open a Corfu popup showing the future history, one could extend `consult-history` to also include the future history.

**Comment by oantolin** [comment]
First of all, I am not proposing anything! I am very satisfied with both the `M-n` UI for future history and with the way Consult currently handles previews. I am a happy user of the default Consult configuration of automatic previews.

So what was I talking about, then? Well, @hmelman said that it seems that many people are unaware of future history and `M-n`. I agree that this features deserves to be better known and I was speculating about one way in which it could become better known: change the future history UI to be easily more discoverable. I would personally disable any such UI and stick with `M-n`, but I also think it might be interesting in discussing other options that other Emacs users might prefer.

I think the UI described in #306, namely, the first future history entry is automatically inserted into an active region in the minibuffer and `delete-selection-mode` is temporarily activated, might be helpful and easy to understand for new users since it is similar to what some other applications and even some web forms use. Then I discussed some downsides than particular UI: (1) it doesn't really help you discover that the future history can have more than one element, and (2) in some cases it would alter what Consult initially previews in a way that I would consider worse than the current situation.

That's all I was saying: first, future history might be made more discoverable with that UI; second, that UI doesn't solve the full discoverability problem and might be slightly annoying for some Consult users. It's just some idle speculation on future history UIs.

**Comment by oantolin** [comment]
> When I scroll through the future (or also the actual) history in Vertico, the current minibuffer input is replaced with the history string. This leads to the set of candidates being narrowed to candidates matching this history string. Furthermore it may lead to an unexpected preview.

Well, I'd say that if you are actively scrolling through history, the preview should not be unexpected.

**Comment by minad** [comment]
Thanks. I see what you mean. What would work is displaying the default/first/second future history item as an overlay, which would go away as soon as the user enters some input. This would not lead to Consult preview hiccups. But the space is limited and it is not clear to me which item or items one would like to show. Show a future history item or an actual history item? Show one or multiple? As you noted the space is limited. I am also only speculating here. Something like this would be easy to implement on the UI level (e.g. in Vertico, Selectrum, or via some small setup hook for default completion). But it is not clear to what would actually be beneficial.
