### ISSUE TITLE
`consult-line` doesn't behave as expected

### ISSUE THREAD

**Issue by felipebalbi** [minad/consult#312]
Hi,

using same example from README.org:

![image](https://user-images.githubusercontent.com/45936891/119406147-090b3d00-bceb-11eb-8d3f-c9e9c3bb0f65.png)

There are no candidates. If I start typing the entire string, however:

![image](https://user-images.githubusercontent.com/45936891/119406210-20e2c100-bceb-11eb-8fab-3b1645a5f960.png)

I get the expected candidates. Running on Emacs 27.2 on macOS

**Comment by minad** [comment]
You probably didn't configure the `completion-styles` properly. You are probably using the `basic` completion style, since you see the candidates after entering the prefix "(defun consult-". I recommend to use `orderless` as completion style. I hope this helps.

See also https://github.com/minad/consult/#bug-reports.

**Comment by felipebalbi** [comment]
Closing this issue. Turns out `orderless` is the fuzzy matching style search I was looking for
