### ISSUE TITLE
Consider using a different project source for `consult-buffer p`

### ISSUE THREAD

**Issue by Jackson-soft** [minad/consult#315]
this is my configure 
![image](https://user-images.githubusercontent.com/3928114/119648477-16900680-be54-11eb-8871-1f5d434e6d5b.png)

this is result of consult-buffer p command
![image](https://user-images.githubusercontent.com/3928114/119648558-2d365d80-be54-11eb-96ed-064015afd312.png)

this is result of project-find-file command
![image](https://user-images.githubusercontent.com/3928114/119648702-5ce56580-be54-11eb-8120-3c61037d249a.png)

**Comment by minad** [comment]
`consult-buffer p` is not equivalent to `project-find-file`. It shows the list of project files in the `recentf-list`.

**Comment by Jackson-soft** [comment]
No, no, I mean files under the same project

**Comment by Jackson-soft** [comment]
No, no, I mean files under the same project

**Comment by minad** [comment]
I don't want to add the alternative project file source right now because of performance concerns. However I renamed the existing source from `consult--source-project-file` to `consult--source-project-recent-file` to make it more clear that the current source is about recent files. This leaves the possibility to add a "proper" project file source for the future.
