### ISSUE TITLE
Windows: Process arguments must be manually escaped and encoded

### ISSUE THREAD

**Issue by oantolin** [minad/consult#317]
I managed to get `consult-find` to work in Windows, but oddly this required to escape the asterisks with backslashes:

```find . -not ( -wholename \*/.\* -prune ) -ipath \*ARG\* OPTS```

With the backslashes it does _not_ work on Linux. I don't know if you want an OS dependent default value for the variable, to mention the backslashes for Windows users in the manual, or just to have people find this issue here.

By the way, the hidden ` *consult-async*` buffer was invaluable in figuring this out, and I wish affe had something like it.

(Another pitfall on Windows is that there is a `find.exe` in `C:\WINDOWS\System32` that you want to avoid, so you need to make sure that GNU find is earlier on the path, but that pitfall I was aware of!)

**Comment by minad** [comment]
Uh why is that? On which level does windows interpret the wildcards? The escaping is not necessary on Unix since the arguments are passed directly to the process without going through the shell.

I would like to avoid platform dependent defaults. I prefer if the issue could be fixed by adding some additional escaping where necessary automatically. Any idea how one could avoid the find.exe issue?

**Comment by oantolin** [comment]
> Uh why is that? On which level does windows interpret the wildcards?

I have no idea, it makes no sense to me. Maybe on Windows `make-process` shells out because they didn't find an appropriate Windows API function? I don't know.



> I would like to avoid platform dependent defaults. I prefer if the issue could be fixed by adding some additional escaping where necessary automatically.



> Any idea how one could avoid the find.exe issue?

Well, there is a `find-program` variable in `grep.el`, which you can point to the location of your find executable. It's default value is just `"find"`, of course. I imagine Windows users that do install GNU find typically set that variable to point to it, rather than mess with paths? I've decided to try the drastic approach of putting Git's `bin/` ahead of `C:\Windows\System32` on the path, but I guess that might cause problems (so far it hasn't).

**Comment by vincentjgoh** [comment]
I mentioned this on reddit: consult-locate apparently has trouble with passing the arguments unadulterated to everything search under windows.

It's worth noting that helm isn't having this same problem; I can get the same results there as on the command line. 

Helm's command string looks like this:
`es %s -instance locate-instance -s %s`
vs consult's:
`es OPTS -instance locate-instance -s ARG`

Helm's docs say this:

> This string will be passed to format so it should end with ‘%s’.The first format spec is used for the "-i" value of locate/es,so don’t set it directly but use ‘helm-locate-case-fold-search’for this.

**Comment by minad** [comment]
There seems to be also a problem with the argument encoding (original #317).

**Comment by minad** [comment]
@Trisk3lion I don't have windows to test the issue. I would however appreciate a PR which fixes the issue properly. 

@iyefrat Are there doomed windows users you know who could help out with this one? Not sure, maybe doom explicitly does not support windows?

**Comment by iyefrat** [comment]
Doom does support windows to an extent, but It's kind of a second class citizen (admittedly I haven't really looked into the details since I don't use windows these days). I don't really know any windows users I could put on the case here, sorry.

**Comment by minad** [comment]
See also @mrc16's workaround for encoding issues: https://github.com/minad/consult/issues/475#issuecomment-994884011

**Comment by minad** [comment]
It seems that windows uses different quoting based on the type of the runtime.

https://github.com/emacs-mirror/emacs/blob/13c8cc58bbd829ca4616dea09cb050dc977db9ae/src/w32proc.c#L1903-L1910

https://github.com/emacs-mirror/emacs/blob/13c8cc58bbd829ca4616dea09cb050dc977db9ae/src/w32proc.c#L2019-L2062

I don't know what is wrong here but the issue here depends greatly on the additional programs (grep, ripgrep, find, git, ...) and the way they are compiled (cygwin, msys, msvc). This is not something we can fix or handle in Consult. It may be necessary to configure `consult-find-args`, `consult-grep-args` etc specifically according to your environment.

Wontfix.

**Comment by minad** [comment]
w32proc.c also uses CreateProcessA which is not what one should use. One should use CreateProcessW and convert before to the native 16 byte encoding understood by the windows api directly. CreateProcessW is the entrypoint in kernel32.dll. I think this leads to additional encoding issues.

https://github.com/emacs-mirror/emacs/blob/13c8cc58bbd829ca4616dea09cb050dc977db9ae/src/w32proc.c#L1352-L1353
