### ISSUE TITLE
Using 'n' or 'N' to move between searched string after consult-line

### ISSUE THREAD

**Issue by akagr** [minad/consult#318]
Hi! First of all, I'm using evil.

When I use `consult-line`, it displays a minibuffer with lines which I can then filter. All this is great. But when I hit `RET` to finish my search, it doesn't allow me to navigate to previous or next match using `n` and `N`.

If I use `consult-isearch`, it does allow that behaviour.

Additionally, I also commonly follow up finishing search with `:s%//replacement/` to quickly replace all the occurrences of the search I just made. This again works with `consult-isearch`, but not with `consult-line`.

I tried searching for existing issues related to this, but couldn't find that. Is there something I need to configure for consult or elsewhere?

**Comment by minad** [comment]
Such a feature is not provided by `consult-line`. As soon as you terminate the search via RET, it is terminated. Therefore no movement between the matches is possible. `consult-line` should be seen as a line-based in-buffer grep using the completion style you configured, e.g., orderless, but not a search command where you can move from match to match. My recommendation is to either use plain Isearch or https://github.com/astoff/isearch-mb to get the behavior you are interested in. I hope this answers your question.

**Comment by minad** [comment]
Since I have been asked for a similar feature on https://github.com/minad/vertico/issues/82, I wonder about this feature again and tried different things:

~~~ elisp
;; Allow to search after closing consult-line with M-n/M-p.
(global-set-key (kbd "M-n") (lambda () (interactive) (search-forward (car consult--line-history))))
(global-set-key (kbd "M-p") (lambda () (interactive) (search-backward (car consult--line-history))))
~~~

**Comment by noctuid** [comment]
I'm using this:
```elisp
(defun noct-consult-line-evil-history (&rest _)
  "Add latest `consult-line' search pattern to the evil search history ring.
This only works with orderless and for the first component of the search."
  (when (and (bound-and-true-p evil-mode)
             (eq evil-search-module 'evil-search))
    (let ((pattern (car (orderless-pattern-compiler (car consult--line-history)))))
      (add-to-history 'evil-ex-search-history pattern)
      (setq evil-ex-search-pattern (list pattern t t))
      (setq evil-ex-search-direction 'forward)
      (when evil-ex-search-persistent-highlight
        (evil-ex-search-activate-highlight evil-ex-search-pattern)))))

(advice-add #'consult-line :after #'noct-consult-line-evil-history)
```
This seems to be good enough for me since I often only use one component for `consult-line` (or the first component is at least good enough for later cycling through matches with evil).

**Comment by skyler544** [comment]
In the hope of helping anyone else who wants this, if you've installed `evil` via `use-package`, all it takes to get this functionality to play nice with `n` and `N` is to take this snippet:

> ```emacs-lisp
> ;; Allow to search after closing consult-line with M-n/M-p.
> (global-set-key (kbd "M-n") (lambda () (interactive) (search-forward (car consult--line-history))))
> (global-set-key (kbd "M-p") (lambda () (interactive) (search-backward (car consult--line-history))))
> ```

and slightly modify it so that it uses `define-key` instead:
``emacs-lisp
(use-package evil
  :init
  ...
  :config
  ...
 (define-key evil-normal-state-map (kbd "n")
    (lambda () (interactive) (search-forward (car consult--line-history))))
  (define-key evil-normal-state-map (kbd "N")
    (lambda () (interactive) (search-backward (car consult--line-history))))
  ...)
```

**Comment by noctuid** [comment]
Keep in mind that will only work if you never use anything but `consult-line` for searching though. It also won't correctly support using `n` as a motion with an operator.
