### ISSUE TITLE
Don't select already visible buffers as default in consult-buffer

### ISSUE THREAD

**Issue by tsdh** [minad/consult#320]
I usually have a single fullscreen emacs frame with two (or three) side-by-side windows showing some buffers A and B.  I frequently switch between those using `other-window`.  Now when I invoke `consult-buffer` in the window showing buffer A, it'll show buffer B as default completion candidate which is useless most of the time since that buffer is already shown in the other window.  (Of course, there are situations where you want to have 2 windows showing the same buffer but at least for me, that doesn't happen too often.)

I'd wish there was a way to tell consult to sort buffers by last-recently-used-time (as it seems to do) but push buffers which are already shown in a window of the current frame to the end of the list.

**Comment by minad** [comment]
Currently only the current buffer is pushed to the end of the list. Your proposal sounds like a reasonable enhancement over the status quo:

1. other buffers
2. visible buffers
3. current buffer

I think it is even reasonable enough to make it the default without an option. In order to revert to the old behavior, the buffer source can be modified.

Other opinions? Thoughts?

**Comment by tsdh** [comment]
Your suggestion sounds great to me. With respect to if an option is needed, I'm not sure. Other people use frames more than I do, and maybe they'd also want to consider a buffer visible if it's in a window of another frame. But if course there is no need for upfront customizability, so it's ok to just wait and see if somebody will request that in the future.

**Comment by tsdh** [comment]
Works nice, thank you!
