### ISSUE TITLE
Unsatisfactory performance of search commands

### ISSUE THREAD

**Issue by Jackson-soft** [minad/consult#325]
The current consult-ripgrep and consult-find performance is not as good as affe-grep and affe-find, whether to consider deleting these two commands or using the results of affe.el

**Comment by minad** [comment]
This is not a constructive criticism. I need concrete benchmarks or improvement proposals. Affe uses a different underlying mechanism, which is not a good fit for Consult itself. Affe works well for small projects but it will be slower than consult-ripgrep for larger projects, since Affe filters *all lines*.

Why not use Affe if you like it more? You may also want to set `consult-async-split-style=space` which will give you a more Affe-like experience for `consult-ripgrep`.

Closing.
