### ISSUE TITLE
Add '-other-window' and '-other-frame' variants for 'consult-recent-file`

### ISSUE THREAD

**Issue by woolsweater** [minad/consult#326]
Analogous to `consult-buffer`'s `consult-buffer-other-{window,frame}` counterparts, I'd like to request the addition of `consult-recent-file-other-window` and `consult-recent-file-other-frame` commands.

(I posted this in #6, the Command Wishlist, but it immediately got buried by another conversation; I hope posting it here as well is okay.)

**Comment by minad** [comment]
Instead of adding dedicated commands my approach is to use `embark-act` and the `find-file-other-window` action on a recent file. This way one avoids a dedicated keybinding for the `consult-recent-file-*` variants. The `consult-buffer-*` variants exist since `consult-buffer-*` aims to replace `switch-to-buffer-*`.

**Comment by woolsweater** [comment]
Okay, fair enough. I can write my own command as well. Thank you!
