### ISSUE TITLE
How to change sources in consult-buffer?

### ISSUE THREAD

**Issue by Crandel** [minad/consult#337]
I used `Helm` last 3-4 years, but some time ago I realize I use only a few commands on daily basis. So I found a `Consult`+`Selectrum` as lightweight replacement of `Helm`.

I used to `helm-multi-files` command which has almost the same output as `consult-buffer`. I changed sources using `[C-right]`, `[C-left]` bindings. If I press `[C-right]` the top source changed from `buffer list` to `recent-file list`, next press changes top source to `bookmark list`, etc. 

If I press [C-left] top source is `recent-file list` again.

Can I configure the same behavior for `Consult`(Selectrum)?

**Comment by minad** [comment]
Another option would be to implement it on the level of the completion UI - adding commands there which reorder the groups. The grouping feature is a bit more general than Consult, it is implemented even in Emacs 28. The advantage of implementing the feature in the completion UI directly would allow to work with all commands supporting groups, not only `consult-buffer`.

**Comment by minad** [comment]
I transferred the issue to https://github.com/minad/vertico/issues/63, since I think this issue should be solved on the level of the completion UI. The same cycling solution can be used by both Selectrum and Vertico.

**Comment by Crandel** [comment]
Thank you for quick answer. Will wait for solution.

**Comment by minad** [comment]
There is one more feature I wanted to make you aware of - [Consult Narrowing](https://github.com/minad/consult/#narrowing-and-grouping). This allows you to quickly narrow down to a source. For example if you have set `consult-narrow-key` to `<`, you can press `<f`, `<m`, `<b` to restrict to **f**iles, book**m**arks or **b**uffers only. To unrestrict you can press `<<`. Imo this feature is better than the cycling feature of helm since it allows you to go directly to the desired source. Of course this means adjusting your muscle memory in contrast to the Helm cycling ;)

I looked into how cycling could be implemented in Vertico and thought about this a bit more. And I have my doubts if it should be added because of the narrowing I just described, because of the additional complexity and also because we already have `vertico-next/previous-group` which allows you to jump between the groups in a way which is familiar from the paragraph navigation in normal buffers. I am not so sure I want to add multiple features which overlap a lot.

**Comment by Crandel** [comment]
Yes, I played a little bit with narrowing, like [this](https://github.com/Crandel/home/blob/master/.config/emacs/recipes/consult-rcp.el#L38), but for bookmarks I need additional keybinding. Cycle using narrowing could be also an option.

**Comment by minad** [comment]
What about using something like this?

~~~ elisp
(define-key minibuffer-local-map [C-left] #'consult-narrow-left)
(define-key minibuffer-local-map [C-right] #'consult-narrow-right)

(defun consult-narrow-left ()
  (interactive)
  (when consult--narrow-keys
    (consult-narrow
     (if consult--narrow
         (let ((idx (seq-position consult--narrow-keys
                                  (assq consult--narrow consult--narrow-keys))))
           (unless (eq idx 0)
             (car (nth (1- idx) consult--narrow-keys))))
       (caar (last consult--narrow-keys))))))

(defun consult-narrow-right ()
  (interactive)
  (when consult--narrow-keys
    (consult-narrow
     (if consult--narrow
         (let ((idx (seq-position consult--narrow-keys
                                  (assq consult--narrow consult--narrow-keys))))
           (unless (eq idx (1- (length consult--narrow-keys)))
             (car (nth (1+ idx) consult--narrow-keys))))
       (caar consult--narrow-keys)))))
~~~

**Comment by Crandel** [comment]
Perfect. Probably I will try Vertico instead of Selectrum too

**Comment by minad** [comment]
There is also https://github.com/minad/vertico/pull/64, you can give this a try.

**Comment by Crandel** [comment]
Thank you @minad !
