### ISSUE TITLE
consult-completion-in-region lsp-mode filter

### ISSUE THREAD

**Issue by tpeacock19** [minad/consult#346]
I was following this issue in https://github.com/minad/vertico/issues/61 and have updated consult to the latest version. However, when I use completion at point the candidates do not filter as expected. It will only move candidates if case-sensitively matching exactly. I've reproduced this with the following:

`emacs -Q -l test-init.el`

```emacs-lisp
;;; test-init.el --- description -*- lexical-binding: t; -*-

(setq user-emacs-directory "~/.config/emacs/")

(setq straight-repository-branch "develop"
      straight-enable-package-integration t
      straight-use-package-by-default t)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))

  (unless (catch 'emacs-version-changed
            (load bootstrap-file nil 'nomessage))
    (when (boundp 'comp-eln-load-path)
      ;; remove leftovers, with confirmation just to be safe
      (when (yes-or-no-p (format "Delete '%s'?" (car comp-eln-load-path)))
        (delete-directory (expand-file-name (car comp-eln-load-path)) t))
      ;; and try again
      (load bootstrap-file nil 'nomessage))))

(straight-use-package 'use-package)
(use-package consult)
(use-package vertico)
(use-package lsp-mode)
(use-package python-mode)
(use-package lsp-pyright)

(setq completion-in-region-function #'consult-completion-in-region)
(vertico-mode)

(find-file "~/temp/test.py")
(python-mode)
(require 'lsp-pyright)
(lsp-deferred)

(provide 'test-init)
```

test.py

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from sys

sys.[[C-M-i Here]]
```

**Comment by minad** [comment]
Try to set completion-ignore-case and possibly adjust the completion-styles?

**Comment by tpeacock19** [comment]
I don't think I'm being clear with the issue. Below is what I see when using vertico-mode & consult-completion-in-region:

![2021-06-29T16:44:12,704505809-07:00](https://user-images.githubusercontent.com/6407145/123881692-cb768100-d934-11eb-99ae-749c8aaf9f30.png)

And this is what I see when using selectrum-mode and its specific completion-in-region function:

![2021-06-29T16:48:41,122851459-07:00](https://user-images.githubusercontent.com/6407145/123881718-dcbf8d80-d934-11eb-988d-45ffff8252c3.png)

This was done with `completion-ignore-case = t` and the default completion style.

**Comment by minad** [comment]
You should adjust the completion-styles such that it does not include basic. Then it should work. Try flex or orderless. The lsp-mode completion table does not follow the specification correctly.

https://github.com/emacs-lsp/lsp-mode/blob/fc30baf3d66b9b5c695e851f7e54af926a453c12/lsp-completion.el#L504

**Comment by minad** [comment]
It seems lsp-mode never had a conforming completion table. The current one got introduced in https://github.com/emacs-lsp/lsp-mode/pull/1693. Before that the completion table was even less compliant.

The problem is that the table does not perform prefix filtering such that the basic completion style is effectively a no-op and does not perform filtering at all. 

We should create an issue in lsp-mode about this. Lsp-mode should provide a fully confirming completion table and then supply an additional completion style which does not make use of prefix filtering if it is undesired.

**Comment by minad** [comment]
As a current work around: In consult-completion-in-region at the point where completing-read is called, completion-styles should be set to (substring), (orderless), or (flex). Furthermore completion-category-defaults and completion-category-overrides should not include an entry for lsp-capf.

**Comment by minad** [comment]
Copying part of my comment from emacs-lsp/lsp-mode#2970 here:

> Unfortunately there will still be issues with this approach, in particular in
combination with consult-completion-in-region. The lsp server may only return
a small subset of items, which fit at point. By transferring the completion to
the minibuffer, the further user input in the minibuffer is not taken into
account by the lsp server. The input will only be used for the secondary
filtering. Ultimately I think consult-completion-in-region is not a good fit
for lsp due to the transfer to the minibuffer. Instead completion in region in
the actual buffer should be used (Company or my Corfu package).

My recommendation is to use Corfu/Company in combination with Lsp-mode or Eglot. `consult-completion-in-region` is fundamentally unable to work correctly with lsp-mode. We can still do a bit better than the status quo, as outlined in emacs-lsp/lsp-mode#2970. But even then `consult-completion-in-region` will be worse than Corfu/Company. One could consider adding special completion support to [consult-lsp](https://github.com/gagbo/consult-lsp), which provides specialized lsp completion in the minibuffer. It could even make use of the consult async functionality.

**Comment by tpeacock19** [comment]
Thanks for looking into this, I appreciate your patience.

> Work around for now: In consult-completion-in-region at the point where completing-read is called, completion-styles should be set to (substring), (orderless), or (flex).

I'm not sure if you still suggest this, but I ran into this problem with my custom emacs config initially. I do make use of orderless as my completion-style so I do not believe this would solve the issue.

> My recommendation is to use Corfu/Company in combination with Lsp-mode or Eglot. consult-completion-in-region is fundamentally unable to work correctly with lsp-mode.

This makes sense and I have been bouncing between corfu & company determining which I like better. However, I've run into perhaps a similar filtering issue in corfu which only seems to show case-sensitive matches. I can create this issue in the corfu repo if you like.

**Comment by minad** [comment]
The best would be to wait until https://github.com/emacs-lsp/lsp-mode/issues/2970 is sorted out.

**Comment by tpeacock19** [comment]
okay will do, thanks.

**Comment by minad** [comment]
> I'm not sure if you still suggest this, but I ran into this problem with my custom emacs config initially. I do make use of orderless as my completion-style so I do not believe this would solve the issue.

Did you try `substring` in the emacs -Q configuration from above?

**Comment by tpeacock19** [comment]
Ah yes, substring and flex actually do work, both with corfu and minibuffer completion. As long as its activated after lsp-mode.  Unfortunately, and i guess obviously, this prevents the use of orderless matching.

**Comment by minad** [comment]
No, orderless should work too.

~~~ elisp
(setq-local completion-styles '(orderless)
            completion-category-overrides nil
            completion-category-defaults nil)
~~~

The only completion style which won't work is `basic` but this will be sorted out as soon as https://github.com/emacs-lsp/lsp-mode/issues/2970 is fixed.

**Comment by minad** [comment]
But I think I understand what you mean - Orderless with space-separated filter strings will work with `consult-completion-in-region`+Vertico. But it will not work in the buffer, since the lsp server will refuse to return strings for the space-separated input string, e.g., if you enter `sys. TAB exec SPC base`

**Comment by tpeacock19** [comment]
I get the following case-sensitive issue when using orderless with corfu or consult-completion-in-region:

![2021-06-30T11:56:47,563181095-07:00](https://user-images.githubusercontent.com/6407145/124016317-0c25d700-d9d5-11eb-82cd-874907a791bc.png)


![2021-06-30T11:57:21,348239135-07:00](https://user-images.githubusercontent.com/6407145/124016342-12b44e80-d9d5-11eb-89b7-702ea371f006.png)

I do have `completion-ignore-case=t` and `orderless-smart-case=t`

**Comment by minad** [comment]
No idea what is going on here. We should wait for https://github.com/emacs-lsp/lsp-mode/issues/2970. For now I recommend `substring` completion with lsp.

**Comment by tpeacock19** [comment]
I don't know if its of any value, but the same settings, with `completion-styles=orderless` works with both `selectrum-mode` & `company-mode`. But I imagine that it is the specification problem mentioned in the other issue.

**Comment by minad** [comment]
Selectrum implements completion differently (and does not follow the specification precisely), I expected that this works accidentally. I am not very familiar with Company, since it is pretty complicated. In that case it works since the lsp guys mostly test with Company. 

With Company+Orderless did you use

~~~ elisp
;; after activating lsp-mode, execute with M-: in the python buffer
(setq-local completion-styles '(orderless)
            completion-category-overrides nil
            completion-category-defaults nil)
~~~

or did you use

~~~ elisp
(setq completion-styles '(orderless))
~~~

without ensuring that the overrides are reset? If you did not reset the overrides the lsp hack will be effective and Orderless won't be used.

**Comment by tpeacock19** [comment]
I used:

```elisp
;; after activating lsp-mode, execute with M-: in the python buffer
(setq-local completion-styles '(orderless)
            completion-category-overrides nil
            completion-category-defaults nil)
```

with all combinations, company+orderless, corfu+orderless, selectrum+orderless, vertico+orderless.

**Comment by davidselassie** [comment]
Did y'all discover if https://github.com/emacs-lsp/lsp-mode/issues/2970 fixed this issue? I'm having the exact same issue combining orderless with consult-complete-in-region but with eglot instead of lsp-mode, so I'm wondering if there's a fix to be made in eglot.

My goal is to request completions from the LSP server and then filter that static list of completions using orderless. I understand that candidate list retrieved from the LSP server will not be updated until the buffer itself is modified.
