### ISSUE TITLE
consult-fd as a separate command

### ISSUE THREAD

**Issue by grolongo** [minad/consult#363]
This is not a bug.

I came across a few closed issues mentioning the use of `consult-find/locate/fd` but couldn't see why `consult-fd` never became it's own command.

I'm setting `consult-find-command` to use `fd` without problem but was wondering if we could have a separate `consult-fd` just like we have `consult-grep` and `consult-ripgrep`.

As an usage example, one could configure `consult-find` to only search non-recursively with the `-maxdepth 1` option and use the speed of `consult-fd` for recursive search with hidden files included.

This seems to do the work for me:

```elisp
(defcustom consult-fd-command
  "fd --color=never ARG OPTS"
  "Command line string for fd, see `consult-fd'.
The command string must have a specific format, including ARG and OPTS
substrings. ARG is replaced by the filter string and OPTS by the auxillary
command options."
  :type 'string)

(defun consult-fd (&optional dir initial)
  "Search for regexp with fd in DIR with INITIAL input.
The find process is started asynchronously, similar to `consult-grep'.
See `consult-grep' for more details regarding the asynchronous search."
  (interactive "P")
  (let* ((prompt-dir (consult--directory-prompt "Find" dir))
         (default-directory (cdr prompt-dir)))
    (find-file (consult--find (car prompt-dir) consult-fd-command initial))))
```

**Comment by minad** [comment]
I don't think the addition of `consult-fd` is justified, see https://github.com/minad/consult/issues/156#issuecomment-758578134. You can trivially write this command yourself, see https://github.com/minad/consult/wiki#find-files-using-fd.

**Comment by grolongo** [comment]
Fair enough, thank you for the justification.

**Comment by minad** [comment]
Copying my comment https://github.com/minad/consult/issues/156#issuecomment-758578134:

-----

fdfind in contrast is not as justified for me, for some subjective reasons:

* It has a bad name which already prevents me from just offering it as is. fd means also floppy disk and file descriptor. For this reason it is not available on some linux distributions under the fd name. This means we already need some configuration for fd.
* It has certain quirks. When given the full-path option, it should search for the regexp in the full-path. This means when I am in directory /home/user and search for user it will find all files. I would want it to search only the path below the root directory.
* I find it weird that it uses regular expressions in contrast to wildcards, even if regular expressions are better. In our context regular expressions are also better, since you can just type #org# to find all org files. But somehow due to all these quirks, fd did not (yet) manage to become a drop-in replacement for find in my use cases.

But given all these arguments - if there wouldn't be the name problem I would have included fdfind here.

**Comment by minad** [comment]
I looked into `fd` again due to my recent changes to the command infrastructure (#380). It would be beneficial to use a find command which has full regexp support. But as far as I understand `fd` is too weak for what I need.

1. The matching problem against full-path should be fixed. I think someone told me how to do this, but unfortunately I forgot the solution.
2. `fd` does not support matching against multiple patterns combined with AND. Since it uses the rust regexp engine instead of pcre it does not support look-ahead patterns `^(?=.*first)(?=.*second)` and it also does not have a `--and` command line option.

**Comment by grolongo** [comment]
> It would be beneficial to use a find command which has full regexp support.

Do you mean something like `consult-find-regexp` (while consult-find uses globbing as default), that would do as an example:
`find . -regextype emacs -regex "foo"` ?

I agree with you GNU find has the most capabilities. For my case I wasn't using `fd` for regexp, I mainly used it with `--glob` anyway. Using `find` from `/` and sometimes `/Users/grolongo` on macOS outputs a lot of errors (Permission denied / Operation not permitted), while `fd` just works very quickly.

**Comment by minad** [comment]
> Do you mean something like consult-find-regexp (while consult-find uses globbing as default), that would do as an example:
find . -regextype emacs -regex "foo" ?

Yes. My recent update changes `consult-find` to also use regular expressions. We also get highlighting and orderless patterns now. See https://github.com/minad/consult/pull/380.

**Comment by minad** [comment]
I've added `consult-fd` in 5960ad787d8d1051d9c3140219d021496731e14c.

**Comment by grolongo** [comment]
Hi minad,  
I took a look at `consult-fd-args`. Is the `executable-find` function inside the if statement running each time someone uses consult-fd?  
If so, shouldn't we use something like below, so it's executed once and for all when the package is loaded?
```elisp
(defvar fd-exec "fd")
(when (executable-find "fdfind")
  (setq fd-exec "fdfind"))
(setopt consult-fd-args (format "%s --full-path --color=never" fd-exec))
```

**Comment by minad** [comment]
See https://github.com/minad/consult/commit/5f78ab04a2a2c6387f0fe29bc309399ea815346a. That's why we have to call `executable-find` once per `consult-fd` invocation.

**Comment by grolongo** [comment]
understood, thank you.
