### ISSUE TITLE
Idea: if in an isearch, use the search string as default consult search

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#364]
One nice feature of `occur` (`M-s o`) is that you can _convert_ a search into an occur _while the search is ongoing_.  This would be a great addition for consult as well.  E.g. `C-s sometext` then `M-s l` for `consult-line`.

**Comment by minad** [comment]
Exists already, see consult-isearch bound in the isearch keymap in the example configuration.

**Comment by oantolin** [comment]
Is that right @minad? I thought `consult-isearch` did something different: I thought it was a way to start a new isearch (or change the search string of the current isearch), prompting you for a previous search string with completion from the isearch search string history.

What this issue is asking is for a way to switch from isearch to consult-line with the isearch search string as the initial input. Like this:

```elisp
(defun consult-line-from-isearch ()
  "Run `consult-line' with current isearch string."
  (interactive)
  (consult-line isearch-string))
```

**Comment by minad** [comment]
@oantolin I meant consult-line, not consult-isearch.

**Comment by oantolin** [comment]
Very cool! I had somehow missed this:

> When consult-line is bound to the isearch-mode-map and is invoked during a running Isearch, it will use the current Isearch string.

**Comment by minad** [comment]
I forgot where I got this from, maybe @astoff, who contributed `consult-isearch`. The feature hasn't been there from the beginning and got added after someone proposed this exact functionality.

**Comment by jdtsmith** [comment]
It's very nice in operation.  Allows one to get into consult-line starting from a search, or using embark.  I bet consult-outline would enjoy the same treatment.

**Comment by minad** [comment]
@jdtsmith One could also add this to outline, but maybe the functionality would be underwhelming there, since the isearch may not lead to matches if one considers only the outline.
