### ISSUE TITLE
New package consult-switch, need feedback

### ISSUE THREAD

**Issue by karthink** [minad/consult#373]
In preparation for consult-reftex, which is coming along beautifully, I wrote a small package using consult to fix a longstanding annoyance I've had with Emacs that I couldn't fix even with Embark. What it does is give the user an easy way to switch the directory when finding files. Unless I've missed something obvious, there's no way of jumping to directories inside find-file-like commands in Emacs.

Here is a demo, you can read the mode-line (keycast) to see the commands being called:

https://user-images.githubusercontent.com/8607532/127601701-c4cf89d3-fc3e-4d98-8a97-90dc61c35a99.mp4

There are two main commands provided by this package: 

1. `consult-insert-user-directory`: When the minibuffer is active, pick and insert a directory from your sources (in my case bookmarks that are directories, projects and the default-directory). Whether the old file name is shadowed or removed is covered by a defcustom. The `-maybe` in the command I'm invoking is because of a wrapper I wrote for my configuration that only calls it when the completion category is file.
2. `find-file-in-directory`: Alternative to `find-file`. When not in the minibuffer, call this to pick a directory from the sources and find-file in there.

Additionally, there's a `consult-jump-from-this-dir` that will run `consult-find` on the input in the directory that is currently in the minibuffer contents. That sounds convoluted but the demo shows how it works pretty well. This is not the same as calling `embark-become` on `find-file` -> `consult-find` since this runs `consult-find` on the default directory instead, which is never what I want. 

- I'm calling it `consult-switch`. This name is neat, but I want to avoid clashing with any plans you might have for the `consult-switch-` namespace. If you have a better name for this do let me know. I do need better names for these commands, I'll fix the prefix when renaming commands before I submit to MELPA.
- I'm reasonably sure this switching feature can be handled more simply with Embark but I don't know how. If it turns out to be trivial, I can just scrap this whole thing.
- I'm planning to add a few more convenience directory-jump type functions. If you have any ideas, such as for more sources (recently visited directories?), I'd like to know.

Any other feedback you might have about the code is appreciated as well. The code is [here](https://github.com/karthink/consult-switch).

----
EDIT: `consult-insert-user-directory` is useful for all 'file category commands where you may need a directory, not just find-file. For example, calling `C-u M-x consult-find`, then `consult-insert-user-directory` lets me quickly select a directory where I want to search for files. I should probably add `(project-root (project-current))` as another source in the list of sources for `consult-insert-user-directory` along with the default-directory.

**Comment by oantolin** [comment]
This looks very nice! And I know how useful `consult-insert-user-directory` is since I have a baby [version of it in my configuration](consult-insert-user-directory), and use it all the time. My version only uses bookmarks that are directories, so a consult-style multiple-source version sounds pretty cool!

**Comment by karthink** [comment]
Added a recentf-dirs source:

![2021-07-30-002201_776x512_scrot](https://user-images.githubusercontent.com/8607532/127616484-e197dfd1-ee54-4bc7-9f3a-254faa6408a1.png)

I probably need to start caching these sources for speed but I haven't figured out how to use `consul--define-cache` yet.

**Comment by minad** [comment]
> In preparation for consult-reftex, which is coming along beautifully, I wrote a small package using consult to fix a longstanding annoyance I've had with Emacs that I couldn't fix even with Embark. What it does is give the user an easy way to switch the directory when finding files. Unless I've missed something obvious, there's no way of jumping to directories inside find-file-like commands in Emacs.

That's great to hear. I am looking forward to more packages which fit this ecosystem. As Omar already confirmed, there is no easy way to jump to directories in `find-file` and so far Consult is also lacking such functionality. I think we discussed about a directory jumping feature at some point, but your package goes further than what we discussed.

>     1. `consult-insert-user-directory`: When the minibuffer is active, pick and insert a directory from your sources (in my case bookmarks that are directories, projects and the default-directory). Whether the old file name is shadowed or removed is covered by a defcustom. The `-maybe` in the command I'm invoking is because of a wrapper I wrote for my configuration that only calls it when the completion category is file.
>
>     2. `find-file-in-directory`: Alternative to `find-file`. When not in the minibuffer, call this to pick a directory from the sources and find-file in there.
>
> Additionally, there's a `consult-jump-from-this-dir` that will run `consult-find` on the input in the directory that is currently in the minibuffer contents. That sounds convoluted but the demo shows how it works pretty well. This is not the same as calling `embark-become` on `find-file` -> `consult-find` since this runs `consult-find` on the default directory instead, which is never what I want.

All these commands make sense as I see it. Omar, do you see a possibility to cover any of these commands easily with Embark? Not really related to what you are doing here, but the Doom Emacs guys (who recently adopted Consult/Embark/Orderless/Vertico) missed a `counsel-jump-file` equivalent.

>     * I'm calling it `consult-switch`. This name is neat, but I want to avoid clashing with any plans you might have for the `consult-switch-` namespace. If you have a better name for this do let me know. I do need better names for these commands, I'll fix the prefix when renaming commands before I submit to MELPA.

Thank you for asking about this. I don't have plans for this namespace, feel free to use it. But my initial reaction was that maybe a less generic name would be better for your package. `consult-jump` is as generic but seems to fit better than `consult-switch`. What about `consult-dirjump`?

>     * I'm reasonably sure this switching feature can be handled more simply with Embark but I don't know how. If it turns out to be trivial, I can just scrap this whole thing.

I am not sure. And since Omar still has his bookmark directory jumper, there is probably a need for such a feature. Maybe one should also reconsider adding some new commands to Consult itself which fill the gap. Generally I am hesitant to stuff much more functionality into Consult itself, but a directory selection command does not sound unreasonable. I think the last time this came up we didn't go through with adding something, because using bookmarks for this purpose seemed a bit ad-hoc. But maybe Omar never really proposed adding it? Another alternative could be to just Consult the recent file list and take all paths from there to make up a directory selector. But then you will probably miss the multi source functionality. So far Consult itself only has buffer multi sources. For now I had intended to keep it this way and not add more multi-source commands. Instead my recommendation for users is to create their own commands with multi sources, adapted to their specific use cases. This is very your package fits in as a useful addition to the main Consult package.

Unrelated - but I've seen that you show the narrowing characters in the group titles. I've also considered this before but I always wondered if I would find it too noisy after having used a command for a while. Maybe I should add this nevertheless and guard it behind a flag `consult-group-title-narrow-key`. What do you think? I have to figure out if there is an easy generic way to do this. For historical reasons the narrowing and grouping functionality (while being very similar and overlapping superficially) is pretty much unrelated in their implementation.

> I probably need to start caching these sources for speed but I haven't figured out how to use consult--define-cache yet.

I recently removed `consult--define-cache` in favor of a much more useful (and efficient) `consult--buffer-query` function which allows you to query the lists of buffers. Of course this won't help your use case. Originally I introduced `consult--define-cache` since I wanted to avoid some recomputations in multi buffer sources recreating various buffer lists all the time. But the convoluted functionality was not worth it and `consult--buffer-query` is fast enough. For your use case, caching shouldn't be necessary. Generally try to keep the usage of internals as low as possible. I would very much appreciate this since otherwise such usage of internals constrains the development of Consult severly (I usually go through the exisiting consult-x packages to see if I would introduce breakage if I change internals).

**Comment by karthink** [comment]
> That's great to hear. I am looking forward to more packages which fit this ecosystem. As Omar already confirmed, there is no easy way to jump to directories in `find-file` and so far Consult is also lacking such functionality. I think we discussed about a directory jumping feature at some point, but your package goes further than what we discussed.

Good to know I'm not duplicating effort.

> All these commands make sense as I see it. Omar, do you see a possibility to cover any of these commands easily with Embark? Not really related to what you are doing here, but the Doom Emacs guys (who recently adopted Consult/Embark/Orderless/Vertico) missed a `counsel-jump-file` equivalent.

`consult-switch-find-from-dir` is essentially `counsel-jump-file`. I think it can be better than `counsel-jump-file` with judicious application of the prefix argument, I'll think about how to do that.

> Thank you for asking about this. I don't have plans for this namespace, feel free to use it. But my initial reaction was that maybe a less generic name would be better for your package. `consult-jump` is as generic but seems to fit better than `consult-switch`. What about `consult-dirjump`?

Yeah, `consult-switch` is too generic. `consult-dirjump` sounds good, the main command it provides can be called `consult-dirjump` too, that makes the function obvious. The `counsel-jump-file` equivalent will end up being called `consult-dirjump-jump-file` or something though, and that doesn't quite fit. Also I can't use `find-file-in-directory` which is a short, good descriptive name because of the package name prefix requirement. `consult-dirjump-find-file` isn't as easy to remember. (Also, "C-x C-d" which is `list-directory` by default, is a great binding for this command!)

How about `consult-dir`? It's on the generic side and possibly a valuable namespace, but the commands will be `consult-dir-jump`, `consult-dir-jump-file` (the file jump command) and `consult-dir-find-file` (the find-file-in-directory command), all of which fit.

> I am not sure. And since Omar still has his bookmark directory jumper, there is probably a need for such a feature. Maybe one should also reconsider adding some new commands to Consult itself which fill the gap. Generally I am hesitant to stuff much more functionality into Consult itself, but a directory selection command does not sound unreasonable.

If you're interested in adding this to Consult, I can submit a PR. I'm okay with it living in a separate package though, I like the modularity of this ecosystem. Consult is pretty large as it stands.

>  I think the last time this came up we didn't go through with adding something, because using bookmarks for this purpose seemed a bit ad-hoc. Another alternative could be to just Consult the recent file list and take all paths from there to make up a directory selector.

A `recentf-dirs` source is part of `consult-switch`, as my above post (with images) shows. The user can always disable the `bookmark-dirs` source if it's not a good fit, or I can disable it by default. (I personally find it quite useful.)

>  But then you will probably miss the multi source functionality. So far Consult itself only has buffer multi sources. For now I had intended to keep it this way and not add more multi-source commands. Instead my recommendation for users is to create their own commands with multi sources, adapted to their specific use cases. This is very your package fits in as a useful addition to the main Consult package.

That makes sense.

> Unrelated - but I've seen that you show the narrowing characters in the group titles. I've also considered this before but I always wondered if I would find it too noisy after having used a command for a while. Maybe I should add this nevertheless and guard it behind a flag `consult-group-title-narrow-key`. What do you think? I have to figure out if there is an easy generic way to do this. For historical reasons the narrowing and grouping functionality (while being very similar and overlapping superficially) is pretty much unrelated in their implementation.

Narrowing is not a discoverable feature (unlike the groups), and it's unlikely that many users will go through the README carefully. Like Doom users who don't know or care what completion system they're using, for example. But having the hints in the group titles does look noisy to me, I have to actively resist the urge to remove it every time I use it. Maybe there's a less noisy solution, like showing the narrow key in the prompt instead? "Switch to (<): "?

> I recently removed `consult--define-cache` in favor of a much more useful (and efficient) `consult--buffer-query` function which allows you to query the lists of buffers. Of course this won't help your use case. Originally I introduced `consult--define-cache` since I wanted to avoid some recomputations in multi buffer sources recreating various buffer lists all the time. But the convoluted functionality was not worth it and `consult--buffer-query` is fast enough. For your use case, caching shouldn't be necessary.

- Project source: `project--list` is a variable maintained by Emacs, and I use it with very little transformation. No caching needed.
- Bookmark source: I have to filter `bookmark-alist` to directory bookmarks every time. If a user has >100 bookmarks, I don't know if performance will be impacted.
- Recentf source: Multiple transformations on `recentf-list` needed. Basically `recentf-list` -> `file-name-directory` -> `delete-dups` -> `abbreviate-file-name` -> filter to remove entries that are already in the other sources. I'm using `consult--define-cache` for this one, I don't have a good sense of whether this is necessary.

> Generally try to keep the usage of internals as low as possible. I would very much appreciate this since otherwise such usage of internals constrains the development of Consult severly

I'll keep this in mind. So far the internals I've used are `consult-project-root-function`, `consult--project-root`, `consult--define-cache` and `consult--string-hash`, plus a couple of `consult-*-face`s. I don't plan to use any other internals, and will try to find an alternative to the cache functionality.

**Comment by karthink** [comment]
I should probably also make the project support independent of the backend -- right now it won't work with projectile (even though I use `consult-project-root-function` etc, because I explicitly use `project--list` in a couple of places. I was planning to try to make this project backend-agnostic using Consult as the project interface, but might have to add explicit support for projectile...

**Comment by minad** [comment]
> `consult-switch-find-from-dir` is essentially `counsel-jump-file`. I think it can be better than `counsel-jump-file` with judicious application of the prefix argument, I'll think about how to do that.

Seems different to me. The `+vertico-jump-file` which the Doom guys added, just finds all the files in the directories for completion. Very similar to my `affe-find`, but synchronous.

> How about `consult-dir`? Package description: "Navigate to directories faster with Consult". It's on the generic side and possibly a valuable namespace, but the commands will be `consult-dir-jump`, `consult-dir-jump-file` (the file jump command) and `consult-dir-find-file` (the find-file-in-directory command), all of which fit.

I also find `consult-dir` a bit too generic, but make your choice!

> > I am not sure. And since Omar still has his bookmark directory jumper, there is probably a need for such a feature. Maybe one should also reconsider adding some new commands to Consult itself which fill the gap. Generally I am hesitant to stuff much more functionality into Consult itself, but a directory selection command does not sound unreasonable.
>
> If you're interested in adding this to Consult, I can submit a PR. I'm okay with it living in a separate package though, I like the modularity of this ecosystem. Consult is pretty large as it stands.

Currently not, since I don't have a clear picture of what I want. But if it turns out that we find something small and generic I would be happy to add it. But adding multiple new sources, many commands etc, does not seem to me like a good idea at this point. I'd rather modularize the ecosystem more. Right now Consult is already pretty much a kitchen sink, but my general guideline is to maintain mostly reusable components here. For example `consult-org-heading` is a generic Org jumper, and you can glue it together with other commands or with Embark in order to get richer actions on the headings. Another example is the recently added `consult-line-multi`, which allows you to specify a query argument to restrict the set of buffers. This way I avoid having to add more special `consult-line-all-buffers-of-this-and-that-type` style commands.

> A `recentf-dirs` source is part of `consult-switch`, as my above post (with images) shows. The user can always disable the `bookmark-dirs` source if it's not a good fit, or I can disable it by default. (I personally find it quite useful.)

Yes, this is good. I was more thinking how I more restricted Consult version could look like if I wanted to add something small here.

> > Unrelated - but I've seen that you show the narrowing characters in the group titles. I've also considered this before but I always wondered if I would find it too noisy after having used a command for a while. Maybe I should add this nevertheless and guard it behind a flag `consult-group-title-narrow-key`. What do you think? I have to figure out if there is an easy generic way to do this. For historical reasons the narrowing and grouping functionality (while being very similar and overlapping superficially) is pretty much unrelated in their implementation.
>
> Narrowing is not a discoverable feature (unlike the groups), and it's unlikely that many users will go through the README carefully. Like Doom users who don't know or care what completion system they're using, for example. But having the hints in the group titles does look noisy to me, I have to actively resist the urge to remove it every time I use it. Maybe there's a less noisy solution, like showing the narrow key in the prompt instead? "Switch to (<): "?

Yes, this is true. But in any case it should be possible to turn of the additional help - I don't like to see too much nose.

>     * Project source: `project--list` is a variable maintained by Emacs, and I use it with very little transformation. No caching needed.

Good.

>     * Bookmark source: I have to filter `bookmark-alist` to directory bookmarks every time. If a user has >100 bookmarks, I don't know if performance will be impacted.

No problem at all as long as it is below 1k I think. But you can always add your own caching which keeps the transformed entries around for a while if it turns out to be a problem.

>     * Recentf source: Multiple transformations on `recentf-list` needed. Basically `recentf-list` -> `file-name-directory` -> `delete-dups` -> `abbreviate-file-name` -> filter to remove entries that are already in the other sources. I'm using `consult--define-cache` for this one, I don't have a good sense of whether this is necessary.

`consult--define-cache` does not exist anymore in the Consult main branch, so you cannot use this. You can roll your own cache or not cache at all. I am also not caching this anymore in Consult. It wasn't really a cache, but rather a means to avoid recomputation across multiple sources.

> I'll keep this in mind. So far the internals I've used are `consult-project-root-function`, `consult--project-root`, `consult--define-cache` and `consult--string-hash`, plus a couple of `consult-*-face`s. I don't plan to use any other internals, and will try to find an alternative to the cache functionality.

`consult-project-root-function` and the faces are public interface, the others are internal but are probably here to stay. The `consult--define-cache` macro is already gone.

**Comment by oantolin** [comment]
> I'm reasonably sure this switching feature can be handled more simply with Embark but I don't know how.

I'm pretty sure your `consult-insert-user-directory`/`consult-switch-directory` is very clunky to do with embark, probably the only way is basically just open some minibuffer prompt where you have the path you want (like, run consult-buffer in a recursive minibuffer, for example), use embark to save it to the kill-ring, then yank. So I believe that command is definitely needed (which is why I have my own baby version).

The command that run consult searches from a directory are sort of possible to emulate with Embark, but these commands you are proposing would still be significantly more ergonomic and I'd think they would be worthwhile.

The strategy to use Embark to run say, `consult-find`, in some directory is to open some minibuffer prompt with the starting directory you want, and then use `<embark-act> C-u C f` (embark-consult binds `consult-find` to `C r` in the general action map). This relies on the fact that with `C-u` the `consult-find` command _first_ prompts for a directory, so using `C-u C r` means the target is injected into the directory prompt, not the search prompt.

This is not too bad (and I often do it), but your commands are better in several ways:

- The biggest improvement I'd say is the centralized list of directories you'd want to use! Of course, for this you don't need a specialized `consult-switch-find-from-dir`, the generic `consult-switch-directory` has a minibuffer prompt with the centralized list of directories, so using `embark-act C-u consult-{find,grep,etc}` from within `consult-switch-directory` is pretty close to the specialized command.
- You have to press `RET` at the `C-u consult-find` directory prompt. This is because embark-consult puts `consult-find` on the allow edit list, because otherwise the non-C-u usage would be pointless: `consult-find` would close at once taking you to the first search result. I guess I could try to improve the `consult-find` support to be "press RET if the command was un with C-u and we are at the directory prompt, but don't press RET if no C-u was used so we are at the search term prompt". (I just wrote in oantolin.embark#252 ---which see, because it is about excatly this topic--- that you can't do that, but of course you can, this is Emacs after all.)

**Comment by oantolin** [comment]
Mmh. On further thought, maybe we really only need the `consult-switch-directory` and we can recommend jumping to consult search commands from there using embark-act. To avoid needing the C-u prefix for the consult search commands, small wrappers such as the one proposed by @andersjohansson in oantolin/embark#252 can be added to embark-consult.

**Comment by minad** [comment]
I would avoid adding small wrappers and rather explain the general concept, then users can easily add their own wrappers in order to not pollute the C consult keymap. Or we add two different keymaps C and D? What do you think about that regarding https://github.com/oantolin/embark/issues/252?

**Comment by minad** [comment]
If everything can be boiled down to a simply `consult-switch-directory` we could also add it to Consult directly. But I am not sure if I want to add another multi source command. consult-buffer is of a different quality/level, you interact with it always, in particular if you are a beginner. This `consult-switch-directory` command is a second-level construct, since you usually trigger it from the minibuffer in the second step.

**Comment by karthink** [comment]
> Seems different to me. The `+vertico-jump-file` which the Doom guys added, just finds all the files in the current directory for completion. Very similar to my `affe-find`, but synchronous.

You're right, I forgot how `counsel-jump-file` used to work. There might be some merit in making `consult-switch-jump-file` work like that.

> I also find `consult-dir` a bit too generic, but make your choice!

I'm leaning towards this more with each hour. It's short, simple and reasonbly descriptive.

> Currently not, since I don't have a clear picture of what I want. But if it turns out that we find something small and generic I would be happy to add it. But adding multiple new sources, many commands etc, does not seem to me like a good idea at this point. I'd rather modularize the ecosystem more.

I agree, this package is a little specialized and too kitchen sink.

> `consult--define-cache` does not exist anymore in the Consult main branch, so you cannot use this. You can roll your own cache or not cache at all. I am also not caching this anymore in Consult. It wasn't really a cache, but rather a means to avoid recomputation across multiple sources.

I'm not a programmer, so I don't have much experience with hash tables or caches. If I create a persistent `recentf-dirs` cache (list or hash), when/how would I update it? 

- One idea I had was to add hooks to recentf functionality (`recentf-add-file`, `recentf-cleanup` or wherever hooks are provided) to update `recentf-dirs` as well, this will take care of the computation problem. But I'm not supposed to add hooks except in a toggleable minor-mode.
- The other idea was to add some timers to update/clean-up the recentf-dirs list, but this has the same problem, plus the list might be out of sync when using consult-switch commands.

> `consult-project-root-function` and the faces are public interface, the others are internal but are probably here to stay. The `consult--define-cache` macro is already gone.

This ties into the preceding issue.

**Comment by karthink** [comment]
`consult-switch-directory` and `find-file-in-directory` can be a single command. It works like the former when called from the minibuffer and the latter otherwise. This simplifies usage considerably.

**Comment by karthink** [comment]
I thought of a way to reduce the noise with the narrowing hint. Is there a way to use a propertized string as the `:name` field of a consult-multi source? Instead of the group name "(p)roject dirs" I can use "**p**roject dirs" or some other subtler hint. I tried this but the `:name` field is expected to be a string with no properties.

**Comment by minad** [comment]
> I'm not a programmer, so I don't have much experience with hash tables or caches. If I create a persistent recentf-dirs cache (list or hash), when/how would I update it?

There is no need to do this for now. Just perform the computation on the fly.

> consult-switch-directory and find-file-in-directory can be a single command. It works like the former when called from the minibuffer and the latter otherwise. This simplifies usage considerably.

Yes, of course. I also thought about this.

> I thought of a way to reduce the noise with the narrowing hint. Is there a way to use a propertized string as the :name field of a consult-multi source? Instead of the group name "(p)roject dirs" I can use "project dirs" or some other subtler hint. I tried this but the :name field is expected to be a string with no properties.

Current there is no intention to allow such formatting, but we could consider allowing it in Vertico. I played a bit around with this and I somehow don't like key indicator in the group title. So I will probably not make changes in this direction.

**Comment by karthink** [comment]
Consult-switch is now [consult-dir](https://github.com/karthink/consult-dir).

There are two commands provided by this package:

- `consult-dir`: Switch directories easily using consult. When called from the minibuffer, choose a directory using consult and replace with or add the directory name to the prompt (with file-name shadowing). When called from a regular buffer, choose a directory and find-file there. This action is configurable. Quickly jump between "distant" directories this way. The list of directories to choose from is collated from the current project/directory, user bookmarks, project roots and recentf file locations.

- `consult-dir-jump-file`: Run `consult-find` in the directory currently in the minibuffer prompt, with the non-directory part of the prompt contents as initial input. Use this in combination with `consult-dir` to quickly "tunnel down" to files across the filesystem. (_I might remove this command from the package entirely to keep things focused, not sure yet if I should leave it in._)

Projectile projects are now supported as a directory source if projectile-mode is on (and will override project.el projects). Projectile is NOT required to use consult-dir.

`consult-project-root-function` needs to be set to enable the projectile/project.el source.

`consult-dir` uses `consult-multi` and thus appropriate annotations and embark-actions will be available for all candidate types if the user has marginalia installed. (_Not sure about this part._)

I will be submitting this to MELPA soon. There's one cache-related issue that I'm thinking on, but it's ready for testing. @minad and @oantolin, could you give it a spin?

**Comment by minad** [comment]
Sounds good! I will take a look soon at this. Is it necessary to hard code projectile support? Why not do it in the same way as consult - requiring some function to be set project-list-function or project-files-function?

**Comment by karthink** [comment]
Yeah, I don't want to hardcode it but I don't want the user to have to write a lambda either. I've modified it without hardcoding now:

```elisp
(defcustom consult-dir-project-list-function #'consult-dir-project-dirs
  "Function that returns the list of project directories.

These are used as candidates for switching when using `consult-dir'.

The options are

1. project.el project directories (the default)
2. projectile project directories
3. Any user-defined function. This function should take no
arguments and return a list of directories."
  :type '(radio
          (const :tag "Project.el projects" 'consult-dir-project-dirs)
          (const :tag "Projectile projects" 'consult-dir-projectile-dirs)
          (function :tag "User-defined function")))
```          

And added `consult-dir-projectile-dirs` to consult-dir.el. Is this something like what you meant?

**Comment by minad** [comment]
Looks good. I looked at the code again. The consult-dir-file-jump function can probably be simplified. Instead of relying on the shadowing overlay it is better to use substitute-file-name on the minibuffer-contents.

**Comment by minad** [comment]
You require project but projectile is autoloaded, is this intentional? I don't use projectile so I cannot tell - maybe it is based on project.el these days and loads it anyways?

**Comment by minad** [comment]
You may want to document that both consult-dir-project-list-function and consult-project-root-function should be set for projectile.

Maybe I should add generalized project support to consult: I could replace consult-project-root-function by a single consult-project-function which allows to query project information. The function should handle arguments 'current, 'list and 'files+path. I am not sure yet, but it could be useful for #315. The problem with #315 is that it could be potentially slow, which is undesired for a buffer switcher.

**Comment by minad** [comment]
One more comment - in yor documentation you write that the minibuffer-local-completion map should be used. Vertico/Selectrum use their own vertico-map/selectrum-minibuffer-ma derived from minibuffer-map. The minibuffer-local-completiion-map is only relevant for icomplete and default completion.

Vertico/Selectrum use their own map since this requires far less unbinding of undesired default keybindings. The default completion system is not ideally designed regarding the key maps. There are too many maps, some completion category specific. I consider this to be a bit of an obsolete design given completion categories. These are the reason for Selectrum/Vertico deviating from the default completion system.

**Comment by minad** [comment]
This is it from my side. If more questions come up, please ask. You may also want to link to the discussion here in the MELPA submission. Makes it easier for the MELPA maintainers if there has already been a review.

**Comment by karthink** [comment]
Thank you for the feedback, I'll incorporate it before submitting to MELPA.

> You require project but projectile is autoloaded, is this intentional? I don't use projectile so I cannot tell - maybe it is based on project.el these days and loads it anyways?

project.el is guaranteed to be present, users may not have projectile installed. So I `require` projectile from inside a condition-case in `consult-dir-projectile-dirs`. The `declare-function` projectile statements are to appease the byte compiler only. I should probably move the call to `require 'project` inside the relevant project function (`consult-dir-project-dirs`) as well.

**Comment by minad** [comment]
Yes, this improves lazy loading. Require takes a noerror argument, so you don't need a condition-case.

**Comment by karthink** [comment]
[MELPA PR](https://github.com/melpa/melpa/pull/7665) in the works.

Also [updated the README](https://github.com/karthink/consult-dir) with a more complete description and some videos showcasing different uses for `consult-dir`.

----

> Instead of relying on the shadowing overlay it is better to use substitute-file-name on the minibuffer-contents.

`substitute-file-name` does not appear to be a callable in my Emacs. There is `substitute-in-file-name`, but that does  environment variable substitution.

**Comment by oantolin** [comment]
> There is `substitute-in-file-name`, but that does environment variable substitution.

That's the one. Besides environment variable substitution it also handles shadowed paths.

**Comment by karthink** [comment]
> That's the one. Besides environment variable substitution it also handles shadowed paths.

Oh okay, I'll make the change.

> You may want to document that both consult-dir-project-list-function and consult-project-root-function should be set for projectile.

To avoid making the user configure two variables, I am planning to remove the use of `consult-project-root-function`  from consult-dir. The projects source is enabled whenever `consult-dir-project-list-function` is non-nil. 

`consult-project-root-function` is still used once in a call to `consult--project-root`, which I will handle internally instead soon.

> Maybe I should add generalized project support to consult: I could replace consult-project-root-function by a single consult-project-function which allows to query project information. 

This sounds like a good idea.

**Comment by karthink** [comment]
> (I just wrote in [Launching consult-*grep from find-file dialogs etc. oantolin/embark#252](https://github.com/oantolin/embark/issues/252) ---which see, because it is about excatly this topic--- that you can't do that, but of course you can, this is Emacs after all.)

The wrapper in oantolin/embark#252 is more or less what `consult-dir-jump-file` does, with some extra logic for handling shadowed file names. This is why I'm considering removing it from consult-dir. It's a useful piece of glue code but I'm not sure it needs to be included. I could also go in the other direction and add similar wrappers for grepping (`consult-dir-jump-grep`) etc. This usage of the async consult commands falls somewhere in between what consult-dir does and what Embark is set up to do.

**Comment by karthink** [comment]
Update: consult-dir is now on MELPA.

**Comment by oantolin** [comment]
And it went straight to my config replacing my bookmark-only version: oantolin/emacs-config@d064d356557a0c0fc89d8e81b6b10156673e339c.

I think `consult-dir-jump-file` had some trouble on Windows, but it works great here on my Chromebook. If I pin down the problem and figure out how to fix it on Windows, I'll let you know.

**Comment by karthink** [comment]
> I think consult-dir-jump-file had some trouble on Windows

That's odd, it's just a call to `consult-find`. Maybe something to do with the value of `consult-find-command` on windows?

**Comment by oantolin** [comment]
I think probably `consult-find` isn't working for on Windows either. I had forgotten but I think what happens is that there is some weird bug with quoting and the process API on Windows, and I had found a work around (maybe just escaping asterisks), but I haven't updated that work around for the recent changes in `consult-find`. I'll sort it out next time I'm on the Windows laptop.
