### ISSUE TITLE
How to make consult-narrow-help prompt appear automatically if there are multiple groups?

### ISSUE THREAD

**Issue by kings2u** [minad/consult#383]
The question pretty much says it all. I love the `consult-narrow-help` prompt and I think it would be handy to not have to invoke it with a hotkey (especially because the hotkey doesn’t seem to work unless I press it twice in a row). I tried addressing this with advice to, e.g., `consult-buffer`, but it was beyond my lisp skills. Would the easiest way to address this be through the `minibuffer-setup-hook`?

Let me know if I should elaborate, or if this isn’t the proper place to be posting the question. Thank you so much for your tremendous packages!

**Comment by minad** [comment]
Thank you!

1. You can configure a shorter key:

~~~ elisp
(define-key consult-narrow-map "\C-h" #'consult-narrow-help)
~~~

2. Show the narrow help immediately:

~~~ elisp
(defun show-narrow-help (&rest _)
  (cl-letf (((symbol-function #'minibuffer-message) #'message))
    (consult-narrow-help)))
(advice-add #'consult--narrow-setup :after #'show-narrow-help)
~~~

I hope this answers your question!

**Comment by kings2u** [comment]
As a quick follow up, how would I get similar functionality for `consult-bookmark`? 

Also I was wondering what resources you would recommend to someone like me (who has read the Introduction to Emacs Lisp but not the Emacs Lisp Manual) to acquire the skills to understand your code and not have to bug you with these customizations? Should I just read the Lisp Manual cover to cover, or are there other resources that helped you master it?

Thank you again!!

**Comment by minad** [comment]
> As a quick follow up, how would I get similar functionality for consult-bookmark?

It should also work for `consult-bookmark` and all other commands with narrowing.

> Also I was wondering what resources you would recommend to someone like me (who has read the Introduction to Emacs Lisp but not the Emacs Lisp Manual yet) to acquire the knowledge to better understand your code (especially your functional programming approach) and not have to bug you with these customizations? Should I just read the Lisp Manual cover to cover, or are there other resources that helped you master it and continue to debug it?

It depends on your background. The Elisp manual is definitely helpful to learn the Elisp idiosyncrasies, but I don't think it is crucial. If you know a bit of scheme, common lisp or any other programming language it should be quite easy to get started. The problem is to understand a bit how the Emacs APIs work, since Emacs is Elisp plus its APIs. There are not many intermediate layers between the user and the Emacs APIs, e.g., many functions are actually commands due to its `interactive` form. This is essentially what makes Emacs Emacs, it is a fully integrated Lisp programming environment with which you interact directly.

Fortunately Emacs is very self documented if you now how to access its help. Make the help accessible at point (e.g. `C-. h` if you bind `embark-act` to `C-.`). Use the `describe-*`, `apropos` and `find-library` commands. I can highly recommend the helpful package for a better help buffer. Also Marginalia is useful to get a quick overview over variables/functions/commands directly in the minibuffer. These utilities help you to navigate through the code of packages. There are also numerous Emacs developer resources or blogposts, you will find some lists if you search around.

The best way is of course to write some code. I can highly recommend the approach used by @oantolin in his configuration. The configuration is well structured around `use-package`, there is essentially not code in the init.el. Every non-trivial code is maintained in tiny packages, e.g., [text-extras.el](https://github.com/oantolin/emacs-config/blob/master/my-lisp/text-extras.el) which contains a bunch of editing commands. Then the package is pulled into the config like any other normal package. This model allows you to write a bit of code and directly use it in your Emacs setup without risking that your config spins out of control, which can easily happen if one copies Elisp snippets directly to the init.el.

If you already have a good understanding of the basics I suggest to suggest read the code of packages you are interested in or the Emacs code itself. Good starting point are the Emacs basics, e.g., simple.el, subr.el, minibuffer.el, seq.el etc.

Maybe @oantolin also has a few good tips?

**Comment by kings2u** [comment]
> It should also work for consult-bookmark and all other commands with narrowing.

I see now that it does work with `consult-bookmark` but that `consult--bookmark-preview` was overriding the message (from your `show-narrow-help` function) with the additional message `"No preview for %s"` (in my case, "No preview for Info-bookmark-jump"). This message was being sent despite the presence of the following in my config:

```
(consult-customize
 consult--source-file consult--source-project-file consult--source-bookmark
 :preview-key (kbd "M-."))
```

I needed to add `consult-bookmark` to the `consult-customize` list above to suppress the unwanted message.

And thank you so much for those many great tips on how to increase my elisp skills!! I took good notes and plan to study those resources thoroughly.
