### ISSUE TITLE
`consult-line-multi` typo (+ default to all buffers with same mode)

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#388]
I use this to search only buffers with matching major mode.  Maybe worth exposing, or even replacing the "search all buffers" with this.  It's rare you want to search across _all_ buffers independent of mode. 

```elisp
(lambda () (interactive)
		(consult-line-multi `(:mode ,major-mode))))
```

There is a typo I believe in `consult-line-multi` doc string: 

```
In order to search a subset of *buffers*
```

**Comment by minad** [comment]
Thanks, I fixed the typo. Exposing the restriction is not necessary, or it is already sufficiently exposed since you can write your wrapper passing the desired restriction.

**Comment by jdtsmith** [comment]
OK, thanks.  BTW, when restricting buffers, it would be helpful if the prompt were not just "Multiple buffers"  but "3 buffers" or similar.  Or ideally even "3 mode-restricted buffers".  Sometimes there is only 1 buffer with the current buffer's mode, but consult-line-multi still says it is searching "Multiple buffers".

**Comment by minad** [comment]
Yes, that's right. This could be improved. Consult-imenu-multi has the same issue. I didn't do this since it is not clear how to translate from a general buffer query restriction to a nice descriptive and short prompt. We could introduce a function consult--buffer-query-description or consult--buffer-query-prompt which provides such a mapping. PR proposal welcome of course!

**Comment by jdtsmith** [comment]
See #391.  BTW, an interface like `consult--buffer-query`, with many different configurable options, would be ideal for a [transient](https://github.com/magit/transient).
