### ISSUE TITLE
[bug report] consult-completing-read-multiple doesn't utilize crm-separator like completing-read-multiple

### ISSUE THREAD

**Issue by natask** [minad/consult#410]
consult-completing-read-multiple doesn't apply `crm-separator` like completing-read-multiple.  `completing-read-multiple` applies `crm-separator` on candidates (either before or after matching) while consult-completing-read-multiple does not.
* Difference
``` org
#+begin_src emacs-lisp :results org
(let ((crm-separator " "))
(consult-completing-read-multiple
		"> "
		(mapcar (lambda (tag-op) (concat tag-op crm-separator)) '("first" "second" "third"))))
#+end_src

#+RESULTS:
#+begin_src org
(second )
#+end_src

#+begin_src emacs-lisp :results org
(let ((crm-separator " "))
(completing-read-multiple
		"> "
		(mapcar (lambda (tag-op) (concat tag-op crm-separator)) '("first" "second" "third"))))
#+end_src

#+RESULTS:
#+begin_src org
(second)
#+end_src
```
* Affects
affects `notmuch-read-tag-changes`.

* Version
consult 0.9
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-07-07

**Comment by minad** [comment]
This is not a bug. You are using the API incorrectly, since you append the separator to the candidates itself. `consult-completing-read-multiple` is arguably doing the correct thing here. You don't observe the same result in `completing-read-multiple` since `completing-read-multiple` functions differently by splitting the crm-separated string afterwards.

**Comment by natask** [comment]
I found the behavior while using `notmuch-read-tag-changes` of `notmuch.el` package.

**Comment by minad** [comment]
Maybe the issue should be fixed in `notmuch-read-tag-changes` then. I looked at the source of an this function and it is not obvious to me why it produces such a completion table with space prefixed tags. See https://github.com/bencollerson/notmuch/blob/c8cb2beda711df8352680402a0df263fb8f31954/emacs/notmuch-tag.el#L71

**Comment by minad** [comment]
up to date source: https://git.notmuchmail.org/git?p=notmuch;a=blob;f=emacs/notmuch-tag.el;h=e3a60441a0b51a86d527b1c61fa6e9bd9a64a018;hb=HEAD

**Comment by natask** [comment]
The reason `notmuch-read-tag-changes` appends `crm-separator` to candidates is so that completing a candidate from candidate list allows one to enter another. Consult has this feature natively. 
I agree it is API abuse. I will put a bug report for notmuch. notmuch should atleast parse out `crm-separator` from candidates after match.

**Comment by minad** [comment]
> I agree it is API abuse. I will put a bug report for notmuch. notmuch should atleast parse out crm-separator from candidates after match.

Yes, it is very simple to fix on the side of notmuch by stripping the returned candidates afterwards.

**Comment by minad** [comment]
https://yhetil.org/notmuch/86a6k7hd43.fsf@gmail.com/T/#u
