### ISSUE TITLE
Is it possible automate switch to window *Completions*?

### ISSUE THREAD

**Issue by alexei-28** [minad/consult#424]
Linux Mint 20

Emacs 27.1

Install package: Consult, Vertico, Embark

Steps:

M-x shell

![1](https://user-images.githubusercontent.com/303539/133797406-9f37d4d2-4b52-4535-a293-5159ed04a879.png)
Input

`cat test.`

and press **TAB**
![2](https://user-images.githubusercontent.com/303539/133797473-f2b2ef47-f6f8-4e3d-8560-c5ef78559aee.png)
Open window` *Completions*` with possible candidates. Nice... but the cursor is not focus on this buffer. Cursor is still stay on shell buffer. So as result I need to press `M-<arrow down> (windmove-down)` to switch to window` *Completions*` and select desire candidate.

![3](https://user-images.githubusercontent.com/303539/133797553-6fb415aa-b8e2-456a-823f-889ae9f1e849.png)
It's not very convenient. Is it possible when press **TAB** to **automate** switch to window `*Completions*` ?

**Comment by minad** [comment]
1. You don't have `vertico-mode` enabled, otherwise you would not see a `*Completions*` buffer. Take a look at the Vertico README.
2. If you really want to use the `*Completions*` buffer and want to use this automatic switching there are other completion UIs available (vcomplete, Protesilaos' completion UI etc).
