### ISSUE TITLE
Add lookup-symbol function

### ISSUE THREAD

**Issue by dalanicolai** [minad/consult#431]
I could not find some consult version for lookup-symbol yet,
so I would like to make a request for it.

If it helps, I've already 'ported/copied' `counsel-info-lookup-symbol`
 to `consult`.

As I am not sure if I did things correctly, I will just paste it here
(instead of creating a PR or adding it to the wiki)
```lisp
(defun consult-info-lookup-symbol (symbol &optional mode)
  "Forward SYMBOL to `info-lookup-symbol' with consult completion.
With prefix arg MODE a query for the symbol help mode is offered."
  (interactive
   (progn
     (require 'info-look)
     ;; Courtesy of `counsel-info-lookup-symbol' and
     ;; `info-lookup-interactive-arguments'
     (let* ((topic 'symbol)
            (mode (cond (current-prefix-arg
                         (info-lookup-change-mode topic))
                        ((info-lookup->mode-value
                          topic (info-lookup-select-mode))
                         info-lookup-mode)
                        ((info-lookup-change-mode topic))))
            (enable-recursive-minibuffers t))
       (list (consult--read (info-lookup->completions topic mode)
                            :prompt "Lookup symbol: "
                            :require-match t
                            :history 'info-lookup-history
                            :default (info-lookup-guess-default topic mode)
                            :add-history (thing-at-point 'symbol)
                            :category 'symbol)
             mode))))
  (info-lookup-symbol symbol mode))
```

**Comment by minad** [comment]
> I could not find some consult version for lookup-symbol yet,
> so I would like to make a request for it.
> 
> If it helps, I've already 'ported/copied' |counsel-info-lookup-symbol|
> to |consult|.

As I see it, there is no need for this command in Consult. The existing
command info-lookup-symbol works almost well as is. The idea of the
Consult/Vertico/Embark/Marginalia ecosystem is to reuse commands when
possible instead of replacing them. The only thing I am missing are
annotations, but this should be fixed by adding a category classifier to
Marginalia. Is there something else you are missing?

**Comment by dalanicolai** [comment]
Ah okay, thanks! That's useful info. Although I am trying to read about and understand this 'new ecosystem' this was, evidently, not yet completely clear to me. So I will read more about marginalia then.
I do have another question, but I will open another issue for it to make it more informative/discoverable.

**Comment by minad** [comment]
> Although I am trying to read about and understand this 'new ecosystem' this was, evidently, not yet completely clear to me. So I will read more about marginalia then.

This selling point is maybe not directly clear, but the idea is that existing commands are only replaced if strictly necessary. If you look at Consult, most of the commands provide new functionality which is not yet present in this form in Emacs itself, e.g., consult-line. Other commands are replacements of existing commands but take another approach and extend the command with automatic preview (consult-imenu, consult-outline, consult-buffer).

But for many commands a replacement is not needed. Annotations can be attached afterwards to existing commands by Marginalia. In Ivy/Counsel this required a replacement of the command, but Marginalia is also supported by Ivy now, which may obsolete some Counsel commands if Marginalia is used instead of Ivy-rich. Furthermore actions are provided by Embark, if you only want to add actions to an existing command, it is not necessary to replace the command. Embark will just do it. In Ivy/Counsel once again this required a replacement of the command.
