### ISSUE TITLE
How to `:sort` `:groups` from `consult--read` ?

### ISSUE THREAD

**Issue by gagbo** [minad/consult#459]
Hello,

I have a small API question from `consult--read`. I'm trying to understand and solve gagbo/consult-lsp#21 which I've been able to reproduce myself for a while (but I never really cared because in my workflow I just directly narrow to the category I want to look at).

The only information in the docstring for `consult--read` is that `:sort` should be `nil` if the candidates are already sorted, but it doesn't mention the interaction with the grouping of candidates, which surely does something because I sort all candidates before grouping them :

```lisp
(defun consult-lsp--diagnostics--flatten-diagnostics (transformer &optional current-workspace?)
  "Flatten the list of LSP-mode diagnostics to consult candidates.
TRANSFORMER takes (file diag) and returns a suitable element for
`consult--read'.
CURRENT-WORKSPACE? has the same meaning as in `lsp-diagnostics'."
  (sort
   (flatten-list
    (ht-map
     (lambda (file diags)
       (mapcar (lambda (diag) (funcall transformer file diag))
               diags))
     (lsp-diagnostics current-workspace?)))
   ;; Sort by ascending severity
   (lambda (cand-left cand-right)
     (let* ((diag-left (get-text-property 0 'consult--candidate cand-left))
            (diag-right (get-text-property 0 'consult--candidate cand-right))
            (sev-left (or (lsp:diagnostic-severity? diag-left) 12))
            (sev-right (or (lsp:diagnostic-severity? diag-right) 12)))
       (< sev-left sev-right)))))
```

From looking at the code it looks like `sort` should be an alist describing some sort-functions, but how should I use those in pair with grouping in order to enforce some order in the groups ?

Regards,
Gerry

#### Ordering in narrow alist

the ordering of the entries in the `narrow` alist that I use isn't consistent with the observed results

```lisp
(defconst consult-lsp--diagnostics--narrow
  '((?e . "Errors")
    (?w . "Warnings")
    (?i . "Infos")
    (?h . "Hints")
    (?u . "Unknown"))
  "Set of narrow keys for `consult-lsp-diagnostics'.")
```

#### (or () 12)

We don't fall in the `12` fallback case, and I know that because the grouping uses the same `(lsp:diagnostic-severity? diag)` call to find out the correct group (and it works) :
```lisp
(defun consult-lsp--diagnostics--severity-to-type (diag)
  "Convert diagnostic severity of DIAG to a type for consult--type."
  (pcase (lsp:diagnostic-severity? diag)
    (1 (car (rassoc "Errors" consult-lsp--diagnostics--narrow)))
    (2 (car (rassoc "Warnings" consult-lsp--diagnostics--narrow)))
    (3 (car (rassoc "Infos" consult-lsp--diagnostics--narrow)))
    (4 (car (rassoc "Hints" consult-lsp--diagnostics--narrow)))
    (_ (car (rassoc "Unknown" consult-lsp--diagnostics--narrow)))))
```

**Comment by minad** [comment]
If the completion UI sorts (`:sort=t`), then the processing happens in the following order:

1. filtering of the candidates
2. sorting of the candidates (using default sorting function if `:sort=t`)
3. grouping, while retaining the order of the candidates (first candidate determines first group)

The shuffling of the groups is intentional, such that the most likely/best matching candidate appears at the top. 
There is no additional facility to explicitly control the sorting of the groups. However Vertico supports feature `vertico-next/previous-group` which allows you to cycle through the groups. When you do that the currently selected group should be locked for further filtering.

If you control the order of the candidates (`:sort=nil`) you also control the order of the groups. The first candidate determines the first group etc. However if you use a completion style which overrides sorting, this does not hold. For example flex does this in order to always move the best match to the top.

**Comment by minad** [comment]
But I must admit that I don't see anything wrong with your consult-lsp code by inspection. You sort by severity, so the group order should be retained. I use the same :sort=nil in combination with grouping for multiple consult commands (e.g. consult-buffer or consult-flymake), which don't show this shuffling effect of yours.

**Comment by gagbo** [comment]
I have been using vertico for a while but I don't remember if I had the issue

**Comment by minad** [comment]
I think I see the issue in consult-flymake too. No idea why I didn't observe it before. I will investigate a bit.

**Comment by minad** [comment]
No, false alarm - consult-flymake didn't sort properly. Fixed in https://github.com/minad/consult/commit/e8f4d9d99e7030243a3cec3aceadb8b2f0ac1679. But I don't see a random shuffling effect.

**Comment by minad** [comment]
Maybe you can narrow down the issue in a more minimal example?

You may want to look at the following places and check if the candidates get reshuffled in weird ways:

1. Sorting by the sort function happens here in vertico (With sort=nil, nothing should happen since the sort function will be identity): https://github.com/minad/vertico/blob/0df38cf1d7290d1be86ee9164a274cca0c306e03/vertico.el#L354

2. Grouping happens here: https://github.com/minad/vertico/blob/0df38cf1d7290d1be86ee9164a274cca0c306e03/vertico.el#L361-L362

**Comment by gagbo** [comment]
vertico--group-by seems to behave properly from my small examples 
```lisp
(vertico--group-by (lambda (elem &rest foo)
                     (if (oddp elem) "Odd" (if (< 3 elem) "Big even" "Small even")))
                   (list 2 1 3 5 4 6))
```

All variations of the list (given that it's already sorted) provide pretty stable variations. I suppose I should look into the `lsp-mode` function I'm calling in case there's some caching involved, but I'm not even sure.

**Comment by gagbo** [comment]
I'm going to close this anyway, since it seems that the sorting in my particular case is handled by other packages (vertico or selectrum or any package that actually care about `sort-function` and `group-function` in completion metadata)
