### ISSUE TITLE
consult-outline with default position at current header in org-file

### ISSUE THREAD

**Issue by fab6** [minad/consult#462]
Hi,

I am looking for an option to have `consult-outline` positioned at the current header in a org file. 
E.g. with this example
```orgmode
* Header 1 a
** INFO Header 2a

*** Header 3aa
*** Header 3ab
*** Header 3ac
*** Header 3ad
* Header 1 b
** INFO Header 2b

*** Header 3ba
*** Header 3bb
*** Header 3bc
*** Header 3bd
* Header 1 c
** INFO Header 2c

*** Header 3ca
*** Header 3cb
*** Header 3cc
*** Header 3cd
```
Starting with `consult-outline` at header `Header 3ba` like (see brown highlighted line):
![image](https://user-images.githubusercontent.com/3047695/140640429-ab9ffe94-c71a-4f00-9243-cf49c40faa39.png)

I get this direct jump to the top header in vertico buffer(see the grey highlighted line on header `Header 1a`)::
![image](https://user-images.githubusercontent.com/3047695/140640448-6b21362b-3c8d-4183-b012-3b0c34199932.png)

I.e. it start at the top header.

Is there an option that it is positioned at the same level (see the grey highlighted line on header `Header 3ba`):
![image](https://user-images.githubusercontent.com/3047695/140640463-16227e14-dd9e-4748-afd0-a893d9e21f7f.png)

I tried to find a similar question, but found mainly  #366  which seems not what I am looking for; probably  this is already described somewhere, which I did not see yet.

Thank you in advance!

**Comment by minad** [comment]
This is the precisely the same issue as #366 by @gira-x. The reasons why this has not been implemented are described in #366. Achieving the behavior you describes requires the completion UI to not move the default value and preserve the ordering of the candidates during filtering with respect to the default candidate. Currently I don't plan to add this feature to Vertico (https://github.com/minad/vertico/issues/92). Alternatively one could wrap around the candidate list as `consult-line` is doing. See also the related issue #287 regarding `consult-line`.

In order to obtain a persistent TOC I recommend to call `consult-outline` and then invoke `embark-collect-snapshot`. Maybe this is useful for you?

**Comment by fab6** [comment]
Ok, I get it now, thank you very much again! 
I will try your mentioned embark-TOC.

**Comment by Gira-X** [comment]
If you use Selectrum you might be able to use the following code which sets the `:default` key in the `consult--read` call to preselect the current org heading:

It's not perfect but works 'fine' enough for me :)

```emacs-lisp
(defun dima-consult-org-heading-default (headings)
  "Note that this returns the incorrect heading if there are headings with 
the same name."
  (when-let* ((current (save-excursion
                         (org-previous-visible-heading 1)
                         ;; remove leading /
                         (when-let ((breadcrumb (org-eldoc-get-breadcrumb)))
                           (substring breadcrumb 1))))
              (current-no-properties (substring-no-properties current)))
    (cl-find-if
     (lambda (it)
       (string-prefix-p current-no-properties (substring-no-properties it)))
     headings)))

(defun dima-consult-org-heading (&optional match scope)
  "Jump to an Org heading.

MATCH and SCOPE are as in `org-map-entries' and determine which
entries are offered.  By default, all entries of the current
buffer are offered."
  (interactive (unless (derived-mode-p 'org-mode)
                 (user-error "Must be called from an Org buffer")))
  (let* ((prefix (not (memq scope '(nil tree region region-start-level file))))
         (headings (consult-org--headings prefix match scope))
         (selectrum-move-default-candidate nil))
    (consult--read
     (consult--with-increased-gc (consult-org--headings prefix match scope))
     :prompt "Go to heading: "
     :category 'consult-org-heading
     :sort nil
     :default (dima-consult-org-heading-default headings)
     :require-match t
     :history '(:input consult-org--history)
     :narrow (consult-org--narrow)
     :state (consult--jump-state)
     :group
     (when prefix
       (lambda (cand transform)
         (let ((name (buffer-name
                      (marker-buffer
                       (car (get-text-property 0 'consult-org--heading cand))))))
           (if transform (substring cand (1+ (length name))) name))))
     :lookup
     (lambda (_ candidates cand)
       (when-let (found (member cand candidates))
         (car (get-text-property 0 'consult-org--heading (car found))))))))

(advice-add #'consult-org-heading :override #'dima-consult-org-heading)
```

Personally, I have both Vertico and Selectrum installed and switch to the one which simply behaves more the way I like it.
I switch to Vertico when displaying consult groups for instance because Selectrum has issues with the minibuffer height (https://github.com/raxod502/selectrum/issues/491) for me.

**Comment by fab6** [comment]
Thank you very much for the additional information!
