### ISSUE TITLE
consult-recent-file doesn't respect save-place-mode

### ISSUE THREAD

**Issue by notuntoward** [minad/consult#465]
When I visit a file, I have Emacs configured to return the cursor to the position I was the last time I visited it -- in my config, I have the line:

`(save-place-mode 1)`

This always worked before I switched to veritico/consult/..., and in fact, it still does work when I open a file with `M-x find-file`.  However, if I open it with  `M-x consult-recent-file`  it is always opened with the cursor at the top of the file.

This is on GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26

**Comment by minad** [comment]
Presumably the same issue as #464.

**Comment by notuntoward** [comment]
Isn't this is a different case than #464?  Here, I'm talking about what happens when the file is actually visited, not what happens in the preview.

**Comment by minad** [comment]
Maybe, but I don't see this issue. `consult-recent-file` just calls `find-file`, so everything should work as usual including `save-place-mode`. Can you reproduce the issue with emacs -Q?

**Comment by notuntoward** [comment]
With -Q,  `save-place-mode` is off.  But if I turn it on, places are always saved as expected, just like they were when I was using ido or ivy, etc.

It looks to me like this problem with consult only occurs for large files; when I start emacs normally (without -Q) short files do have their places saved, but big ones don't -- the same ones for which the red ^M's are shown in preview.

But as you point out, `place-save-mode` should work when you actually visit these files.

**Comment by notuntoward** [comment]
Were you able to reproduce the problem using my example file?

**Comment by minad** [comment]
The problem is that when you open a large file the file is previewed literally by Consult (with the Ms and the point at the top). Then the saveplace mode will unfortunately save the place at the top of the file. When you really open the file the next time saveplace will put the point again at the top.

In order to avoid this you have the following options:

1. Disable preview for `consult-recent-file`, or only automatic preview (recommended).
2. Use a larger limit for literal preview, such that the problem does not occur for the files you are interested in.

We could also try to work around this issue but I am afraid that it is not worth the complication. One could add the save place hooks to the `consult-preview-excluded-hooks` list, but this would lead to undesirable consequences. Then during preview saveplace mode would never be effective, not even for small files. We could then add a separate `consult-preview-excluded-literally-hooks` variable, which only applies when literal files are previewed. Furthermore the `consult-preview-excluded-hooks` are only used to filter the `find-file-hook` and not the `kill-buffer-hook`, which would be necessary to avoid this problem, since the saveplace mode installs its hooks for both `find-file` and `kill-buffer`.

**Comment by minad** [comment]
Furthermore there is one oddity here - `saveplace-mode` seems to not jump to the position of a literally opened file but it still remembers the position in a literally opened file. I argue that this is wrong. This is actually the cause of the issue. If you want to see this fixed one should send a bug report upstream. But of course this would need some more investigation and one should reproduce the issue without any packages in emacs -Q only.

**Comment by notuntoward** [comment]
Thanks.  I'll also submit the saveplace-mode bug.

**Comment by CloseToZero** [comment]
As a workaround:

```lisp
(defun my/dont-save-place-when-find-file-literally (orig-fun &rest args)
  (unless find-file-literally
    (apply orig-fun args)))

(advice-add #'save-place-to-alist
            :around #'my/dont-save-place-when-find-file-literally)
```

**Comment by notuntoward** [comment]
Thanks!
