### ISSUE TITLE
How to use regex in consult-line?

### ISSUE THREAD

**Issue by FirstLoveLife** [minad/consult#469]
Cannot find any yet. Swiper has good support for regex.

**Comment by minad** [comment]
You can use the orderless completion style. See also https://github.com/minad/consult#recommended-packages.

**Comment by FirstLoveLife** [comment]
> You can use the orderless completion style. See also https://github.com/minad/consult#recommended-packages.

Thanks! But I found with orderless, I can use most regex, but I still cannot use `\s` to match space, which is weird.

**Comment by oantolin** [comment]
That's not Emacs regexp syntax. In Emacs you match a space with `\s-`. You should read the [section of the manual on regexp syntax](https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html), several small things may differ from what you are used to on other tools.

**Comment by minad** [comment]
Consult uses the Emacs regexp expression syntax consistently across all commands in order to match all the other Emacs search commands (isearch, occur, regexp search and replace). Even for the grep commands a syntax translation is performed. Therefore it is valuable to familiarize yourself with the Emacs regexp syntax!

https://github.com/minad/consult/blob/0d0a2f335889f82e91d96f77d71884ebd554aa62/consult.el#L568-L587

**Comment by FirstLoveLife** [comment]
Thanks! I was a ivy/swiper user, swiper use `\s` and `space space` for space.
