### ISSUE TITLE
Possible to refresh the changed results in consult-buffer and consult-register?

### ISSUE THREAD

**Issue by kings2u** [minad/consult#474]
When I use `embark-act-noquit` and `k` to kill a buffer in `consult-buffer` (with the goal of keeping the minibuffer up so that I can continue acting on existing buffers), the `consult-buffer` minibuffer still displays the just-killed buffer. It's not until I exit the minibuffer and re-execute `consult-buffer` that the killed buffer goes away. Is it possible to refresh the display immediately so that the killed buffer disappears from `consult-buffer` right after being killed? 

I wasn't sure if this was an Embark issue, but since I've also written a similar function that doesn't use Embark and clears an existing register from the list of candidates in a `consult-register` minibuffer, I figured I'd post here. Thanks for any help you or @oantolin can offer!

EDIT: I should also mention that I'm using Vertico, and that `(consult-vertico--refresh t)` didn't do the trick.

**Comment by minad** [comment]
I assume you use an outdated version of embark since buffer killing via embark-act in consult-buffer refreshes the mini buffer. See the variable embark-post-action-hooks.

Please make sure that you use updated embark and consult version and test with emacs - Q (only vertico, consult, embark). If this doesn't solve the issue please let us know.

**Comment by oantolin** [comment]
As @minad said, you probably haven't updated Embark in a long time: the function `embark-act-noquit` was removed a while back. Now there is only a single `embark-act` function and a variable `embark-quit-after-action` that controls whether the minibuffer is quit or not. I think this changed several months ago!

**Comment by kings2u** [comment]
> the function embark-act-noquit was removed a while back

I just noticed this function actually came from my init.el. I should have prefixed it with my own namespace!
```
(defun embark-act-noquit ()
  "Run action but don't quit the minibuffer afterwards."
  (interactive)
  (let ((embark-quit-after-action nil))
    (embark-act)))
```

I found that the culprit preventing the minibuffer from refreshing after killing a buffer in `consult-buffer` was that I had globally remapped `kill-buffer` to my own custom function. Maybe NOW I will remember not to report a bug until after testing with emacs -Q!

Thank you for the tip regarding `embark-post-action-hooks`. Here is what I now use to immediately kill the selected `consult-buffer` candidate:
```
(defun my/embark--quick-kill-selected-buffer ()
  (interactive)
  (kill-buffer (plist-get (car (embark--targets)) :target))
  (embark--restart))

(defvar my-consult-buffer-map
  (let ((map (make-sparse-keymap)))
    (define-key map "\M-w" #'my/embark--quick-kill-selected-buffer)
    map))

(consult-customize consult-buffer :keymap my-consult-buffer-map)
```

One slight bug is that if I'm in Buffer A when starting `consult-buffer`, if I then delete Buffer A with my function I will get the error "Selecting deleted buffer" after quitting the minibuffer (since Buffer A no longer exists). This issue is not restricted to just my function; I get the error in emacs -Q when using Embark with a prefix argument to kill a buffer. Do you have a suggested fix? (BTW, I got the functionality of using Embark to kill a buffer from Karthink's post at https://githubmemory.com/repo/oantolin/embark/issues/231)

> For consult-register how does your function work btw?

I'm sure it could be improved upon (for example I probably shouldn't be using embark internal functions), but it seems to be functional:
```
(defun my/delete-register (&optional regchar)
  "Delete register, either a candidate in `consult-register' or REGCHAR."
  (interactive)
  (if (equal embark--command 'consult-register)
      (progn (set-register (string-to-char (vertico--candidate)) nil)
             (embark--restart))
    (if regchar
        (set-register regchar nil))))
```

On a related note, when I try to save point registers between emacs sessions using session.el, they are converted to file registers and no longer retain their preview of searchable buffer positions in `consult-register`. Is there a way you'd recommend to save registers between sessions?

Thanks again to both of you for your service to the emacs community!

**Comment by minad** [comment]
> Maybe NOW I will remember not to report a bug until after testing with emacs -Q!

Yes, this would be good. See also https://github.com/minad/consult/#bug-reports ;)

> One slight bug is that if I'm in Buffer A when starting consult-buffer, if I then delete Buffer A with my function I will get the error "Selecting deleted buffer" after quitting the minibuffer (since Buffer A no longer exists). This issue is not restricted to just my function; I get the error in emacs -Q when using Embark with a prefix argument to kill a buffer.

I don't think there is a resolution. This is basically an Emacs bug since when leaving the minibuffer, Emacs tries to restore the window configuration including the last buffer. So I would say - don't do this, don't kill the current buffer!

> I'm sure it could be improved upon (for example I probably shouldn't be using embark internal functions), but it seems to be functional:

I suggest you look into how to define Embark actions properly. Your approach works of course, but you use vertico and embark internals. You could do this more cleanly with embark-define-keymap and registering the keymap for the consult-register completion category. The Embark README and wiki describe in detail how to do this.

> On a related note, when I try to save point registers between emacs sessions using session.el, they are converted to file registers and no longer retain their preview of searchable buffer positions in consult-register. Is there a way you'd recommend to save registers between sessions?

Hmm, that's odd. As soon as you kill buffers Emacs converts buffer registers to `file-query` registers (as opposed to plain `file` registers without position), see `register-swap-out`. If you make use of that functionality you should get filename plus position. But I am not saving registers, so I don't have a snippet to share.
