### ISSUE TITLE
Consult-buffer initial narrowing candidate selection

### ISSUE THREAD

**Issue by tpeacock19** [minad/consult#477]
I'm not sure if this has been addressed, but there is a slight difference when using the initial narrowing mentioned in the [wiki](https://github.com/minad/consult/wiki#start-command-with-initial-narrowing) with `?b` as the initial key versus other values. It does not select the first candidate in the list, thus even when the matching candidate is filtered you have to manually select it with `vertico-next` in my case. 

Is there a way to get the behavior closer to the standard `consult-buffer`? Thanks!

![2021-12-03T13:31:13,464628257-07:00](https://user-images.githubusercontent.com/6407145/144669463-340a1392-bc4a-4dd2-8068-cf54d94b8f53.png)
![2021-12-03T13:30:54,369230189-07:00](https://user-images.githubusercontent.com/6407145/144669466-93db6f6d-5a8d-499d-acf4-2f1e4c2a2a22.png)

**Comment by minad** [comment]
The issue is that `consult-buffer` specifies a `:default` value. If you initially narrow to files for example, the default is still a buffer and therefore the prompt is selected in Vertico, such that when you press RET, the default is submitted.

You can overwrite the default to work around this:

~~~ elisp
(consult-customize consult-buffer :default nil)
~~~

Probably you only want to apply this setting locally for some command. Note that you can also easily create your own command using `consult--multi`, reusing the `consult-buffer-sources`.

**Comment by tpeacock19** [comment]
That's perfect. I had defined a couple small wrappers and have customized them as you showed and it works for me. I'll have to take a look into `consult--multi` but for the time being I appreciate more focused commands.

**Comment by minad** [comment]
I revisited this issue and improved the behavior, see #714.
