### ISSUE TITLE
Improve user interface and performance of `consult-line`

### ISSUE THREAD

**Issue by salutis** [minad/consult#487]
I use `consult-line` all day every day, and I love it. After about 6 months of use, I would like to suggest and discuss the following two improvements:

(1) When the user calls `consult-line`, it shows a buffer that duplicates the lines that appear above it. Unlike `M-x`, `C-x b`, and other commands, `consult-line` shows no history, and duplicating the lines before the user types anything does nothing for the user, it just makes the command "feel busy". Could we make `consult-line` like the other commands that show the prompt and nothing else until they have something meaningful to show?

(2) In larger files, such as longer Org documents, `consult-line` takes 4-5 seconds on my machine to appear (for the first time). Based on some messages I sometimes see, it seems that the command fontifies the entire buffer upfront. Is that why we have the delay? If so, could we do it lazily or in the background instead? Perhaps we could make it better in combination with (1) above?

Thank you!

**Comment by minad** [comment]
Thank you for the suggestions! These have all been considered To say it directly - `consult-line` is perfect as is in its current simple form and there is no room for improvement. It is very much in a local optimum.

> (1) When the user calls `consult-line`, it shows a buffer that duplicates the lines that appear above it. Unlike `M-x`, `C-x b`, and other commands, `consult-line` shows no history, and duplicating the lines before the user types anything does nothing for the user, it just makes the command "feel busy". 

That's right. The solution for this problem is to use a completion UI which shows the completion candidates on demand or only after you typed a certain amount of characters. You can try @protesilaos' Mct as alternative to Vertico. In Vertico I also added a few recent improvements, which work in the direction of making Vertico more tunable per command. Take a look at these links:

* The [vertico-multiform](https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category) extension allows you to configure Vertico per command
* Maybe also the discussion in https://github.com/minad/consult/issues/486 is interesting, where I wrote about the vertico-multiform extension.
* A potential [vertico-demand](https://github.com/minad/vertico/issues/149) extension has been proposed, which would hide the Vertico popup for longer. It has not been implemented yet, but I may add this in the future.

There is one alternative solution I should mention. One can also implement a `consult-line-delayed` command which computes the matching lines after you entered a single word. If you enter more words the usual Emacs filtering could take over. See https://github.com/minad/consult/issues/417#issuecomment-922480825 for a `consult-line-delayed` command, which resembles `swiper-isearch`. I don't want to add this command though. As I wrote before, `consult-line` does not aim to compete with Isearch as a general search command. As such it is acceptable that has a certain startup time.

> Could we make `consult-line` like the other commands that show the prompt and nothing else until they have something meaningful to show?

You probably mean the commands like `consult-grep`. Yes, this is already possible and this also solves the issue for large files. You can configure `consult-grep/ripgrep` to search through a single file only instead recursively through a directory tree. I think I've seen such a `consult-ripgrep-this-file` command in @mohkale's configuration. Maybe this command could be added to the wiki, @mohkale? There is already the [my-consult-grep-or-line](https://github.com/minad/consult/wiki#counsel-grep-or-swiper-equivalent) command in the wiki, which either uses `consult-grep` or `consult-line` depending on the buffer size. The downside of `consult-grep` for searching is that you don't get fontification in return.

> (2) In larger files, such as longer Org documents, `consult-line` takes 4-5 seconds on my machine to appear (for the first time). Based on some messages I sometimes see, it seems that the command fontifies the entire buffer upfront. Is that why we have the delay? If so, could we do it lazily or in the background instead? Perhaps we could make it better in combination with (1) above?

The slowdowns is caused by two things:

1. The fontification is the major problem. Unfortunately Emacs does not have the ability to fontify in the background as far as I know. The reason is the single-threaded nature of Emacs. If you feel bold you could propose the introduction of javascript-like workers (or Erlang or other systems which have isolated runtimes) to the Emacs developers. Then one could start a background job, which does not share data with the main thread (not requiring a global interpreter lock this way). The only data which would be shared via explicit message passing is the unfontified buffer and the fontified buffer in return. Currently one can implement something like this by starting a background Emacs process (see for example the async package), but this is a heavyweight solution. Now to the actual solutions in Consult: 1. Consult offers the variable `consult-fontify-max-size` which you can adjust to avoid the fontification of large buffers.  2. Consult offers the variable `consult-fontify-preserve` which you can set to nil. Then no fontification is computed or kept, which leads to significant speed-ups.

2. The GC sometimes sets in, depending on your GC configuration. `consult-line` temporarily increases the GC limit to speed up the candidate line generation process. However before showing the UI we decrease the limit again. Then a GC may trigger if the default limit in your configuration is low.

Please check out the existing resources and let me know what you think.

**Comment by salutis** [comment]
@minad ACK. I have read your reply three times already. Wow! I will need to set aside some extra time to process all this information.

**Comment by minad** [comment]
I've implemented a dynamic consult-line-multi command, see https://github.com/minad/consult/commit/1247248ff023c970591ec2a99655132e2a81ee45 and https://github.com/minad/consult/issues/644. It should behave mostly like consult-grep but on buffers. The candidates are dynamically computed after entering some input, like swiper-isearch.
