### ISSUE TITLE
Improve focus-lines UI

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#496]
As discussed in PR #495, the UI for focus-lines is a little opaque.  Ideas for useful features:

1. Show an updating visible/total line count at left.  Each are easily derived with the current structure for one filter (only).  Similar to how `consult-buffer` shows selection/count. 
2. Give an indication of the already applied filters, perhaps with coloring and count for positive (include) and negative (exclude) filters.  Could also show the filter strings themselves (but perhaps only after the prompt). 

So like:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/93749/148865173-b79d58e1-398e-4e86-b89b-e12da7f7da5f.png">

This can be independent of any "merging or filter composition" changes.  E.g. it would work even with the "just add more overlays and let Emacs sort it out" approach, if we can come up with a simple way to tally lines which are "multiply invisible".

**Comment by jdtsmith** [comment]
It also occurs to me that focus-lines and keep-lines are basically doing the same job, except the former applies an invisible overlay and the latter removes the text altogether (when complete).  Might be possible to merge and create thin wrappers around the core algorithm.

**Comment by minad** [comment]
Hmm, maybe it is possible to optimize keep lines too. Note that keep lines also has to take some care about undoing etc. If you delete input and suddenly more matches appear you have to reinsert the content, so I am not sure if you can improve the status quo. Of course one could also use overlays for the intermediate state and only modify the buffer in the final step. Would that be preferable? I intentionally decided against this since this allows you to move to the buffer copy text via recursive editing. If the whole buffer is hidden by an overlay this keep-lines advantage is lost.

**Comment by minad** [comment]
Close due to inactivity. Please ping me if something materializes.
