### ISSUE TITLE
How to wrap long file name in the Consult-buffer display

### ISSUE THREAD

**Issue by jayrajput** [minad/consult#506]
Here is a screenshot showing the issue. The first entry which is a long name is not fully visible. Not sure if using emacs in terminal on windows/wsl2 is making any difference.

![image](https://user-images.githubusercontent.com/2172309/152645920-f5c20200-e6aa-4dad-ba23-f1b738537e18.png)

**Comment by minad** [comment]
I assume you use Vertico. Vertico currently assumes that candidates fit on a single line. There has been the proposal to enhance `vertico-buffer` to also allow multi line candidates. But no such support has been added so far, since it interferes with resizing and scrolling. For now you can disable truncation like this:

~~~ elisp
(advice-add #'vertico--resize-window :after #'vertico--no-truncate)
(defun vertico--no-truncate (&rest _)
  (setq-local truncate-lines nil))
~~~

**Comment by jayrajput** [comment]
Thanks. I do use vertico. And the suggestions works like a charm.
