### ISSUE TITLE
Consult to search from two sources: file names and file contents.

### ISSUE THREAD

**Issue by zxcvbn97** [minad/consult#512]
I am building an elisp function to search for a keyword that appears in either a file name or a file content. I have a directory of org notes and would like to use consult to search for that. 

I am aware of consult-ripgrep and consult--multi but don't know how to do this? Can you please help

**Comment by minad** [comment]
You could write a shell script:

~~~ elisp
#!/bin/sh
find . -not '(' -wholename '*/.*' -prune ')' -iregex ".*$1.*" \
     -exec echo -en "{}\x001:" \; -exec head -n 1 {} \;
rg --null --line-buffered --color=never --max-columns=1000 \
  --path-separator / --smart-case --no-heading --line-number . -e "$1"
~~~

Then configure `consult-grep-args` to use this script instead of grep. I hope this helps. You can also solve this on the level of Elisp, combining the output of two processes, but it will be much more difficult and you would have to write some additional infrastructure, since Consult does not support this.
