### ISSUE TITLE
Defer loading major mode, or exclude certain modes on preview

### ISSUE THREAD

**Issue by Qkessler** [minad/consult#515]
Hi there, dropping a quick issue as I was thinking about a problem that I usually have when using the live-preview feature. Normally I have it off, as I believe sometimes it slows down my Emacs considerably.

An example of this is when previewing a file which has a major mode that is controlled by lsp-mode. The live-preview loads the major mode and lsp-mode, which causes the language server initialization. For heavy-handed servers, this process is slow, and I find myself waiting for the server to initialize, even if I wasn't planning on opening that file.

I have a couple suggestions:
- The problem that I see with deferring the major mode is that the preview will have no syntax highlighting.
- Maybe there could be a variable for major modes that should be taken care of differently (for previews), even if the candidate list is the same. This would probably mean having control over the candidates individually, but I don't find this to be a problem as we are already doing that when building the candidate list.

I created this issue to start a discussion, what do you think? Have you already sunk some time thinking about this topic?

**Comment by minad** [comment]
First I recommend to disable automatic preview for certain slow sources, see https://github.com/minad/consult#live-previews. I assume you are already aware of this possibility?

Besides that there are these options to fine tune preview:

- consult-preview-raw-size/max-size
- consult-preview-excluded-hooks

consult-preview-excluded-hooks only filters the find-file-hook. So maybe we should add a possibility to filter out other hooks too. But I haven't figured out a generic way of doing that yet.

**Comment by minad** [comment]
@Qkessler Do you have feedback or a concrete, actionable proposal? Closing this for now.

**Comment by Qkessler** [comment]
Hi there, sorry for taking so long! The new job has been interesting but time-consuming (as it should be). I don't really have a clear proposition, but since my use-case is lsp-mode, I could investigate how and when the lsp-mode is enabled, i.e. I would have expected to also be a find-file-hook function, since it activates when the file gets loaded, but I'm not really sure how it really works. 


> consult-preview-excluded-hooks only filters the find-file-hook. So maybe we should add a possibility to filter out other hooks (e.g., hooks of the major mode) too. But I haven't figured out a generic way of doing that yet.

This is really interesting, I have tried using both variables but they are not applicable for by use-case. I'm fine with closing the issue, we can still comment on it when we have the time.

Thanks @minad
Best,
Enrique.

**Comment by minad** [comment]
Okay, feel free to make proposals at any time and continue to comment here. I tend to close issues which don't involve bugs or imply something directly actionable. This doesn't mean that we cannot improve on the preview hook issue, preview buffer filtering etc.

**Comment by chasecaleb** [comment]
For what it's worth I would also use this functionality if it were available to delay loading LSP mode since LSP servers are slow to start up, particularly in larger projects. This isn't an absolute must have since it just blocks for a second or two, but it would be a nice to have.

As for implementing it: I load LSP by adding `lsp-deferred` to various major mode hooks, e.g. `nix-mode`, `sh-mode`, `typescript-mode`, and so on. So perhaps in addition to checking `find-file-hook`, you could also determine the buffer's major mode and check the major mode's hook. Alternatively, if you want something more generic then maybe a second `defcustom` to allow users to specify a map of hook -> functions within the hook to exclude?

Sadly I'm also in the "don't have time to work on it in the conceivable future" boat. @minad if you want to let me know youru thoughts on my two implementation ideas I may come back to implement this sometime in the future if I get annoyed enough, haha.

**Comment by jdtsmith** [comment]
Looks like we are thinking along similar lines.  I solved the lsp case by [testing for preview](https://github.com/minad/consult/issues/538#issuecomment-1069646334) during initialization.  But a more general approach would be nicer.  It's too bad modes do not have a uniform and separable way of configuring their font-lock keywords, since that's the most important part of the preview IMO.  My proposal over in #538 was to have a let-bound list of variables wrapped around the preview function, which users could configure to disable various unwanted initialization during preview.  But a useful collection of such variables would have to be discovered.
