### ISSUE TITLE
consult-line makes subsequent navigation in large file buffer very slow

### ISSUE THREAD

**Issue by bbktsk** [minad/consult#517]
I have a very large file (4214473 lines, ~520MB) open in the Fundamental mode, with emacs 27.2 running in a text mode in a terminal over ssh. Initially, everything works as expected, but once I invoke `consult-line` and quit it, navigation in the buffer suddenly becomes very slow with screen redraws taking several seconds.

Steps to reproduce:
- `emacs -nw -q`
- eval minimal config:
```
(package-initialize)
(require 'consult)
(setq completion-styles '(substring))
 ;; gc setting does not seem to have much impact on the issue, it is included just to indicate I've already tried it
(setq gc-cons-threshold 1000000000) 
```
- `C-x C-f verylargefile.txt` , select "yes" on the confirmation prompt
- confirm that navigation in file is fast: `PgDown`, `PgUp`, `M-<`, `M->` executes  "immediately" (maybe 0.1sec? The speed I'm used to from regular sized files.)
- `M-x consult-line`. Wait ~60 sec for the prompt (that's unfortunate but expected and not the topic of this issue). 
- Do not search for anything, just `C-g` to abort search.
- `PgDown`, `PgUp`, `M-<`, `M->` are now very slow, with screen updates after each taking several seconds. Screen seems to be updated in "batches", each containing about 5 lines and taking ~0.5 sec to complete, including slight yet visible delay between batches.

Running cpu profiler during navigation shows that most of the time is spent in the `redisplay` function.

Using emacs-27.2 on Linux running on 20core/64GB VM. All packages were freshly installed today.

**Comment by minad** [comment]
`consult-line` generates many markers, which are registered in a buffer linked list. It may be that these markers lead to issues here. Needless to say that `consult-line` is not designed to handle such large files (use occur or consult-grep instead). However we can still try to figure out the issue here. Please replace `(point-marker)` with `(point)` and then `M-x compile-defun` to check if the problem goes away:

https://github.com/minad/consult/blob/1d5571f57977067fa9e4ac3794b0cb0fbca5dc6a/consult.el#L2788

If the problem goes indeed away with this change it may make sense to introduce a "cheap mode" where we use integers instead of markers, with the downside that recursive editing will not work and the positions will lose their validity as soon as the file is edited. This matters in particular for Embark export/snapshort. Embark could convert to markers when exporting.

**Comment by minad** [comment]
We could also just bail out early in `consult-line` if a file has more than 100k lines, in order to avoid issues in case the command is invoked accidentally. But then you have to wait for a minute, so you could always press C-g earlier which would ensure that your Emacs stays responsive. One could also try to reset the markers when quitting from `consult-line`, such that they are removed from the linked list. Maybe it would be even sufficient to run the garbage collector. @bbktsk This makes me wonder - do you have special garbage collector settings? Maybe some hack which prevents the gc from running?

**Comment by oantolin** [comment]
The manual does advise using `(set-marker m nil)` when you are done with a marker. If I understood correctly, even if the marker is garbage, it is still updated until such a time when it is garbage collected. So (1) maybe if consult-line just sets the markers to `nil` upon quitting the problem disappears,  and as @minad said, (2) maybe immediately running the garbage collector upon exit also fixes the problem.

If setting the markers to nil upon exit fixes the problem, we might be able to easily arrange things so that embark-export just skips that step.

If neither setting the markers to nil nor running the garbage collector work satisfactorily, the other strategy mentioned earlier of using "cheap markers" does not sound like too much of a complication either, and I'd be happy to go along with it by making the necessary changes to embark-consult.

**Comment by minad** [comment]
I just tried `consult-line` again on medium size files with 20k lines and I don't see any observable difference there. So I wonder if we should even do anything here, since invoking `consult-line` on larger files already doesn't make sense. It seems to me that, at the point where the markers start to matter, `consult-line` is already far from usable. However it may be possible to prove otherwise via benchmarks.

So under that assumption it is more a question of safe guarding against misuse and preventing `consult-line` from creating all these markers and to abort cleanly. The question remains why the gc does not set in. One could argue that as a user one will probably not wait for a minute and hitting C-g early will also prevent the issue. In order to be extra safe one could also introduce a buffer size check.

**Comment by minad** [comment]
> The manual does advise using (set-marker m nil) when you are done with a marker. If I understood correctly, even if the marker is garbage, it is still updated until such a time when it is garbage collected.

I don't think that this is generally a good advice :-P

~~~ elisp
(let (markers)
  (dotimes (n 1000000)
    (push (point-marker) markers))
  (dolist (m markers)
    (set-marker m nil)))

(let (markers)
  (dotimes (n 1000000)
    (push (point-marker) markers))
  (dolist (m (reverse markers))
    (set-marker m nil)))
~~~

**Comment by bbktsk** [comment]
I do not have any extra gc settings except for `gc-cons-threshold`. I tried running `garbage-collect` in the degraded state, but it did not solved the problem.

**Comment by minad** [comment]
@bbktsk The issue should be fixed by https://github.com/minad/consult/commit/9f94c6b00d718d3574901d570e1005a280b4e6b0.

**Comment by bbktsk** [comment]
Confirming it is fixed now.

Thank you for super fast help with this! It was awesome, esp. considering how very specific problem it was. If you ever visit Prague, CZ, let me know, I'll buy you a beer! 8)

**Comment by minad** [comment]
Thanks! Good performance is a priority. I will take you up on that in case I will visit Prague again :) Have fun with Consult and the other packages! If you have discover more issues or have improvement proposals, please let me know.
