### ISSUE TITLE
drop --regexp for consult-locate

### ISSUE THREAD

**Issue by sje30** [minad/consult#554]
`consult-locate-args` has a defaut value of   "locate --ignore-case --existing --regex"

I found that consult-locate is quite slow with the --regex switch.  Is it worth considering dropping that flag by default?  I'm using the plocate implementation of locate which notes that 

```
       -r, --regexp
              Patterns  are  taken to be POSIX basic regular expressions.  See
              regex(7) for more information. Note that this  forces  a  linear
              scan through the entire database, which is slow.
```

Just an idea, please ignore if you prefer.  But for me, this makes the consult-locate close to instantaneous, whereas with --regexp the process takes several seconds (even on a fast laptop).

**Comment by minad** [comment]
Indeed. It makes sense to treat the input literally to take advantage of the database index. I must admit, I don't use the locate command and I think it is generally not used widely given that I've gotten not much feedback about this command in comparison to other commands like `consult-grep`. Please let me know if the problem is solved by https://github.com/minad/consult/commit/53b0e41770ec9e5ebd0e8ab778cf636a1e8a90fa. Note that not much is lost since we can still take advantage of the Emacs filtering via the input splitting, e.g., `#literal#some completion style filter`. Only `literal` will be passed to `locate` and the candidates will then be post filtered by the rest of the input.

**Comment by sje30** [comment]
Thank you very much for the update.  Just tested and all working as I hoped.
