### ISSUE TITLE
`consult-kmacro` does not show the `key` a macro is bound with

### ISSUE THREAD

**Issue by anupam312nwd** [minad/consult#561]
Hi,
This is a feature request for `consult-kmacro`. I often define many macros on the fly and use `evil-execute-macro` to use it.
But after a while, I forget which `macro` is bound with which `key` in the register.

Will it be possible to show the key in `consult-kmacro` at the beginning similar to the one appear in `consult-register`?
Thanks!

**Comment by minad** [comment]
This sounds like a reasonable proposal, but I don't see a direct way to find the corresponding key to a macro. If you bind macros via `C-x C-k b` (`kmacro-bind-to-key`) then an anonymous closure is produced and bound to the key. The closure contains the macro definition. One could try to create a similar lambda form via `kmacro-lambda-form` and try to look it up via `where-is-internal`. This may work or may not work. In any case it does't seem very robust. For this technical reason I prefer to not add this feature.

**Comment by anupam312nwd** [comment]
I used to use `counsel-kmacro` https://github.com/abo-abo/swiper/blob/5ff652c3020c5c510011018ca6805a4d65339e32/counsel.el#L5611 before which shows the corresponding `key`. Though I understand very basic elisp so far.
I could not find anything stored in evil registers or macro variables. 
I use registers for storing strings to paste, to mark positions (`evil-goto-mark-line`, `evil-collection-consult-mark`), and for `kmacro`.

**Comment by minad** [comment]
That's odd. I don't see anything in the counsel code. Could you please show me two screenshots side by side how it looks for you with counsel and consult?

**Comment by minad** [comment]
Okay. I'd still be happy to support this if we come up with a working solution as mentioned in https://github.com/minad/consult/issues/561#issuecomment-1108293397.

**Comment by oantolin** [comment]
I'd suggest spying on the user while they bind kmacros to keys: advise `kmacro-bind-to-key` to store the key binding in hashtable keyed by kmacro. You could do the same for names by advising `kmacro-name-last-macro` too. If you don't want to it unconditionally, you could do it in a global minor mode called something like  `consult-kmacro-store-info-mode` .

**Comment by minad** [comment]
@oantolin In principle I would agree, but it seems like a disproportionate effort only to make the key annotation available.

**Comment by oantolin** [comment]
Yes, it does. 😄

**Comment by okamsn** [comment]
> consult-kmacro was created by @okamsn, maybe he knows a solution?

I'm not familiar with how Evil stores its macros. I'll try to check in a few days.

For Emacs general, it looks like keyboard macros might use the new "open closures" in Emacs 29 ([here](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=52d5771e0a803f57b8cdd7675bf15f2f9b946039)). Maybe a property for the bound keys could be added?

**Comment by okamsn** [comment]
@anupam312nwd 

> Will it be possible to show the key in `consult-kmacro` at the beginning similar to the one appear in `consult-register`? Thanks!

I'm still unsure about this given the reasons stated by others, but

> I often define many macros on the fly and use `evil-execute-macro` to use it. But after a while, I forget which `macro` is bound with which `key` in the register.

it turns out Evil just stores its macro in the normal Emacs registers.  `consult-register` can display those that are recorded as a string of characters, but displays the string "Garbage:" for those stored as vectors (same as Emacs). However, Evil has the command `evil-show-registers`, which correctly shows the keyboard macros that were stored as vectors (such as those using `<escape>`).  **Therefore, for now at least, the answer is to just use `evil-show-registers`.**


Evil works differently from how Emacs stores keyboard macros in registers, which `evil-show-registers` does not support. I don't know why they chose that path, and don't often bind the macros to registers in Evil. I tend to just use the kmacro ring and `consult-kmacro`.

The command `evil-show-registers` uses `key-description` to correctly show mouse events, which `format-kbd-macro` skips over. I'm not sure why there's this difference, since `key-description` seems to work on the values stored in `kmacro-ring`.  Just doing the below seems to make it work for mouse events:

``` elisp
;; Old (from `kmacro.el.gz'):
(cl-defmethod register-val-describe ((data kmacro-register) _verbose)
  (princ (format "a keyboard macro:\n   %s"
		 (format-kbd-macro (kmacro-register-macro data)))))

;; New:
(cl-defmethod register-val-describe ((data kmacro-register) _verbose)
  (princ (format "a keyboard macro:\n   %s"
		 (key-description (kmacro-register-macro data)))))
```

I've asked about this upstream.

Evil's keyboard macros seem to be stored in the registers as either strings or vectors, so I'm not sure if there is anything to distinguish an Evil kmacro from a string to insert in `consult-register` or equivalent. One could make a command for Consult based on what `evil-show-registers` does, but I don't know how useful that would be, given the apparent disagreement of how things are stored in the registers.

**Comment by anupam312nwd** [comment]
Thanks a lot for investigating the matter. `evil-show-registers` looks like an option to check for corresponding macros. I have bound it on a keybinding. 
I almost never use the mouse while using emacs. But it can be useful for other readers.

**Comment by okamsn** [comment]
Update:
- Keyboard macros seen in `view-register` are now formatted with `key-description` upstream, so mouse events are now displayed correctly. See https://github.com/emacs-mirror/emacs/commit/a4e5fdf97582003760f6818fd6266e537d2fc207.
- I've asked about why Evil does it differently in https://github.com/emacs-evil/evil/issues/1620. Hopefully the two can be unified.
