### ISSUE TITLE
consult-mark doesn't jump to correct position

### ISSUE THREAD

**Issue by ilupin** [minad/consult#562]
Recipe:
1. emacs -Q
2. turn on `vertico-mode`
3. open a file and press `C-SPC` to set a mark in some position
4. move the point to other position using C-v or mouse
5. `M-x consult-mark`, then vertico-mode shows the mark as the only candidate. However, pressing RET doesn't jump to the mark

I'm using GNU Emacs 29.0.50.

**Comment by minad** [comment]
I cannot reproduce this on Emacs 28 with emacs -Q but maybe I did something wrong. Is this bug a regression on Emacs 29, can you please check? Do you keep an Emacs 28 install around? Unfortunately I cannot take Emacs 29 bug reports for my packages at this point since there is a lot of churn upstream and unintended breakage currently. Many regressions just vanish after some time after someone reported regressions. But I will switch to Emacs 29 not too long in the future, since I am eager to try out the recent performance improvements added there.

**Comment by ilupin** [comment]
Hi, I have tested on emacs 28 and the problem exists too. Please try the following steps:

1. `emacs -Q -L <path_to_consult>`
2. eval the following code in the scratch buffer:
```
    (require 'consult)
    (global-set-key "\M-m" 'consult-mark)
```
3. run the following commands
```
 C-h n			       ;; view-emacs-news
 C-SPC			       ;; set-mark-command
 C-SPC			       ;; set-mark-command
 C-v			       ;; scroll-up-command
 M-m			       ;; consult-mark
 <return>		       ;; minibuffer-complete-and-exit
```

This screenshot is captured after pressing M-m. The live preview correctly shows the location of the previous mark set by C-SPC.
![image](https://user-images.githubusercontent.com/5555871/165665773-90bafc2f-4fad-4bf9-bfe2-17b03508a8f6.png)

This screenshot shows the final position after pressing RET, which is the same location after C-v.
![image](https://user-images.githubusercontent.com/5555871/165667115-72e1a070-9814-4670-839a-ab9ee19d573c.png)

**Comment by minad** [comment]
I can reproduce it now. But there is a crucial difference - you didn't turn on vertico-mode.

**Comment by minad** [comment]
Okay, I identified one problem. The function `consult--jump` which performs the final jump calls `push-mark` and this can have side effects on the markers. Hopefully this fixes your problem. Please give it a check.

However there is another issue in your reproducible. If you press RET in an empty default completion minibuffer (`minibuffer-complete-and-exit`) returns the empty string. This is called the "null completion". In this case `consult-mark` does not perform a jump, such that you end up with your original position. I consider the concept of the null completion a design mistake of `completing-read`. You can even "complete" the empty string if REQUIRE-MATCH=t. If you instead invoke `minibuffer-force-complete-and-exit` then you will jump to the first candidate. Therefore this is not a bug in `consult-mark`. However there is a small flaw in Consult preview, which still previews the first candidate, despite the possibility of returning with the null completion. `embark-act` has the same problem, it also acts on the first candidate if the minibuffer is empty. The problem is that we cannot tell if the user is going to exit with `minibuffer-complete-and-exit` in this case (the meaningless null completion) or with `minibuffer-force-complete-and-exit` (more reasonable). Consult assumes that you do not want the null completion and therefore previews the first candidate.

**Comment by oantolin** [comment]
I think the call to `push-mark` mutating the `mark-marker` was probably the bigger problem, because I can also reproduce the issue with Vertico, even though under Vertico `completing-read` returns the first candidate rather than the empty string.

**Comment by oantolin** [comment]
But, yes either problem alone can cause this issue:

- Before your fix I could reproduce with both Vertico and with default completion.
- With that new definition of `consult--jump` I cannot reproduce with Vertico but still can with default completion.

**Comment by minad** [comment]
> With that new definition of consult--jump I cannot reproduce with Vertico but still can with default completion.

Why? Do you see the null completion? This is not a bug.

**Comment by minad** [comment]
> even though under Vertico completing-read returns the first candidate rather than the empty string.

Vertico is a bit more strict. It assumes that you don't want the null completion if REQUIRE-MATCH=t. But you can still get it via M-RET.

**Comment by oantolin** [comment]
Yes, I just meant the null completion. I called it "reproducing" even though it's not technically a bug, because the effect is exactly the same as the push-mark bug's effect under Vertico!

**Comment by minad** [comment]
Good. Thank you for checking! The null completion is definitely confusing in this case. When I tried to reproduce this initially I assume that I pushed a few markers and jumping always worked as intended and I didn't hit the push-mark mutation. The mutation of the mark-marker is reasonable but the mutation of the existing mark ring markers seems like a problematic premature optimization. Maybe the mark ring wants to preserve market object identity for some weird reason.

**Comment by minad** [comment]
@oantolin Do you think we should modify the target finders such that the handle the null completion specially. For empty minibuffer one would have to return `(or (car-safe minibuffer-default) minibuffer-default)`. This would affect consult--default-completion-mb-candidate and embark-target-top-completion. However this is questionable since as I mentioned it all depends on if the user will complete or force complete and exit.
