### ISSUE TITLE
Similar setting like `consult-line-start-from-top` for `consult-ripgrep`

### ISSUE THREAD

**Issue by lynnux** [minad/consult#573]
I often use `vertico-repeat` to resume search, if `(setq consult-line-start-from-top nil)`, this will work perfect for `consult-line`, because the first line in result is the current line cursor in.
But invoke `vertico-repeat` to call `consult-ripgrep` this won't work, it seems always go to the first line in matching result.

**Comment by minad** [comment]
I don't understand this issue. What is it supposed to do and how is it supposed to work based on ripgrep? Please describe your feature request in detail.

**Comment by minad** [comment]
After rereading your issue - it seems that the problem is actually `vertico-repeat` which doesn't jump to the selected match (and there is no relation to `consult-line-start-from-top`). This is a limitation of `vertico-repeat` in combination with `consult-ripgrep`, since `consult-ripgrep` is an *asynchronous* command. The matches come in *asynchronously* and as such we cannot restore the position. You may want to use `embark-collect` or `embark-export` from `consult-ripgrep` instead. This is the recommended workflow if you want to keep track of multiple matches.

**Comment by lynnux** [comment]
Ok, I'm learning embark now, thanks for detail explanation!
