### ISSUE TITLE
consult--source-recent-file couldn't filter opened file which is symlinked in recentf-mode

### ISSUE THREAD

**Issue by liuyinz** [minad/consult#577]
1. open a symlinked file.
2. call `consult-buffer`
3. in "File" section the symlink path is not removed.
4. workaround, filtered by `lambda` with `(file-truename x)` first.
```elisp
(defvar consult--source-recent-file
  `(:name     "File"
    :narrow   ?f
    :category file
    :face     consult-file
    :history  file-name-history
    :state    ,#'consult--file-state
    :new      ,#'consult--file-action
    :enabled  ,(lambda () recentf-mode)
    :items
    ,(lambda ()
       (let ((ht (consult--buffer-file-hash)))
         (mapcar #'abbreviate-file-name
                 (seq-remove (lambda (x) (gethash (file-truename x) ht)) recentf-list)))))
  "Recent file candidate source for `consult-buffer'.")
```

**Comment by minad** [comment]
Unfortunately we cannot use any functions which access the file system in `consult-buffer` since then the command will get unpredictably slow if Tramp paths occur in the list. We can only rely on pure string manipulation. If you prefer the file path normalization with respect to symlinks you can replace the `:items` function in your user configuration.

For a precedent, where I made this mistake, see https://github.com/minad/consult/issues/258 and https://github.com/minad/consult/commit/6ced33ac555dc8852a3fc14811bb745fad19f3c7.

**Comment by liuyinz** [comment]
Got it, Thanks.
