### ISSUE TITLE
Question around character encoding

### ISSUE THREAD

**Issue by jojojames** [minad/consult#585]
Trying out consult-line and consult-buffer with https://github.com/jojojames/fussy

I end up getting candidate strings like so:

```
";; This buffer is for text that is not saved, and for Lisp evaluation.�"
```

which when passed through to the rust scoring backends, fail. Wondering if these are expected/where they're from/etc.

I added https://github.com/jojojames/fussy/commit/d5833ad6a26b946e9db79b138ec7f514d4b87afc to account for them but was hoping to get some clarity for these strings.

**Comment by minad** [comment]
consult-line and consult-buffer add tofu characters to disambiguate duplicate candidates. See consult--tofu-char. Originally I used valid Unicode characters in the private plane b but switched to invalid characters later since Emacs allows those too. Your native completion style should be able to handle all Emacs code points.

**Comment by jojojames** [comment]
Thanks sounds good, also agree with the conclusion.

**Comment by minad** [comment]
See also https://github.com/minad/consult/commit/19aa0d03025de2f4afaaca4d3ac5e4e7c1f68608.
