### ISSUE TITLE
Multiple directory search using consult-grep/ripgrep

### ISSUE THREAD

**Issue by mclearc** [minad/consult#597]
Would it be possible for consult-grep/ripgrep to take multiple dirs as input (as can be done on the command line calling grep or ripgrep) rather than a single one? Apologies if this has already been answered elsewhere. This has come up for a notes search function I've written -- see https://github.com/mclear-tools/consult-notes/issues/7. Thanks!

**Comment by minad** [comment]
When I enter `#input -- /dir1 /dir2` it works for me, but dir1 and dir2 are searched in addition to the default directory. In order to avoid this you could write:

~~~ elisp
(defun consult-ripgrep-multiple-directories ()
  (interactive)
  (let ((consult-ripgrep-args
         (string-replace
          "."
          "/dir1/ /dir2/" ;; Absolute paths!
          consult-ripgrep-args)))
    (consult-ripgrep)))
~~~

Note that the directories must be absolute (`~/something` will not work) since we call `rg` and `grep` directly. Maybe that's a mistake and we should instead pass everything through the shell first for argument expansion? I hope the solution above is good enough for your use case. We could also add support for multiple directories to `consult-ripgrep` etc directly, but it is not really a natural extension. Currently `consult-ripgrep` changes the `default-directory` and runs `rg` in that directory.
