### ISSUE TITLE
consult-find doesn't find anything with windows/mingw32

### ISSUE THREAD

**Issue by ambihelical** [minad/consult#601]
Windows 10 Enterprise/21H2
consult elpa version 20220622.1544  
gnu find from mingw32

When consult-find is run in any directory, nothing is matched.  For example when default-directory is what passes for my home directory with mingw32, "c:/Users/ericb/", and then running consult-find, the prompt shows the following:
`!/0   Find!`
Typing terms that should match files there the ! turns briefly to *, and then returns to !

The same configuration is working correctly with Linux.

**Comment by minad** [comment]
You can check the `_*consult-async*` buffer (leading space) for error messages. Then you can take a look at `consult-find-args`. Maybe this variable needs a modification for Windows? But besides that I have no idea and I cannot help you since I don't use Windows and Emacs generally doesn't work well there since many Unix assumptions don't hold. If there is something which needs to be done on the side of Consult, I'd be happy to hear. Unfortunately nobody stepped up contributing Windows support so far.

**Comment by ambihelical** [comment]
A bit early to close I think!  I usually open issues first, and if I have time and ability I'll contribute a fix if the author doesn't have a faster one. I think this one can be fixed easily now that I know about the async buffer. 

Below is what the async buffer has.  It looks like -wholename argument is getting expanded by the shell and barfing on file names with spaces which windows has many of.  I tried putting single quotes around it in consult-find-args, and that seems to work on linux and windows.  I can submit a PR for this as long as I don't need to sign a contribution agreement, which I don't plan to get.  

It doesn't look like this gets expanded with linux, as I made a directory with a space in it, and it handled it fine. Perhaps one of those assumptions that don't hold maybe, but single quotes seem to work as far as I can tell with linux as well. Alternatively, a different default can be made for windows. 

```
consult--async-process started ("find" "." "-not" "(" "-wholename" "*/.*" "-prune" ")" "-iregex" ".*foo.*")
consult--async-process sentinel: event=exited abnormally with code 1 lines=0
>>>>> stderr >>>>>
/usr/bin/find: paths must precede expression: `3D Objects/..'
/usr/bin/find: possible unquoted pattern after predicate `-wholename'?
<<<<< stderr <<<<<
```

**Comment by minad** [comment]
> A bit early to close I think!

No, it is not. I cannot support Windows and I cannot sacrifice time for it. If you are interested in figuring out Windows support, it is welcome though. I kept the last Windows issues open for half a year or longer with explicit requests for help without clear progress.

> I tried putting single quotes around it in consult-find-args, and that seems to work on linux and windows.

This sounds familiar. I believe there was a similar issue before which was fixable by additional quoting. Please look at the other stale Windows issues. The problem is only this - we call find/grep directly and not through a shell. So if Emacs on Windows uses a shell it is an Emacs bug.

> Alternatively, a different default can be made for windows.

My preferred solution is this:

1. One should report the bug upstream, since something is off if arguments are processed differently on Windows and Unices. There is also an encoding problem with the argument passing.
2. In the meantime you can override the configuration in your init.el for Windows. I think the problem is also that there are different builds of Emacs on Windows and we may not rely on the existence of grep/find.

**Comment by ambihelical** [comment]
I can provide some windows support, but I'm no expert.  I'm forced to use windows for work, and don't want to give up Emacs so I'm motivated to having things work.  I just started using vertico/consult (from ivy/counsel) less than 1 week ago, and 1 day on windows so far, so I'm still coming up to speed with it, so I didn't know about the async buffer.  I'll look at the stale issues for windows, but like you I'm not likely to spend time on things that don't affect me. 

One thing that isn't clear from your response and I couldn't find anything about it in the readme, do you require gnu copyright assignment?  I've been too lazy to do the paperwork, and aren't likely to do so just to contribute code.

**Comment by minad** [comment]
> I'll look at the stale issues for windows, but like you I'm not likely to spend time on things that don't affect me.

The Windows issues are all related (encoding, argument passing), so you may be affected by them. The only affected commands are the async grep and find commands. My problem with Windows issues is not only that I am not affected by them, but also that only few people use Emacs (test and contribute) and the issues are actually on a deeper layer.

1. Multiple incompatible Emacs ports on Windows exist (Cygwin, Mingw, ...)
2. Emacs on Windows is broken
3. Windows is broken

> One thing that isn't clear from your response and I couldn't find anything about it in the readme, do you require gnu copyright assignment?

Then you didn't look closely enough at the readme. Searching for copyright should reveal that yes, copyright assignment is required. However I doubt that it matters much in this case. The bulk work regarding full Windows support is to identify the issues in Consult and identify the underlying reasons in Emacs, report Emacs bugs if the behavior is not consistent with Unix, even if it should be. And only then finally figure out possible workarounds.

However my stance on workarounds is relatively rigorous - I only accept workarounds if at the same time some steps are taken to fix the actual underlying problem.

> I've been too lazy to do the paperwork, and aren't likely to do so just to contribute code.

If it is only laziness your motivation may get up if you have an actual workaround at hand. But maybe the copyright assignment is already a sufficient reason to not even try.

**Comment by ambihelical** [comment]
Just for future reference should someone want to fix this (including myself), it turns out that msys and cygwin executables glob their arguments for compatibility with running from windows command line which expects executables to do this.  This is what is causing the issue.

This magit PR is what was done for magit:

https://github.com/magit/magit/pull/2281

I believe this is the root cause for #317, at least the escaping part.

**Comment by catweazle9** [comment]
For what it's worth, the Windows Everything program `es.exe` accepts an argument `-path .` to search for files only from the current directory. The following (which builds on the `Everything` example in the FAQ) seems to provide similar functionality (I guess) to `consult-find` on other platforms:

```
(defun consult-everything-current-dir ()
  "Search with `everything' under the current directory for files matching input regexp given INITIAL input."
  (interactive)
  (let ((consult-everything-args (concat "es -path .")))
    (consult-everything)))

```

FAQ: https://github.com/minad/consult/wiki
