### ISSUE TITLE
consult-find: cannot find files when there are other subdirs under current dir

### ISSUE THREAD

**Issue by ZeaLot4J** [minad/consult#611]
Here comes a problem, I invoke consult-find under ~/.emacs.d/elpa/consult-20220701.1352/, it works as expected undoubtedly, there are no even subdirs in this case.

![image](https://user-images.githubusercontent.com/24864820/178639032-81fa0062-2d61-496c-8160-02efd36d7d55.png)

However, after I create a empty tmp directory, it turns out no matching results.
![image](https://user-images.githubusercontent.com/24864820/178639641-ce3fea03-7ba8-4779-a1f6-5f82668e8f1b.png)

Then remove the tmp directory, it works again.
Same issue happens under a project, it seems consult-find only works under leaf node dir?
Usually I prefer "git ls-files" to "find" in projects, but I'd like give a try to consult-dir which uses consult-find under the hood.

`OS`: windows
`emacs version`: GNU Emacs 28.1 (build 2, x86_64-w64-mingw32) of 2022-04-22
`consult-find-args`: "find . -not ( -wholename */.* -prune )"
`(require 'package)
(setq package-archives
'(("melpa" . "https://melpa.org/packages/")
("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(package-refresh-contents)
(package-install 'consult)
(package-install 'vertico)

(vertico-mode)

(require 'consult)
`

I think this can be easily reproduced under the directory ~/.emacs.d/elpa/consult-xxxxx/

**Comment by ZeaLot4J** [comment]
There is nothing wrong with consult-find in Linux.

**Comment by minad** [comment]
In order to investigate this you can look into the `*consult-async*` buffer for error messages. Also did you try the find command on the command line? What is different in the case with the subdirectory?

I close this issue, since I cannot reasonably support Windows, which I haven't used in years. Windows is broken and Emacs on Windows adds further issues on top. Anyway, if you figure out the underlying reason for the issue and a possible fix I am happy to merge it. Thanks!

**Comment by minad** [comment]
See also https://github.com/minad/consult/issues?q=label%3Awindows for other Windows-related reports. Unfortunately there are also problems with encoding and command line argument escaping.

**Comment by ZeaLot4J** [comment]
> It could be that your issue is a duplicate of #601. A possible fix was mentioned in that issue.
Nice. now I've got a possible fix:
`(setq consult-find-args "find . -not ( -path \\*/.\\* -prune )")`
which works well both in windows and linux, check it out please.

**Comment by minad** [comment]
Well, this is a hack, not a proper fix since `consult--find-builder` generates arguments dynamically which would also require escaping. As I've understood in #601 it would be better to just disable the globbing by setting a MSYS or CYGWIN environment variable, such that Windows would behave in the same way as Unix systems. If you are interested you could try to port that fix from Magit to Consult.
