### ISSUE TITLE
Error when running minibuffer-complete-history while in consult-* (with vertico)

### ISSUE THREAD

**Issue by actondev** [minad/consult#613]
I'm getting `Error in post-command-hook (vertico--exhibit): (error "Invalid completion style consult--split")`
when running `minibuffer-complete-history` while being in the `consult-ripgrep`.  This also happens with
- consult-grep
- consult-find

Doesn't happen with
- consult-line
- consult-imenu
- consult-buffer

**Comment by minad** [comment]
Yes, this is expected. consult-grep has to define its own completion style (and override the existing style) because of its asynchronous filtering. It is not yet obvious to me how to fix this. For now you can use consult-history instead for history completion in the minibuffer.

~~~ elisp
(define-key consult-async-map [remap minibuffer-complete-history] 'consult-history)
~~~

**Comment by minad** [comment]
For now I've chosen the cheap solution to just remap the commands. In the future we may find a better solution, but I am not yet concerned much with Emacs 29 as long as I haven't switched.

**Comment by actondev** [comment]
Thanks! The "cheap" solution is fine :) 
Had not noticed that minibuffer-complete-history was only present in 29, I was just playing with vertico/consult combo (moving from helm), & was trying out different things when I stumbled upon this.
