### ISSUE TITLE
Use grep-find-ignored-files in consult-grep

### ISSUE THREAD

**Issue by theottm** [minad/consult#616]
Would it be possible to respect `grep-find-ignored-files` also when using `consult-grep`? Or is there a simple way to ignore them manually? It seems `M-x consul-grep #query -- [^~]` is not working for me.

**Comment by aagon** [comment]
Hello Mr. Mendler.

First of all, thanks for this wonderful package.

Regarding the file and directory exclusions that should be respected by `consult-grep`, but also by `consult-ripgrep`, `consult-git-grep` and `consult-find`, I thought that it might be a good idea to use `project-ignores`(if it is bound of course) as well.

Similarly to what you did in 7c5a98a6abe5a42a9005d8c83a7ebef849e33e63, we could add in the respective command builders as exclusions all the files and directories present in the list returned by `project-ignores`. Some exclusions would probably be redundant with the ones already provided by `grep-find-ignored-files` and `grep-find-ignored-directories` or the ones already implemented by the external commands themselves, but that's not a problem.

Hence, for the current `project.el` backend, any vcs directory would be excluded (and not just `.git`, that I see you had to hardcode before 7c5a98a6abe5a42a9005d8c83a7ebef849e33e63) without us having to worry about it (let the `project-backend` worry about all that).

On top of that, if a new backend were to be defined, we would automatically inherit from all its defined exclusions.

And if you think that this amount to hardcoding too much "project logic" in the `consult-{grep,ripgrep,find,git-grep}` commands, we could always conditionate the respect of `project-ignores` to a user option.

I could try to provide a PR, if you are interested. I think it is a good step in the direction of further integration with `project.el`, which seems to be one of the directions you have already chosen for this package.

Mit freundlichen Grüssen,

Aymeric Agon-Rambosson

**Comment by minad** [comment]
Hey,

I am not sure if we should also respect project-ignores. If we want that indeed, we should probably introduce a separate configuration variable which can be set either to the grep or the project ignores. Did you note that grep-find-ignore-directories is set from vc? So maybe project wouldn't add benefits on top?

Then there is the question if the other commands should respect the variables too. For ripgrep/git-grep I don't think so, since these tools come with their own ignore mechanism. Adding it for consult-find would be a good addition though, maybe only grep-find-ignore-directories?

Overall I don't have a coherent design in mind here. Proposals, prototypes and PRs are welcome!

**Comment by aagon** [comment]
> If we want that indeed, we should probably introduce a separate configuration variable which can be set either to the grep or the project ignores to avoid duplicates.

I'm not sure why the duplicates would be a problem. We have `grep-find-ignored-files` and `grep-find-ignored-directories` who provide project-agnostic exclusions, and `project-ignores` that are most certainly going to have some overlap with the former, but could also provide extra project-specific exclusions. If we could be sure that `project-ignores` is always bound and always returns a superset of the content of the former two, I wouldn't mind getting rid of the former two. But I don't think we can assume that.

> Did you notice that grep-find-ignore-directories is set from vc?

Indeed I did. What matters is not only thoses static directories in `vc-directory-exclusion-list`, but also dynamic directories and files added to, say, `.gitignore` (or, and that's my point, **any other equivalent**, whether in the VC backend, or any other one).

> For ripgrep/git-grep I don't think so, since these tools come with their own reasonable and efficient ignore mechanism.

The purpose is to add extra, project-specific ignore patterns to an indeed already reasonable and efficient ignore mechanism in the general case, and taking into account project-specific exclusions that might not be specified in a `.gitignore`. The point here is not performance, its practicality : we might just want to exclude even more noise than what `rg(1)` and `git-grep(1)` already do, without having to manually type the exclusions in the minibuffer.

> Adding it for consult-find would be a good addition though, maybe only grep-find-ignore-directories?

As it turns out, this is maybe the least important addition, since `project-find-file` already takes into account `project-ignores` : `project-find-file` with `vertico` and `consult-find` would provide more or less the same results and fill the same functionality. However, depending on the `project.el` backend, `consult-find` would provide a quicker alternative since it relies on `find(1)` and not some internal elisp implementation.

> Proposals, prototypes and PRs are welcome!

This snippet works perfectly for `consult-grep` : 

```elisp
  (defcustom my/consult-use-project-ignores t
    "Whether to add `project-ignores' to exclusions"
    :type 'boolean
    :group 'consult)

  (defun my/consult--grep-builder (input)
    "Build command line given INPUT."
    (unless (boundp 'grep-find-ignored-files) (require 'grep))
    (pcase-let* ((cmd (append (split-string-and-unquote consult-grep-args)
			      (mapcar (lambda (s) (concat "--exclude=" s))
				      (bound-and-true-p grep-find-ignored-files))
			      (mapcar (lambda (s) (concat "--exclude-dir=" s))
				      (bound-and-true-p grep-find-ignored-directories))
			      (when (and
				     my/consult-use-project-ignores
				     (fboundp 'project-ignores))
				(mapcar (lambda (s) (if (directory-name-p s)
							(concat "--exclude-dir=" s)
						      (concat "--exclude=" s)))
					(project-ignores (project-current) default-directory)))
			      ))
		 (`(,arg . ,opts) (consult--command-split input))
		 (flags (append cmd opts))
		 (ignore-case (or (member "-i" flags) (member "--ignore-case" flags))))
      (if (or (member "-F" flags) (member "--fixed-strings" flags))
	  `(:command (,@cmd "-e" ,arg ,@opts) :highlight
		     ,(apply-partially #'consult--highlight-regexps
				       (list (regexp-quote arg)) ignore-case))
	(pcase-let* ((type (or consult--grep-regexp-type
			       (setq consult--grep-regexp-type
				     (if (consult--grep-lookahead-p (car cmd) "-P") 'pcre 'extended))))
		     (`(,re . ,hl) (funcall consult--regexp-compiler arg type ignore-case)))
	  (when re
	    `(:command
	      (,@cmd
	       ,(if (eq type 'pcre) "-P" "-E") ;; perl or extended
	       "-e" ,(consult--join-regexps re type)
	       ,@opts)
	      :highlight ,hl))))))
```
I am going to adapt this snippet to `consult-ripgrep`, `consult-git-grep` and `consult-find`, and eventually test it on another `project.el` backend that I am developing in the meantime.

Tell me what you think !

**Comment by aagon** [comment]
Update : 

This does not work, I don't get why : 

```elisp
  (defun my/consult--ripgrep-builder (input)
    "Build command line given INPUT."
    (pcase-let* ((cmd (append (split-string-and-unquote consult-ripgrep-args)
			      (when (and
				     my/consult-use-project-ignores
				     (fboundp 'project-ignores))
				(mapcar (lambda (s) (if (directory-name-p s)
							(concat "--glob='!" s "**'")
						      (concat "--glob='!" s "'")))
					(project-ignores (project-current) (project-root (project-current))))))
		      (`(,arg . ,opts) (consult--command-split input))
		      (flags (append cmd opts))
		      (ignore-case (if (or (member "-S" flags) (member "--smart-case" flags))
				       (let (case-fold-search)
					 ;; Case insensitive if there are no uppercase letters
					 (not (string-match-p "[[:upper:]]" arg)))
				     (or (member "-i" flags) (member "--ignore-case" flags)))))
		 (message "%s %s" flags arg)
		 (if (or (member "-F" flags) (member "--fixed-strings" flags))
		     `(:command (,@cmd "-e" ,arg ,@opts) :highlight
				,(apply-partially #'consult--highlight-regexps
						  (list (regexp-quote arg)) ignore-case))
		   (pcase-let* ((type (or consult--ripgrep-regexp-type
					  (setq consult--ripgrep-regexp-type
						(if (consult--grep-lookahead-p (car cmd) "-P") 'pcre 'extended))))
				(`(,re . ,hl) (funcall consult--regexp-compiler arg type ignore-case)))
		     (when re
		       `(:command
			 (,@cmd ,@(and (eq type 'pcre) '("-P"))
				"-e" ,(consult--join-regexps re type)
				,@opts)
			 :highlight ,hl)))))))
```

But in the case of `rg(1)` it is possible to specify project-specific exclusions in a file like `.rgignore` or `.ignore`, which is much simpler than building a complex command line.

Since `git-grep(1)` only works on git repos, `.gitignore` would be a way to specify project-specific exclusions, but that would require to add `--exclude-standard` to `consult-git-grep-args`.

**Comment by aagon** [comment]
> For consult-grep it still makes sense to offer an ignore mechanism since grep doesn't come with such a mechanism by default.

Ok, I agree. The argument applies for `find(1)` as well, I'd say.

> I think a better solution overall is to just make this configurable.

Would we want to make it configurable for `consult-ripgrep` and `consult-git-grep` also, for consistency's sake ?

```elisp
(setq consult-grep-args '("grep" (consult-generate-exclude-args) ...))
```
In this example, `consult-generate-exclude-args` would have to return a list of strings or a string ? The idea of `consult-grep-args` is to be a list of split strings, right, so that we can get rid of `split-string-and-unquote` in `consult--grep-builder` ? I'm not sure how to ensure that `consult-grep-args` is a flat list of strings, and not a list of strings and lists.

**Comment by minad** [comment]
I'd like to generalize this everywhere. We should replace all `split-string-and-unquote` calls in the builders with some `consult--build-arguments` call, which handles the improved `consult-*-args`. The args can either be a string in which case `split-string-and-unquote` is used or it could be a list of expressions which are evaluated. Each expressions must evaluate to a string or a list of strings.

**Comment by minad** [comment]
@aagon Is there still interest in pursuing that?

**Comment by aagon** [comment]
Sorry for my being inactive. I have a satisfactory implementation for my use case resembling the working snippet I put [there](https://github.com/minad/consult/issues/616#issuecomment-1193403083). I also understood why my other snippet did not work : the strings in the list cannot have spaces in them. So we need to make sure that the list returned by `consult--build-arguments` returns a list of correctly split strings, which is not the case now : 

```emacs-lisp
(consult--build-arguments '("foo" "bar" "foo bar" (concat "x" "y") (list "foo" "bar")))
```
returns 
```emacs-lisp
("foo" "bar" "foo bar" "xy" "foo" "bar")
```
while we would want it to return
```emacs-lisp
("foo" "bar" "foo" "bar" "xy" "foo" "bar")
```

Once this function is correct, we just have to use it instead of `split-string-and-unquote` in the builders, and change the type of the args variable to accept not only strings, but lists of strings and expressions as well.

I am not sure how to implement this function correctly, though. We would need to use `split-string-and-unquote` inside the list anyway, I think.

**Comment by minad** [comment]
@aagon What about this function? Strings are split and unquoted and other expressions are evaluated. The expressions must return a string or a list of strings, but these strings are not split further.

~~~ elisp
(defun consult--build-arguments (str)
  (mapcan (lambda (x)
            (if (stringp x)
                (split-string-and-unquote x)
              (ensure-list (eval x 'lexical))))
          (ensure-list str)))
~~~

**Comment by aagon** [comment]
I have offered a small proof of concept at #654, the discussion can continue there.
