### ISSUE TITLE
consult-ripgrep and multiline searches

### ISSUE THREAD

**Issue by mclearc** [minad/consult#629]
Ripgrep now supports multiline searches with the `--multiline` flag. See, e.g. [this post](https://til.hashrocket.com/posts/9zneks2cbv-multiline-matches-with-ripgrep-rg) for an overview. However I haven't been able to get this working by changing `consult-ripgrep-args`. This may be due to the way `consult--ripgrep-builder` works, though I confess I don't entirely understand that function. Any advice here would be very much appreciated. Thanks.

**Comment by minad** [comment]
I don't know. On my setup I have a pretty old rg version, so I won't be able to test this for a while. In its current form consult-ripgrep is fundamentally line-based. If you manage to configure rg to emit the matches in the usual grep output format (or the grep format with --context), then consult-ripgrep should just work. Otherwise it won't and then it is out of scope for now. Anyway feel free to experiment and open a PR if you come up with a solution.

**Comment by minad** [comment]
Regarding the builder - this function is just supposed to parse the input and produce a command line. You should be able to figure this out from the source. The bigger problem is the format of the output, which doesn't seem compatible with the usual grep format for --multiline. Then we need more intrusive changes.
