### ISSUE TITLE
Warning: ‘buffer-local-value’ is an obsolete generalized variable.

### ISSUE THREAD

**Issue by phikal** [minad/consult#636]
With a [recent change](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=915efbff98), `buffer-local-value` is obsoleted as a generalized variable.  This is currently being used as one in `consult-keep-lines`, where a `cl-letf` block sets the buffer-local value of `buffer-read-only` to nil.  It appears to me that it should just as well be possible to just bind `inhibit-read-only`, or am I mistaken?

**Comment by minad** [comment]
Thanks for the report. No, this won't be equivalent. I want to make only the current buffer read-write, not inhibit-read-only for the whole block, since this won't interact correctly with recursive minibuffers. I could instead use my consult--local-let macro which solves exactly the issue from 26624. https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26624 (Generalized variable `buffer-local-value' does't restore local flag).

However I disagree with the deprecation of the generalized variable, since it is perfectly well defined as long as the variable is already buffer local when being set. Then 26624 will not be an issue. 

For example in https://github.com/oantolin/embark/pull/534 and https://github.com/minad/vertico/pull/274 you replace perfectly valid code with equivalent longer code. I won't merge this for now. I will reconsider if the Emacs 29 release date comes closer. In the meantime I hope that the deprecation is taken back.

**Comment by minad** [comment]
To elaborate on 26624 - the "resolution" to deprecate the `buffer-local-value` gv is misguided, since the actual problem lies with `cl-letf`, which doesn't restore the local flag. The gv itself is well-defined. Anyway, take my take with a grain of salt since I didn't read through the long discussion on 26624.

**Comment by minad** [comment]
A different fix for 26624 would be to introduce a warning. This will preserve the possibility to use the gv, but will forbid the problematic side effect of changing the local flag.

~~~ elisp
(gv-define-setter buffer-local-value (val var buf)
  (macroexp-let2 nil v val
    `(with-current-buffer ,buf
       (unless (local-variable-p ,var)
         (warn "Variable is not yet local")
         (make-local-variable ,var))
       (set ,var ,v))))
~~~

**Comment by minad** [comment]
Oh my, I think the discussion in 26624 went a bit in the wrong direction. Michael who proposed the deprecation went on with this:

> I think we should spend significant efforts to avoid surprises. In this
case, if it means we should remove `alist-get' as well from the forms
supported by `cl-letf', then I think that's what we should do. The
documentation for `cl-letf' clearly states: "On exit, either normally or
because of a ‘throw’ or error, the PLACEs are set back to their original
values." If it can't do that for some place form, it shouldn't be allowed.

So we may now get a lobotomized version of gv since cl-letf has problems with it. gvs are useful beyond cl-letf. I hope that this gets reverted. Instead greater care should be taken to ensure that cl-letf is not used incorrectly. But I think in some cases the side effect of changing the local flag can even be tolerated. In cases where this is not possible one can use something like consult--local-let, which I introduced specifically for this purpose.
