### ISSUE TITLE
Dired: Previewed buffers reused

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#639]
In my [consult-jump-project](https://github.com/jdtsmith/consult-jump-project), I call `consult-buffer` again via the `:action`, when a project is selected. This seems to work fine, but I have recently discovered an issue with a dired enhancement mode called dirvish.  When a dirvish buffer which was previewed/opened by the 1st consult-buffer is selected by the 2nd (recursive) consult-buffer call, it is incompletely initialized and not functional.  Do the delay hooks still get called in such a situation?

**Comment by minad** [comment]
Indeed. I can reproduce this problem without Dirvish. Consult preview (incomplete buffer initialization) interferes with Dired session reuse.

In order to get directories into `consult-buffer` I use the following trick. 

~~~ elisp
(add-hook 'dired-mode-hook (lambda () (recentf-add-file default-directory)))
~~~

Then acting on the previewed buffer with `embark-dwim` reproduces the problematic issue, since the `Preview:...` buffer is then reused as normal Dired buffer, which should be prevented somehow by Consult. Maybe Dirvish also stumbles over this reuse by Dired.

-----

Anyway, since we are talking about Dirvish. I really like what the @alexluigit is doing there. However I am worried by the sheer amount of advices installed by this package, which will lead to many integration issues down the road. @alexluigit Is there a chance to reduce the amount of advices/hooks?

https://github.com/alexluigit/dirvish/blob/214ae1ac9366178a7338e991940aaab09fc06aa4/dirvish.el#L183-L208

**Comment by minad** [comment]
@jdtsmith Can you please check that https://github.com/minad/consult/commit/0d518df9f816a55604db23e5dc71f9208b2666ff solves the issue? Unfortunately I had to add a little bit of Dired special casing. But overall, the behavior for files and directories should be symmetric now.

**Comment by jdtsmith** [comment]
Thanks.  Unfortunately this does not fix the dirvish issue.  Perhaps this is because my recursive call to consult-buffer re-uses the preview-generated buffer (upon selecting it).

Dirvish is really good.  I do agree about the number of advices; hopefully they could be reduced over time.

**Comment by minad** [comment]
Regarding recursively invoked `consult-buffer` I found one more issue - https://github.com/minad/consult/commit/ad6cceb95eaa72f996bb8f0ccd6054f626d35f3b. Usually we don't want to offer the previewed buffers again for selection I think.

**Comment by jdtsmith** [comment]
> Usually we don't want to offer the previewed buffers again for selection 

In this case I actually do.  Is there a way to "bless" a preview-created buffer and complete its init (to make it a "real buffer"), as is done for recursive edits?

**Comment by minad** [comment]
> In this case I actually do. Is there a way to "bless" a preview-created buffer and complete its init (to make it a "real buffer"), as is done for recursive edits?

Hmm, this sounds conceptually wrong. Whatever the reason is, you shouldn't do this. Probably you are fighting the project switching APIs? Project switching in project.el usually uses the MAYBE-PROMPT argument and happens the other way round than what you are doing?

Anyway, the buffer upgrade happens here. I won't expose any of this as part of the API, since this part of the code is brittle and may change. Preview is the most delicate part of Consult.

https://github.com/minad/consult/blob/ad6cceb95eaa72f996bb8f0ccd6054f626d35f3b/consult.el#L1171-L1192

**Comment by minad** [comment]
We could upgrade the previewed buffers when entering a recursive edit, similar to when the window configuration changes. But I assume that in most recursive editing scenarios you don't actually want the upgrade to happen, since this would also interfere with Embark and other use cases. Upgrading buffers is not free. We initialize them fully which is costly and they will also stay around afterwards, which will be very annoying.

**Comment by jdtsmith** [comment]
> Whatever the reason is, you shouldn't do this

It was a happy accident honestly: I noticed in the 2nd call to consult-buffer that the previewed dired buffer consult opened was kept around.  This turned out to be very convenient, as sometimes, on project file/buffer selection, you decide you prefer the project dired buffer after all.  

I could explicitly visit the dired buffer before invoking the 2nd (recursive) consult-buffer, but then I have *two* buffers visiting the same directory, and dirvish gets quite unhappy (it seems to carry lots of global state).  Hence my interest in "blessing" the original previewed buffer.   I'll see what workarounds I can find.

**Comment by alexluigit** [comment]
> Anyway, since we are talking about Dirvish. I really like what the @alexluigit is doing there. However I am worried by the sheer amount of advices installed by this package, which will lead to many integration issues down the road. @alexluigit Is there a chance to reduce the amount of advices/hooks?
> 
> https://github.com/alexluigit/dirvish/blob/214ae1ac9366178a7338e991940aaab09fc06aa4/dirvish.el#L183-L208

Thanks. I'm not satisfied with some of these advices either.  In the very early versions I used the `dired-after-readin-hooks` to initialize the dirvish sessions, which turned out to be very error-prone. So I switched to this top-bottom approach, namely advising every dired entry command. Maybe advising `dired-noselect` is the way to go, I'll see if I can work it in.

**Comment by minad** [comment]
@alexluigit Okay, great! It sounds better to install only very few targeted advices instead of the shotgun method of advising everything at the top.
