### ISSUE TITLE
category file overrides :annotate, etc.

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#640]
I like to include `category file` in project directories offered by consult-buffer for selection.  This has good effects for embark, but it causes the custom-configured `:annotate` to be overridden by the standard marginalia file annotator.  How can I both categorize candidates as file, so that embark treats it as one, but also use my own custom `:annotate` function?

**Comment by minad** [comment]
That's a Marginalia issue really, since Marginalia overrides the annotations functions. You would want to configure Marginalia per command. You could use `vertico-multiform-mode` and locally rewrite `marginalia-annotator-registry`, such that the Marginalia file annotator is locally not taken into account. But all this sounds a bit like a hack. The better approach would be to introduce a `project` category, transform it to the `file` category in Embark and provide a separate `project` annotator in Marginalia. Didn't we already discuss this somewhere?

**Comment by jdtsmith** [comment]
We talked about a marginalia project category, yes.  I don't remember why that didn't progress.  It seems to me marginalia should respect any explicitly passed `:annotate` function.  Is there a reason it doesn't? Obviously if you just assign the `:category` it makes sense for it to do so.

**Comment by minad** [comment]
> I don't remember why that didn't progress. 

Because you didn't create a PR adding the project annotator :D

> It seems to me marginalia should respect any explicitly passed :annotate function. Is there a reason it doesn't? 

Marginalia supports multiple annotation functions, see for example the entry for the `command`  category:

~~~ elisp
(command marginalia-annotate-command marginalia-annotate-binding builtin none)
~~~ 

Marginalia just uses its own annotators by default, since these are richer than the annotators usually provided by Emacs.

**Comment by minad** [comment]
> Obviously if you just assign the :category it makes sense for it to do so.

Marginalia respects the original category due to its function `marginalia-classify-original-category`, but you could even override that, see `marginalia-classifiers`.

**Comment by jdtsmith** [comment]
>> I don't remember why that didn't progress.

> Because you didn't create a PR adding the project annotator :D

Hah.  I looked and was reminded why: to calculate the number of recentf files and open buffers a given project has, I make use of `consult--buffer-query` and its derivative `consult--buffer-file-hash`.  So this capability would need to be replicated in marginalia (unless it's already there?).

Also, for efficiency, I cache all project details once during a given consult-buffer call, and re-use those details for formatting the candidates.  As I understand it, marginalia has to treat each candidate in isolation.  Maybe skipping that wouldn't slow things down too much, especially since marginalia formats "just in time" and only a few candidates will be visible at a time.

**Comment by jdtsmith** [comment]
Have you ever considered separating out some of the basic functionality (buffer and file info, recent files, string functions, etc.) from across all your packages into a util library?   Then all the various packages could use it, but would not depend on each other.   

Coming up with a generic yet meaningful name would probably be the biggest challenge....

**Comment by minad** [comment]
No, I don't want to introduce such a utility library. I think it would be better to contribute functionality upstream.

**Comment by jdtsmith** [comment]
Any recommendations on how to efficiently provide the "recent files/open buffers" data for project-category  directories in marginalia?  It would be nice if e.g. `project-switch-project` also got in inherit this format.
