### ISSUE TITLE
consult-keep-lines: is it possible to preserve buttons/links and other overlays?

### ISSUE THREAD

**Issue by yangyingchao** [minad/consult#642]
It seems `consult-keep-lines` removes all the buttons. For example, executing
following code generates a buffer with buttons:

```
(with-current-buffer (get-buffer-create "test consult-keep-lines")
  (erase-buffer)
  (--dotimes 10
    (insert (format "    button-%d" it))
    (make-button (point-at-bol) (point-at-eol)
                 'action
                 (lambda (x)
                   (interactive)
                   (message "Button pushed: %d" it)))
    (insert "\n"))
  (pop-to-buffer (current-buffer)))
```

Then `M-x: consult-keep-lines` , all buttons are replaced with plain texts.

Is it possible to keep those buttons?  

Thanks

**Comment by minad** [comment]
The list of removed text properties is here:

https://github.com/minad/consult/blob/ad6cceb95eaa72f996bb8f0ccd6054f626d35f3b/consult.el#L1067

We cannot preserve overlays. Generally it is a not a good idea to execute consult-keep-lines on buffers with overlays or with rich properties, since we replace the buffer content.

You could also try consult-focus-lines, which hides lines but doesn't delete them.

**Comment by yangyingchao** [comment]
> The list of removed text properties is here:
> 
> https://github.com/minad/consult/blob/ad6cceb95eaa72f996bb8f0ccd6054f626d35f3b/consult.el#L1067-L1070
> 
> We cannot preserve overlays. Generally it is a not a good idea to execute consult-keep-lines on buffers with overlays or with rich properties, since we replace the buffer content.
> 
> You could also try consult-focus-lines, which hides lines but doesn't delete them.

i see. 

Thanks.
