### ISSUE TITLE
How to specify an initial filter without an initial input?

### ISSUE THREAD

**Issue by sje30** [minad/consult#646]
For context:

I'm trying to think of a way to use consult-ripgrep to search a directory of org files to look for matches in org headings.
If I specify my input as 

```
(consult-ripgrep "emacs#*")
```

then I find headers containing emacs.  (It will also generate false positives, e.g. 'emacs * ')

Is there a way of specifying an initial filter function whilst keeping the initial input empty?

```
(consult-ripgrep " #*")
```

kind of works, but then I have to C-b three times to get the cursor to the start of the query so that I can then type in the heading that I am looking for.

I have also experimented with 

```
(setq consult-async-min-input 5)
(consult-ripgrep nil "^\* ")
```
but I'm concerned this may generate a lot of hits, as the first regex (^\* ) will find a lot of headings.

Any ideas appreciated!

**Comment by sje30** [comment]
I am aware of consult-org-headings but from what I can tell, it searches only the current org-mode buffer, rather than a directory of org-mode files.

**Comment by minad** [comment]
The input string is transformed by consult--regexp-compiler to a list of regular expressions and a highlight function. Maybe you could let-bind that variable to a function which adds a "^\*" regular expression?

I wonder why your experiment with "^\* " initial input didn't work out? This should give the same result as long as you increase the minimal input to 6. The advantage is then that you can remove the initial input and also search for content in case you want to widen your search. 

In any case, I recommend to filter with ripgrep for headings instead of using post filtering (via #*), since post filtering puts the load on Emacs.

**Comment by sje30** [comment]
ok, thanks.  I'll try again with the first approach -- and see what you mean re: putting the load on ripgrep rather than Emacs.

thank you for a great package.
