### ISSUE TITLE
preview is automatically opening files in external application

### ISSUE THREAD

**Issue by fhansen42** [minad/consult#666]
In consult-buffer and consult-recent-file files with external extensions (see below code from my custom.el file regarding these extensions) are being automatically opened in external applications. I would prefer not to preview these files at all. Furthermore, after they are opened, I get the following error message: 

> Error in post-command-hook (consult--preview-post-command): (error "Book1.xlsx in external program")

Any ideas how to prevent this?

```
 '(openwith-associations
   '(("\\.pdf\\'" "explorer"
      (file))
     ("\\.xlsx\\'" "explorer"
      (file))
     ("\\.pptx\\'" "explorer"
      (file))
     ("\\.docx\\'" "explorer"
      (file))
```

**Comment by minad** [comment]
I think there are two possibilities to prevent openwith from running:

1. Configure consult-preview-excluded-files, maybe auto generate from the openwith-associations.
2. Configure consult-preview-variables, modify file-name-handler-alist or inhibit-file-name-handlers.

I haven't tested these solutions since I don't use openwith. I hope this helps!

**Comment by fhansen42** [comment]
`consult-preview-excluded-files` worked. thanks so much.
