### ISSUE TITLE
Feasibility of piping arbitrary sequences of consult commands together?

### ISSUE THREAD

**Issue by Hoboneer** [minad/consult#696]
Hi, I've been thinking of creating a consult command that allows one to use a sequence of consult commands together where the output from an earlier one limits the input to a later one---a pipeline.

My main use for this is to define a find/locate command followed by a grep on its output, but I'd like to be more general about it.

As for syntax, I'm thinking just one minibuffer prompt could be used and partition it by some predefined punctuation character, say `|`.  This character could also be used to force searching for patterns shorter than `consult-async-min-input` rather than double up: `pattern...#|pattern`.

For example, to use a locate followed by a hypothetical consult grep which can run on individual files:

```
#.py#projects work|TODO
```

This searches the locate database for `.py` files under `projects` and `work` (assuming such a folder structure exists) which contain `TODO`.

However, I wonder:

1. how feasible this is to implement technically;
2. how commands such as `consult-grep` and `consult-find` could be retrofitted to filter by input; and
3. whether this is in scope to include within the project or whether it should be an external package.

I'm willing to do this myself, but I'd like some pointers.  With regard to copyright assignment, I'm still in university and I remember only seeing that my university has policy regarding copyright about staff, not students.  I've seen [this FSF bulletin article](https://www.fsf.org/bulletin/2022/fall/copyright-assignment-with-the-fsf) though.

**Comment by minad** [comment]
The idea of the asynchronous Consult commands is that the processing happens outside Emacs in external processes. Composing Consult commands with pipes itself is not feasible, but you probably didn't mean that literally?

You can already use pipes by reconfiguring `consult-grep-args` or the `consult--grep-builder` such that it generates something like `sh -c 'cmd1 | cmd2'` etc. Then you should rewrite the command builder such that the input is distributed across the commands `sh -c 'cmd1 input1 | cmd2 input2'`, where input1 and input2 are for example split at a pipe. This should all be quite easy to do if you dig a bit into the command line builder.

What we will end up then with is a specialized command (e.g. find|grep) and not something which we can recompose freely at runtime. I have my doubts that this will be worth it. `consult-ripgrep` can already prefilter based on filename via `rg` command line options. Additionally, Consult provides the two-level filtering by splitting at the `#` separators, e.g. `#grep#filter`.

In any case, feel free to experiment! If something useful comes out, it may go to a separate package or to Consult itself if the command is sufficiently general and if there is sufficient general interest. 

(I close this since it is not about an issue in Consult, but an open-ended question. But please continue the discussion. Others may also be interested and chime in here.)
