### ISSUE TITLE
non-recursive consult-grep

### ISSUE THREAD

**Issue by vspinu** [minad/consult#718]
I very often want to search for files in the current directory without recursing into sub-directories. Given that `consult-ripgrep` does recurse and does it better than grep, the current default setup seems redundant. 

I expect this to be a common use case. Would it make sense to add a new command like `consult-grep-files`? Or simply document in the doc string of `consult-grep-args` of how to achieve that? 

I cannot figure it out for some reason, when I remove -r flag the grep does no longer work:

```el
(setq consult-grep-args
      '("grep" (consult--grep-exclude-args)
          "--null --line-buffered --color=never --ignore-case --line-number -I ."))
```

**Comment by minad** [comment]
I am not sure which option to pass to `grep`. If such an option exists, you can add it to `consult-grep-args`. Removing `-r` doesn't work since then you would have to pass a file as argument to `grep`. Maybe flat searches are also supported by `rg`? I don't think that this use case warrants its own command, since it should be easy enough to implement this in a user configuration. It is certainly not a common use case, since you are the first to request it.

**Comment by vspinu** [comment]
I gave up on `grep`. Indeed it looks like it's not possible without `sh -c` wrapping. I ended up wrapping `ripgrep` instead.

```el
(defun my-consult-ripgrep-1 (&optional dir initial)
    (interactive "P")
    (let ((consult-ripgrep-args
           (replace-regexp-in-string "\\.$" "--max-depth 1 --hidden --follow ." consult-ripgrep-args)))
      (consult--grep "Ripgrep-1" #'consult--ripgrep-builder dir initial)))
```

>  It is certainly not a common use case, since you are the first to request it. 

Frankly, I am surprised. Two most common scenarios for me are searching config files in the root of the project or user home directory, and searching code files in a module without recurring into sub-modles. I had this out of the box with helm and cannot now live without.

**Comment by minad** [comment]
> Frankly, I am surprised.

You are the first to ask for this. I think you are a special user. For me such a flat search doesn't matter so much since searching through entire trees is usually fast enough for me. Furthermore Consult offers the post-filtering functionality (see https://github.com/minad/consult#asynchronous-search). Then I often exclude results with `#initial search#!things !to !exclude`. You can also exclude paths `#initial search#!/some/path`.
