### ISSUE TITLE
exclude candidates for consult-xref based on file name

### ISSUE THREAD

**Issue by fgeller** [minad/consult#730]
hi! thanks for this amazing package 🙏 

is there a way to exclude candidates based on the file name? the typical use case i have, is browsing references and wanting to exclude matches in test files. for `consult-git-grep` i can do something like `funcName -- :!*test*` - is there an equivalent for `consult-xref`?

**Comment by minad** [comment]
Thanks! A filtering/exclusion mechanism on top of Xref feels a bit out of scope of Consult, since Consult is just a display mechanism with preview. It may be possible to configure the sources itself which generate `xref-locations` in order to achieve the desired filtering, since that would be the correct place to do this. If that is not possible you can implement your own exclusion mechanism by wrapping `consult-xref` or by advising `consult-xref--candidates`. Note that if you use Orderless you can write `!test` to filter out the literal string "test". Does this help you?

**Comment by fgeller** [comment]
yep, ideally it wouldn't be xref specific.
i don't think orderless' `!test` would help, as i'm trying to filter the "group" (is that the correct term?), not the candidates. e.g.:
<img width="893" alt="Screenshot 2023-01-29 at 11 08 56" src="https://user-images.githubusercontent.com/52790/215319263-bc470ad7-b4a9-44f1-bb17-d1976415a178.png">

i'm browsing the references for the symbol `install` but would like to filter/exclude based on the file name. e.g., `!mode` or `#!mode` to exclude the groups that match `mode` is what i'm looking for i believe :) briefly skimming, it seems that the group is stored in the property `consult--prefix-group` on the candidates, but from what i can see the `input` is interpreted by xref/earlier and not even passed to `consult-xref`. then i can only think of solutions where i filter without looking at the input, or do you see a way to keep the flexibility to filter "after the fact", ie browsing the results and later realizing that i can exclude a bunch of generated files or test files?

**Comment by minad** [comment]
Okay, I see. If you want to filter by group title, Orderless won't work. There is indeed no direct way to access the input.
