### ISSUE TITLE
Unable to use "consult-find" or "consult-locate"

### ISSUE THREAD

**Issue by deb75** [minad/consult#737]
Hi,

I recently switched to `consult` as a `helm` replacement.

I noticed that no `consult` command seems bounded to `C-x C-f`. Before it was `helm-find-files`.

I tried to use `consult-find`, I get this prompt
```
Find (~/): #
```

I assume, I have to enter a regexp or a file name in the "~/" directory.

But whatever I enter, nothing comes out : 
```
Find (~/): ! #nt
```
Only a red exclamation "!" appears, if I press enter, it answers "[Match Required]".
But what I have entered shoud match some files in that directory.

I checked that the `find` command is in the emacs exec-path.

However, I run emacs on windows10 and the `find` command is a msys2 command,
that is to say not a native one as opposed to mingw64 commands. It is possible that
something goes wrong in between.

Therefore, I would like to used "fd" which benefits from a native windows build and is
anyway believed to be faster than `find`. I first tried to modify the `consult-find-args` to make consult
use "fd", but it again does not work.

Could you help me to make `consult-find` work ? either with "find" or "fd" ?

Regards

**Comment by minad** [comment]
You asked before about `helm-find-files` on #6. As mentioned there, just use `C-x C-f`, which is the builtin `find-file` and which works perfectly well with Vertico/Marginalia/Embark.

Regarding `consult-find` and `consult-locate`- Emacs on Windows has some known issues, see #601. Maybe you will find something useful when you read through the issue tracker, see https://github.com/minad/consult/issues?q=label%3Awindows+is%3Aclosed. It would be great to make Consult run smoothly on all platforms (technically it should be possible), but this requires someone to do the testing and to eventually provide patches, since I am not a Windows user. It seems to me that maybe also upstream patches to Emacs itself are needed. Certainly the heterogeneity of msys/mingw/... does not help, but I am out of my depth regarding the actual differences.

**Comment by deb75** [comment]
Thanks for your answer.

Finally, `find-file` indeed works as you said, but only if I call it manually. Typing `C-x C-f` only opens the old builtin ui, not vertico.

**Comment by hmelman** [comment]
> Finally, `find-file` indeed works as you said, but only if I call it manually. Typing `C-x C-f` only opens the old builtin ui, not vertico.

You should use `C-h c` to check what command is bound to `C-x C-f`, it's probably not `find-file` if it behaves differently.

**Comment by deb75** [comment]
You were right,  `ido` steals thi shortcut, disabling `ido` solves the issue.

As for `consult-fd`, this works : 
```elisp
(defvar consult-fd-args nil "Shell command and arguments for fd.")

(setq consult-fd-args "fd.exe --color=never -i -H -E .git --regex --path-separator=/")

(defun consult--fd-builder (input)
  (pcase-let* ((cmd (split-string-and-unquote consult-fd-args))
               (`(,arg . ,opts) (consult--command-split input))
               (`(,re . ,hl) (funcall consult--regexp-compiler
                                      arg 'extended t)))
    (when re
      (list :command (append cmd
                             (list (consult--join-regexps re 'extended))
                             opts)
            :highlight hl))))


(defun consult-fd (&optional dir initial)
  (interactive "P")
  (let* ((prompt-dir (consult--directory-prompt "Fd" dir))
         (default-directory (cdr prompt-dir)))
    (find-file (consult--find (car prompt-dir) #'consult--fd-builder initial))))
```
I would just like to be able to choose the directory.
