### ISSUE TITLE
Subtle and mysterious consult bug affecting smooth pixel scrolling past images in org-mode

### ISSUE THREAD

**Issue by jdtsmith** [minad/consult#743]
This is going to sound a bit crazy.  I tend to show images in org mode, and I've long been frustrated that when smooth-scrolling is enabled (emacs-mac), scrolling the image upwards with the trackpad past an image causes the scroll position to "jump back down" again for small frame heights.  Here's how it looks:

https://user-images.githubusercontent.com/93749/218002381-a6e48f97-1e84-449d-8c70-a7109c4f4bd3.mov

I finally got frustrated enough to bisect my large init.el, and narrowed it down, unexpectedly, but unequivocally, to... consult.  Even a bare use-package of the latest consult from today causes the scrolling problem.  Without it, smooth scrolling past images doesn't skip a beat.

I've tried poking around the buffer to look at all the []-modification-hooks, window-[]-functions, and similar suspects, but I don't see consult doing anything untoward.  Possibly I missed something.

I'm hoping you might have an idea where to look.  Seriously strange.

**Comment by oantolin** [comment]
> Even a bare use-package of the latest consult from today causes the scrolling problem.

I bet it's compat, I doubt consult does anything _directly_ that could affect scrolling like that.

**Comment by minad** [comment]
Why Compat? Compat also doesn't do anything intrusive like this.

**Comment by minad** [comment]
My hands on this one are tied. I cannot debug this since I don't have a Mac. I am also not familiar with `smooth-scrolling` - what is this? Therefore I need you to be rigorous about the provided information, see https://github.com/minad/consult#bug-reports.

Please do the following steps:

1. Provide a minimal init.el and the Org file which does this.
2. Tell me the exact commands (or key presses) you invoke starting from emacs -Q. Any Consult commands?
3. Bisect Consult to find the commit which introduced the issue. It should be quick to do this, just clone the Consult git repository and put it on the load path. There have not been many changes to Consult since 0.31. It may have something to do with preview, see in particular the changes to `consult--invisible-open-temporarily` regarding the new org-fold-core. The only explanation is that Consult does something during which leads to some left overs, which are not cleaned up properly. See https://github.com/minad/consult/commit/497a5ebaf23db2c9d4630752e56ed76e4d70a5df.

**Comment by minad** [comment]
Regarding investigating any Consult left-overs - It should be possible to check each of them one by one. I count only 15 `add-hook` calls in Consult, plus `consult--append-local-post-command-hook`, plus `consult--minibuffer-with-setup-hook`. Both `consult--append-local-post-command-hook` and `consult--minibuffer-with-setup-hook` are potentially problematic since they work around issues with the hook mechanism in Emacs. This is were I would look first. Also make sure that you look at both the local and the global values of the variables. I hope this helps.

**Comment by minad** [comment]
See also https://github.com/minad/consult/commit/a9a619cb5519047accf0e42932db28ef1f95594b. Not sure if any of this helps.

**Comment by jdtsmith** [comment]
Yeah, apologies... I knew in advance that this is one where getting you a reproducer isn't really possible.  I'm happy to debug this myself, was just hoping to tap your mental networks for any clues or connections based on the behavior seen.  I will look more closely at the PCHs etc. I always forget about the `t` chaining through to the global value for example.

BTW, `mac-mouse-wheel-smooth-scroll=t`  is the [direct precursor to pixel scrolling](https://lists.gnu.org/archive/html/emacs-devel/2021-11/msg01574.html) in Emacs 29.  So not sure if this subtle jumping bug would affect Emacs 29 with pixel scrolling, but the code is inherited.  

You should distinguish between the default NS port and emacs-mac.  Basically emacs-mac is the port of Emacs that should by all rights be the released & supported one for MacOS.  It is the direct inheritance of the emacs Carbon port.  But various objections to its "extra capabilities" has prevented this, and I'm sure comments like "our stance is that a person who moves from GNU/Linux to MacOS is being self-destructively foolish" discourage the very talented developer Mitusharu Yamamoto from bringing his work into core.  The Emacs 22 survey shows that while GNU/Linux dominates among emacs users, MacOS is 2nd (and >2x Windows):

![image](https://user-images.githubusercontent.com/93749/218104290-8389228c-b990-4305-9c94-d83b90c9ebf7.png)


> Also remember the dysfunctional interruption mechanism on Mac?

Again, not in emacs-mac.  

>> Emulation of `select' without periodic polling.  It doesn't use CPU time while the Lisp interpreter is idle and  waiting for some events to come, even with subprocesses or network connections.

**Comment by minad** [comment]
Let me say - please be realistic about what I can possibly do here. In order to keep things somewhat in check, issues which are not reproducible are prone to be closed, since they are not actionable. Also I cannot do any support for platforms which I don't use and which I cannot access. It is of course appreciated to ask questions, in particular if you plan to do some debugging. I am interested to see what you find out. Maybe you should also try the Emacs 29 version of the Mac port?

> "our stance is that a person who moves from GNU/Linux to MacOS is being self-destructively foolish"

Frankly, there is some truth in that statement. Mac is a closed platform and it will only get more closed in the future, taking freedom away from you as a user. As an Emacs user it is the antithesis of what I want. 

But note that I am not against ensuring that my packages work sufficiently well on Mac. I implemented fixes before. There are certain requirements however. Someone must tell me precisely what needs to be changed to fix an issue. Furthermore there must be sufficient evidence that the issue should actually be fixed in my package and not in the Mac port itself for example.

I think it is reasonable of the Emacs maintainers to not merge any patches which would make the experience on non-free platforms better than on free platforms. If the Mac developers want to add something, they can at least potentially add the feature for the free platforms too. It is not possible in the other direction, as my example shows.

**Comment by jdtsmith** [comment]
No worries at all. I'm all too familiar with the frustrating "it doesn't work" style of bug report. I assure you this isn't that.  You've given me somewhere to look and I appreciate it. I will report back if I find anything definitive. 

On system-specific issues, I will offer you another perspective to consider. I use emacs exclusively on Mac (since about 15yrs).  I have gotten bug reports over the years from Linux and Windows users that I can similarly not reproduce or diagnose. The ports are mostly the same but do have small differences.  I personally find it helpful to look at it that way rather than thinking "my version is definitive, others are suspect".  Even if I still find it frustrating. 

I do run Linux on all my servers and will occasionally check an issue there, and once I even found a windows box with emacs for a thorny one, but all the usual version issues complicate this. 

I appreciate all you do for emacs.

**Comment by minad** [comment]
> On system-specific issues, I will offer you another perspective to consider. I use emacs exclusively on Mac (since about 15yrs). I have gotten bug reports over the years from Linux and Windows users that I can similarly not reproduce or diagnose. The ports are mostly the same but do have small differences. I personally find it helpful to look at it that way rather than thinking "my version is definitive, others are suspect". Even if I still find it frustrating.

I agree that it is useful to make software portable, since this increases robustness. This same argument, also applies to Compat for example, which can also help in increasing robustness, since we test packages against more versions. Portability ensures that we avoid using details, private APIs, rely on certain side effects and so on.

However I do think that there is a "definitive version" of Emacs. I do think that the Mac version is suspect for many reasons: It seems more buggy than the X11 version (but this could be bias), the existence of two ports muddies the situation, it is not as well supported by upstream, it is not as universally available, fewer users can access it and it is proprietary. Linux/BSD etc on the other hand can be executed everywhere via a VM. Maybe I can do it technically for Mac, but I would probably violate some licenses and in any case it would require me to run proprietary software.

If you use Mac you don't really own your system, all kinds of things can happen if the company makes some questionable move. Maybe in the case of Mac the situation is not as obvious, but did you try to use a Windows system recently? How can it possibly be acceptable that it treats your computer as an ad platform, I think even in the start menu?

As I wrote above, this is the antithesis of Emacs, which you can control. One can list numerous problematic proprietary software/hardware examples, where you don't own what you own. What about smart phones? What about music players? Smart keys? Smart homes? Car electronics? Electronic toys for children? It is a mistake to become more and more dependent on such things. Of course in some cases - why bother, if you get an immediate benefit and you don't really depend on it? Maybe you don't even care if the thing spies on you? It is a mistake nevertheless, and the mistake is more grave for central tools like your notebook or main computer.

**Comment by hmelman** [comment]
I also use the macport (emacs-mac) and am happy to try to reproduce this.  I'm not much of an org user but can try it.  I'm using the prebuilt releases of the macport (currently 28.2) on macOS 12.6.3.

**Comment by minad** [comment]
@hmelman Sure, go ahead. It may also be possible to reproduce this issue with pixel-scroll-precision-mode only on other platforms. I am not using pixel-scroll-precision-mode, since I don't really see an effect. It doesn't make scrolling much smoother for me. I tried to reproduce the issue with pixel-scroll-precision-mode but didn't see anything. Also I am missing a mental picture of how Consult could be causing this in combination with pixel-scroll-precision-mode.

**Comment by jdtsmith** [comment]
I'm redoing my init.el bisection as a double-bisection.  I suspect this is an A&B type bug, in which consult is not acting alone to elicit the issue.  Will post more once I figure something out, and provide a recipe others can try on Emacs 29.  BTW, pixel scrolling does very little/nothing for me with external mice scrollwheels, but has a big impact with smooth trackpad scrolling.

**Comment by minad** [comment]
> BTW, pixel scrolling does very little/nothing for me with external mice scrollwheels, but has a big impact with smooth trackpad scrolling.

With my track pad on the notebook I still don't see much of a difference. It may depend on some Emacs settings, but I also tried emacs -Q. Probably it also depends on X settings but this goes beyond what I am interested in digging into right now.

**Comment by jdtsmith** [comment]
OK, _mea maxima culpa_.  This has _nothing_ to do with consult.  Very sorry to have wasted your time.  I've isolated it down to an org-indent problem.  The reason I suspected consult was my own dumb fault: I had an `:after consult` stanza in my org `use-package`, such that removing consult in my initial bisection was actually serving (in a roundabout way) to prevent the offending org config from being set (`org-startup-indented`).  But since org is builtin, you don't really notice this.  It actually makes plenty of sense since org-indent monkeys with before/after-change-functions.   Correlation != Causation as I tell my students. 

Again, my sincere apology for this distraction.  I'll take this up with the org folks.  I appreciate all your suggestions and help.

**Comment by minad** [comment]
Okay, thanks! I had assumed that you had excluded any potential interferences. Btw, `org-indent-mode` is also on my list of modes one should not use in addition to `pixel-scroll-precision-mode`. ;)

Which benefits do you see in `org-indent-mode`? In my simpled minded view there are basically two types of Org documents - some look like todo lists with headlines only and some have the weight on the content, e.g., like project readmes or personal notes. For the starred todo lists I get indentation for free via the stars and for the documents with more content I don't want the indentation since it only wastes space and the indentation is also less meaningful.

**Comment by jdtsmith** [comment]
> I had assumed that you had excluded any potential interferences. 

So had I ;).  Erroneously as it turned out.  

>  org-indent-mode is also on my list of modes one should not use in addition to pixel-scroll-precision-mode. ;)

I have an adventurous spirit I guess... 

> Which benefits do you see in org-indent-mode?

I typically use up to 4 levels of nesting + nested lists inside, and without indentation it becomes challenging to see the structure at a glance.  Basically for the same reason I want sub-lists to indent, I want sub-headings to indent.

**Comment by minad** [comment]
> I typically use up to 4 levels of nesting + nested lists inside, and without indentation it becomes challenging to see the structure at a glance.

This seems to be a mixed style, which does not fall into the two categories of Org documents I mentioned above. But you could just use headings instead of lists or manually indent the lists deeper. Sublists have to be indented anyway.

> Basically for the same reason I want sub-lists to indent, I want sub-headings to indent.

But sublists are indented manually? Also subheadings are indented already by the stars themselves. I mean the point is really about the content below the headings.

I tend to avoid modes which I feel are technically problematic/intrusive, even if it may be nice to use them. org-indent-mode or indent guides belong to those modes, since they rely on change hooks etc. This is generally a good recipe for a stable Emacs. Avoid modes which are enabled all the time and which install post command hooks or change hooks. Also avoid anything which uses many overlays (not such a big problem these days anymore, but still). Post command hooks etc should be as robust and as fast as possible.

**Comment by jdtsmith** [comment]
OK this bug is annoying: even org/org-indent-mode doesn't really seem to be the culprit.  The pre-conditions seem to be:

1. Smooth/pixel scrolling with a device that works with it.
2. An image displayed in a window whose height is smaller than the image's. 

Sigh.  Recipe:

1. Turn on pixel/smooth scrolling.
2. Download this [image from wikipedia](https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png?download).
3. In your `*scratch*` enter:
   ```elisp
   (progn
     (insert "\n")
     (insert-image (create-image "/path/to/PNG_transparency_demonstration_1.png")))
    ```
    and execute it.
5. With a tall frame, smoothly scroll past the image, enjoying the fact that it does not jump past your view.
6. Adjust the height of your frame or window to be at or smaller than the image's height (experiment).
7. Attempt to smoothly scroll past the image.  Looping-back hijinks commence.

**Comment by jdtsmith** [comment]
> But sublists are indented manually? Also subheadings are indented already by the stars themselves. I mean the point is really about the content below the headings.


When I say I want sub-headings and sub-lists to indent, I mean their entire contents.  I actually think org-indent is not a big problem.  It simply adds a line-prefix as lines scroll into view.
