### ISSUE TITLE
FEATURE REQUEST: Somehow show command error when a command exits with an error message

### ISSUE THREAD

**Issue by rswgnu** [minad/consult#751]
If the command-line program associated with a consult command exits with an error, it would be very helpful to see the error to understand what is wrong with the current search expression.  Otherwise, you may get no matches when you really think you should but have no quick way to tell why.  Is there such a feature?  Maybe you would have to press a key binding to display it.

Right now, I have to exit the interactive search, list buffers, type a space, start and then select the " *consult-async*" buffer to see what is going on.  Most users will never know how to do this, so the UI could likely be much better here.  Just a thought.

**Comment by oantolin** [comment]
I think I like org mode export's approach: it just prints a message in the echo area that says something like "Export did not produce a PDF, see buffer *Output ...* for details". I'd be fine with that, just an instruction to check the log buffer.

Ah, but maybe looking for that buffer is "too advanced" because its name begins with space?

**Comment by minad** [comment]
We already have the error indicator in the prompt: `Grep! <input>` for errors and `Grep: <input>` for success. If this information is not good enough we should make sure that the underlying command is made more robust. `consult-grep` and the other commands currently are robust enough and are intentionally designed such that they do not fail.

There are no reasonable error message we could print, since there are no errors except if no matches are found or if the command crashed. Crashes should never happen under normal circumstances (segfault, os killed the process, ...). I hope that `consult-grep` is still sufficiently robust if we merge #749? I don't want the command to fail unexpectedly during the search. Maybe the `read-string` to read the search locations is not so good, since it allows input without sufficient error checking?

**Comment by oantolin** [comment]
> Maybe the `read-string` to read the search locations is not so good, since it allows input without sufficient error checking?

Oh, good point. Maybe that is a little unconstrained.

**Comment by minad** [comment]
Hmm, after thinking about this more, we are actually not as strict as I would like the commands to be. For example `consult-grep` accepts command line options, e.g., `#input -- -F`, which could lead to failures. So we may still want to add error messages, but only in the cases where the command failed "unconventionally". It is probably not easy to distinguish the different failure modes since there is no established exit code convention. Maybe if stderr output is non-empty, we should print the first line?

**Comment by rswgnu** [comment]
My view is that commands produce warnings and errors at times and it is best if possible to show them to the user for resolution.  The consult interface should not try to pre-empt all such states.  Just showing an ! Without any further follow through doesn’t help in understanding the problem.  All we need is a key that will display the tail end of the log buffer.

**Comment by minad** [comment]
> My view is that commands produce warnings and errors at times and it is best if possible to show them to the user for resolution.

I agree, in the cases where it makes sense. Please checkout https://github.com/minad/consult/commit/994f800a59924ed2683324deab39810fdc760d5d if this works for you.

> The consult interface should not try to pre-empt all such states. Just showing an ! without any further follow through doesn’t help in understanding the problem.

Now this is where I disagree. Ideally these commands *never fail* and as such Consult can get away with the minimal activity indicator. This should still be the normal mode of operation. But unfortunately I didn't achieve the strict goal since we allow additional command line options.

**Comment by rswgnu** [comment]
This fix works perfectly for me.  It displays the error for clarity while still producing the outputs from the valid file/directory list.  Thanks.
