### ISSUE TITLE
Consult-register errors with recent Emacs commit

### ISSUE THREAD

**Issue by tpeacock19** [minad/consult#752]
A recent commit https://github.com/emacs-mirror/emacs/commit/a129f257720dbef9adcaff58862d45ac142f93f6  in the master branch of Emacs removed the `kmacro-register` type. This causes an error in `consult-register.el` with the method `consult-register--describe. I haven't looked fully into the issue, but the error is removed with the following diff:

```diff
1 file changed, 1 insertion(+), 1 deletion(-)
consult-register.el | 2 +-

modified   consult-register.el
@@ -77,7 +77,7 @@ (cl-defmethod consult-register--describe ((val marker))
                 'multi-category `(consult-location . ,str)
                 'consult--type ?p))))))
 
-(cl-defmethod consult-register--describe ((val kmacro-register))
+(cl-defmethod consult-register--describe ((val kmacro))
   "Describe kmacro register VAL."
   (list (consult-register--format-value val) 'consult--type ?k))
 ```

**Comment by minad** [comment]
Yes, can you please report this upstream? It is not so nice to introduce such a breaking change upstream. However we can work around this as soon as the Emacs 30 release date approaches - still a long way there.

**Comment by monnier** [comment]
> Yes, can you please report this upstream? It is not nice to introduce such
> a breaking change upstream. However we can work around this as soon as the
> Emacs 30 release date approaches - still a long way there. cc @monnier

Hmm... we don't really want to revert this change, but it's indeed currently
difficult to make such a change smoothly (both on Emacs's side and on
Consult's side) :-(

I can see two changes which would make it easier:
- Introduce a notion of "(obsolete) type alias".  It might do the trick
  for Consult, tho it would be a mild lie in this case (the new `kmacro`
  type is not the same as the old `kmacro-register` type).
- Change `cl-defmethod` so it doesn't signal an error when the
  specializer (e.g. `kmacro` or `kmacro-register`) doesn't exist.
  Ideally, it should instead "suspend" the method until the type
  is defined.  Arguably, this should be handled by delegating to some
  generic function.

**Comment by minad** [comment]
On 2/26/23 00:41, monnier wrote:
>> Yes, can you please report this upstream? It is not nice to introduce such
>> a breaking change upstream. However we can work around this as soon as the
>> Emacs 30 release date approaches - still a long way there. cc @monnier
> 
> Hmm... we don't really want to revert this change, but it's indeed currently
> difficult to make such a change smoothly (both on Emacs's side and on
> Consult's side) :-(

That's okay. I agree with the simplifications in kmacro.el. I just
wanted to let you know that such changes are not completely
unproblematic for downstream users.

> I can see two changes which would make it easier:
> - Introduce a notion of "(obsolete) type alias". It might do the trick
> for Consult, tho it would be a mild lie in this case (the new `kmacro`
> type is not the same as the old `kmacro-register` type).
> - Change `cl-defmethod` so it doesn't signal an error when the
> specializer (e.g. `kmacro` or `kmacro-register`) doesn't exist.
> Ideally, it should instead "suspend" the method until the type
> is defined. Arguably, this should be handled by delegating to some
> generic function.

I could just use a macro and emit different definitions on Emacs 29 and
Emacs 30 on the side of Consult, e.g., if Consult is the only package
which has problems thanks to this change. But I don't want to act
prematurely here on the side of Consult, since Emacs master may still
change again.

**Comment by minad** [comment]
To answer more concretely to your two proposals:

On 2/26/23 00:41, monnier wrote:
> I can see two changes which would make it easier:
> - Introduce a notion of "(obsolete) type alias". It might do the trick
> for Consult, tho it would be a mild lie in this case (the new `kmacro`
> type is not the same as the old `kmacro-register` type).

This would work, but please don't introduce obsolete type aliases only
because of my package if this is not a common problem. We don't have to
make the problem larger than it is.

> - Change `cl-defmethod` so it doesn't signal an error when the
> specializer (e.g. `kmacro` or `kmacro-register`) doesn't exist.
> Ideally, it should instead "suspend" the method until the type
> is defined. Arguably, this should be handled by delegating to some
> generic function.

You can judge better, but in my opinion is this is not a great idea. I
like the static checking aspect of cl-defmethod. Btw, I also think that
the Emacs big brother byte compiler should get more and more strict. I
like the changes made by Mattias in that direction.
