### ISSUE TITLE
consult-ripgrep show some results twice

### ISSUE THREAD

**Issue by damanis** [minad/consult#758]
Version: consult-20230228.1346
No specific scenario, just two lines reference to same place in the code.
![image](https://user-images.githubusercontent.com/65733488/222085898-eee0b4a2-00e1-4e31-a68a-6440ff38ef7a.png)

**Comment by minad** [comment]
This could be a configuration issue. Please try to reproduce the issue with emacs -Q first. Follow the steps described in https://github.com/minad/consult#bug-reports. Thanks!

**Comment by unmonoqueteclea** [comment]
After updating consult, I am seeing this problem too

**Comment by damanis** [comment]
@unmonoqueteclea 
I found that in my case the problem was in my configuration. After comment out these lines consult-ripgrep works properly.
```
;; (setq consult-ripgrep-args
;;     "rg --null --line-buffered --color=never --max-columns=1000 --path-separator /\
;;     --smart-case --no-heading --line-number --no-column .")
```

**Comment by slotThe** [comment]
@damanis the problem is the `.` at the end of the ripgrep invocation (signaling the current directory).  Ever since https://github.com/minad/consult/commit/f32168ac20dc46b29e0023f2aee447662f764f0b, the `-grep` commands support multiple directories, which causes some incompatibilities with this (see also the [changelog](https://github.com/minad/consult/blob/main/CHANGELOG.org#development))

**Comment by unmonoqueteclea** [comment]
That fixed my problem! Thanks @damanis @slotThe !
