### ISSUE TITLE
xref (consult-xref) previews not showing up

### ISSUE THREAD

**Issue by mpenet** [minad/consult#760]
Hi Daniel, 

I just noticed that I never get previews from xref results candidates using `consult-xref`, I tried both xref-find-definitions and xref-find-references in differents modes and nothing shows.

You can see that it seems to be configured properly https://github.com/mpenet/emax/blob/master/init.el#L298-L299 but yet nothing. 

* GNU Emacs 29.0.60
* xref Version: 1.6.2

What am I doing wrong?

**Comment by mpenet** [comment]
I tried in both elisp mode and clojure. 

I will give it a try in a bit, I am stuck on a call right now.

**Comment by minad** [comment]
Okay, I just tried. It works for me in Elisp mode. Please let me know if you figure something out and try to create a minimal example, see https://github.com/minad/consult#bug-reports.

It could be that the xref marker used in your projects is not yet supported by Consult. Hopefully we can then add support. See here for the relevant code:

https://github.com/minad/consult/blob/5b2b9f572a9046d3235b4fae0e70ef129f735a26/consult-xref.el#L69-L82

**Comment by dasoju** [comment]
I am running into the same issue, and I debugged further.
I am using xref-find-definitions over TRAMP, which runs ripgrep on the remote machine 
Since ripgrep is running on the remote machine, ripgrep returns filename/path without SSH prefix, and consult is trying to open file without SSH prefix and fails to open, 

i think this is really a bug with either xref or consult-xref and should actually prefix remote files with SSH prefix
