### ISSUE TITLE
Avoid binding `file-name-handler-alist` to nil

### ISSUE THREAD

**Issue by sdevlin** [minad/consult#766]
In a few commands, consult.el binds `file-name-handler-alist` to nil before calling `abbreviate-file-name`. Per the comments, this is to avoid slow operations due to Tramp.

But there's more entries in `file-name-handler-alist` than just Tramp's handlers. In my own configuration, I have a handler for some files on a network file system. Coincidentally, my motivation was also to speed up `abbreviate-file-name`, which I do by handling calls to `file-name-case-insensitive-p`. When `file-name-handler-alist` is bound to nil, those calls become expensive, and the corresponding consult.el commands can be very slow.

If binding `file-name-handler-alist` is needed here, could consult.el be more selective and simply remove the Tramp handlers?

Thanks!

**Comment by minad** [comment]
Actually I think it is okay as is, since we just restore the old behavior. abbreviate-file-name didn't go through the file-name-handler-alist before in older Emacs versions. It was a pure function and then the Tramp developer decided to break this contract, making the function impure. Therefore I am not eager to change this.

As a possible solution, we could add a function consult--abbreviate-file-name-pure which you could then override with an advice in your configuration. If you are interested feel free to create a PR.

**Comment by minad** [comment]
Could you elaborate on why the Consult commands become slow if we bind file-name-handler-alist to nil. Maybe I am misunderstanding something but as I mentioned, the function was supposed to not go through handlers before. But maybe it was slow before also for network file systems. Could you please check against an old version of Emacs, e.g., Emacs 27.

**Comment by sdevlin** [comment]
Hi, thanks for the quick fix!

Even though you closed the issue, I'll add a bit more context. I'm using Emacs 28.2, and while `abbreviate-file-name` is not handled by `file-name-handler-alist`, it calls `file-name-case-insensitive-p` as a subroutine, and that function _is_ handled by `file-name-handler-alist`. So unfortunately that one function call can slow everything else down . . .

It's unfortunate that Emacs itself does not provide a pure version of this function. Anyway, thank you again for your work. The fix LGTM.

**Comment by minad** [comment]
> Hi, thanks for the quick fix!

Does it work properly for you?

> Even though you closed the issue, I'll add a bit more context. I'm using
> Emacs 28.2, and while |abbreviate-file-name| is not handled by
> |file-name-handler-alist|, it calls |file-name-case-insensitive-p| as a
> subroutine, and that function /is/ handled by |file-name-handler-alist|.
> So unfortunately that one function call can slow everything else down . . .

Yes, understood.

> It's unfortunate that Emacs itself does not provide a pure version of
> this function. Anyway, thank you again for your work. The fix LGTM.

Tbh the Emacs file API is not great. Tramp is also not improving the
situation since all the time new APIs are added which may or may not go
through some handlers and may fail or hang randomly. One would need at
least two incarnations of every function, one set of pure functions and
one set of functions which could access the file system.

**Comment by sdevlin** [comment]
> Does it work properly for you?

Actually, it looks like I'm getting errors now due to the absence of `directory-abbrev-apply`. Is this an Emacs 29 function? Should I find it in compat.el?

> Tbh the Emacs file API is not great.

Yep, agree.

**Comment by minad** [comment]
> Actually, it looks like I'm getting errors now due to the absence of directory-abbrev-apply. Is this an Emacs 29 function?

Indeed. It must be ported back via Compat.

**Comment by minad** [comment]
I reverted the fix for now. It can be applied again as soon as we have https://github.com/emacs-compat/compat/commit/684ada93bb2e55366bbb48278d344025cfb69b75.

**Comment by sdevlin** [comment]
I just tested this again, and it works correctly. Thank you again for your work!
