### ISSUE TITLE
Support consult-fd since fd can now handle multiple patterns

### ISSUE THREAD

**Issue by ghosty141** [minad/consult#770]
The following sentence in the wiki indicates that consult-fd should now be included with consult "by default"

> Parallel search is of course a strong advantage, so if fd gets support for multiple patterns consult-fd should be added to the consult package.

[Same thing in issue #6](https://github.com/minad/consult/issues/6#issuecomment-1278252044)

> If multiple pattern support is added to fd, I would like to see a consult-fd command here. 

This is the merge request that implements the missing feature: https://github.com/sharkdp/fd/pull/1139

**Comment by minad** [comment]
Oh, it is great that the fd PR finally landed! We can consider this as soon as fd with multiple patterns is widely available, let's say in Debian testing. I am sorry for being restrictive, but it would add too many complications if we would have to implement fd version checking and possible feature downgrading if an older version is found. On the upside, there is plenty of time for someone to prepare a PR. ;)

**Comment by ghosty141** [comment]
That sounds reasonable, good to know that's its now just a matter of time. Being restrictive is a good thing with so many users/platforms etc.

**Comment by ghosty141** [comment]
@minad It seems like it is in debian testing currently! https://packages.debian.org/bookworm/fd-find -> 8.6.0-3 -> https://github.com/sharkdp/fd/releases/tag/v8.6.0

**Comment by minad** [comment]
That's great! But I have to disappoint you about adding it immediately. We have to wait at least until I have Bookworm on my system. I am sure it won't take long. :)

**Comment by ghosty141** [comment]
Hehe, no worries. If you think it's time I'd appreciate it if you'd tag me or something. Thanks in advance :)

**Comment by mentalisttraceur** [comment]
For what it's worth, I think it was always perfectly reasonable for `consult-fd` to simply fail with an error if the underlying `fd` didn't support `--and`, rather than trying to gracefully degrade.

**Comment by ghosty141** [comment]
I mean it's just a matter until minad finds time for it. I'm sure it won't take too long ;)

**Comment by mentalisttraceur** [comment]
> I mean it's just a matter until minad finds time for it. I'm sure it won't take too long ;)

Sure, but I didn't say "hurry up", I said that I think a certain error behavior is acceptable design - that's less a comment about this one concrete situation or this specific past decision, and more an abstract general thought which can be constructively factored into all other situations and decisions.

**Comment by mentalisttraceur** [comment]
@minad I might end up catching the time+motivation for a PR, is this list about what you want?

1. keep the check for `fd` being installed as `fdfind`, maybe make it more robust against weird edge-cases (personally I like behavior-testing checks rather than just does-it-exist checks, but the latter is probably good enough in practice);
2. check if `--and` works and forward the error in a clear user-friendly way if not;
3. add docstring to the function itself
4. update the wiki to either delete the `fd` section or just say that `consult-fd` is now provided out-of-the-box,
5. find all places (README, any other docs) in the repo that mention `consult-{find,grep,ripgrep}` and use that as examples/guides of where and how to mention `consult-fd`.

**Comment by minad** [comment]
I appreciate help. Make sure that you check https://github.com/minad/consult#contributions.

Regarding opening a PR, please delay that. Currently I don't want to add consult-fd, since I don't have a recent version of fd available. This will not change for the next few months. I suggest you create a separate consult-fd.el file with the command, install it in your configuration, share it on github and link to the repository from the Consult wiki.

**Comment by mentalisttraceur** [comment]
In that case I don't think I'll be doing much, sorry - my eagerness to help was largely motivated by hope of getting `consult-fd` in a `consult` package release soon.

**Comment by mentalisttraceur** [comment]
If it's useful to anyone, here's a link to [the solution that currently works for me](https://github.com/mentalisttraceur/home/blob/47ca231dca5a006f29e803be5d2588dacbb8267f/.emacs#L210-L225). I don't think it's good enough for a PR (it doesn't hit any of the points in the list I commented earlier, and it's coupled to my own personal helper macros+function), but it does take advantage of the `--and` option.

**Comment by minad** [comment]
@ghosty141 Now I do have `fdfind` with `--and` around, so I'd welcome a PR which adds this command.
