### ISSUE TITLE
non latin charaacters not displayed correctly in grep/ripgrep result minibuffer

### ISSUE THREAD

**Issue by JonatanSahar** [minad/consult#786]
Hi!
I have some files in hebrew in my notes folder, when I use `consult-grep` to search for a hebrew term I get the right results, but all the hebrew chars are displayed by their (unicode?) char-number, like so:
![image](https://user-images.githubusercontent.com/18332012/230644026-6686d20f-bbe3-4eae-bdd8-acc6549b3466.png)

needless to say that org/txt buffers I use  to edit the files do present them properly, and so do functions that look for file names only like `consult-projectile-find-file`.

Do you have any idea what might be going on?
Thanks!

**Comment by minad** [comment]
I have not observed this particular issues before. It could be that there is some encoding misconfiguration. Can you please check if this behavior happens with emacs -Q? See also https://github.com/minad/consult#bug-reports. Also check that the file in Hebrew is correctly encoded as UTF-8. Could you post such a file somewhere that I can try to reproduce this issue?

**Comment by JonatanSahar** [comment]
Hi, thanks for looking into it.
This is an example file (contents): https://pastebin.com/Q3y0GbcP

I haven't been able to try it with `emacs -Q` yet because the snippets in the manual don't work for me, and I'm addmitedly not great with vanilla emacs, and the package loading mechanisms.. 
I tried the most basic one:
```
(package-initialize)
(require 'consult)
(setq completion-styles '(substring basic))
```
and got 

> eval-region: Cannot open load file: No such file or directory, consult

so I tried adding the path (got it through `locate-library`):
```
(package-initialize)
(require 'consult "~/doom-emacs/.local/straight/build-28.1/consult/consult.elc")
(setq completion-styles '(substring basic))
```

and got:

> byte-code: Cannot open load file: No such file or directory, compat

could you maybe direct me how to proceed?

thanks again :)

**Comment by minad** [comment]
Thanks for the sample file. I tried it and it works correctly in my setup and with emacs -Q. I tried both an ascii file name and a Hebrew file name to make sure that the file name is not the problem. Grepping for both ascii and Hebrew text works. This means that this is a configuration problem, some issue with the locale settings of your system or of Emacs.

> could you maybe direct me how to proceed?

Apparently you use Doomemacs, so I don't want to tell you anything which will mess up your existing configuration. If you use Emacs 29 or newer you can use the `--init-directory` option to specify a different Emacs user directory. Alternatively, temporarily move your `.config/emacs` directory to another location. Then you can proceed with the following steps.

1. emacs -Q
2. M-x package-initialize RET
3. M-x package-refresh-contents RET
4. M-x package-install RET vertico RET
5. M-x vertico-mode RET
6. M-x package-install RET consult RET
7. M-x set-variable RET (substring basic) RET
8. M-x consult-grep RET

I hope you figure out the cause of the issue. @iyefrat is the best person to help you since he made the Vertico/Consult integration for Doomemacs, speaks Hebrew and is familiar with the encoding/bidi difficulties.

**Comment by JonatanSahar** [comment]
Thank you! I'll give it a try. And thanks for the referral :)

**Comment by JonatanSahar** [comment]
So, I actually do get this with `emacs -Q` the way you described it. (moved my .emacs.d elsewhere, created an empty one, and called `emacs -Q`)
The only thing I didn't run was `M-x set-variable RET (substring basic) RET`, since there was no completion, and I got [match required].

**Comment by minad** [comment]
It could be that some encoding setting is wrong in your setup. Checkout environment variables like LANG and LC_ALL.

**Comment by JonatanSahar** [comment]
ok, for posterity - this solved the problem for me:

```
;; UTF-8 as default encoding
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)
(set-keyboard-coding-system 'utf-8-unix)

;; do this especially on Windows, for python output problems
(set-terminal-coding-system 'utf-8-unix)

```
