### ISSUE TITLE
Tramp access after execution `consult-buffer` on Tramp window

### ISSUE THREAD

**Issue by BrownShibaDog** [minad/consult#792]
Firstly, I would like to express my gratitude for providing such useful tools to the Emacs community. I have been using the consult package, and it has been a great addition to my workflow. However, I have encountered an issue related to the consult-buffer command when used with tramp.

When I try to use consult-buffer with a remote file opened using tramp, it triggers tramp access, causing Emacs to attempt an SSH connection to the remote host. This issue occurs specifically when I use consult-buffer on a remote file opened using tramp. It does not occur when I use consult-buffer on a local file buffer.

I was wondering if there is any way to suppress this tramp access caused by consult-buffer. I have already implemented the solutions suggested in the following related issues:

- Issue #224: Setting to disable tramp buffer previews
- Issue #781: Setting to exclude tramp buffers from recentf

Additionally, when connected to a slow host, consult-buffer becomes unresponsive. I would appreciate it if you could suggest any settings to reduce the occurrence of this issue.
Reproduction steps

1. Open a buffer using tramp in Emacs via SSH, e.g., `/ssh:hostname.local:/dir/`.
2. Shut down hostname.local to make it unreachable.
3. Move the cursor to the window that contains the buffer opened in step 1. (make it the current window)
4. Run `consult-buffer`.
5. (Emacs will try to establish an SSH connection to hostname.local, which is down, causing it to wait for a timeout.)

Thank you for your help and support.

**Comment by minad** [comment]
Thanks. The current Consult behavior seems perfectly justified, since if you do *anything* in such a frozen Tramp buffer it will lead to a significant slow down. So I am not sure if we should do anything about this. But if you investigate where the reconnect is coming from we may be able to do something about it. It could come for example from determining if there is a current project, see `consult-project-function`. In this case you could configure a `consult-project-function` which prevents the reconnect from happening, but I don't think this should be part of Consult itself.

**Comment by minad** [comment]
I tried your recipe. As I had suspected, it seems the `consult-project-function` is indeed the culprit. You can 1. set the project function to nil to disable project support in `consult-buffer`, 2. alternatively write a project function which bails out in remote buffers (check `default-directory` if the path is remote) or 3. remove the project sources from `consult-buffer-sources`. Each of these approaches should resolve your issue.

**Comment by BrownShibaDog** [comment]
Thank you for your prompt response.

I tried the `3.` method you suggested, and it certainly solved the problem.

As a reference, I also confirmed that using `projectile-project-root` in projectile.el for the `consult-project-function` can also alleviate the issue.

It is possible that projectile.el has a mechanism to cache the project root, which may allow `consult-buffer` to be executed without remote access in some cases.

Thank you very much for your help!

**Comment by mpolden** [comment]
Maybe `consult-project-function` could default to ignoring remote projects? Step 2 in the recipe may also happen due to loss of connectivity on the local machine and it's unfortunate that `consult-buffer` hangs in this case , especially when used as a `switch-to-buffer` replacement. (`switch-to-buffer` doesn't hang in this case).

**Comment by minad** [comment]
@mpolden Well, but what about remote projects? We would lose functionality in that case. We could cache the project directory in Consult. But I think that this should rather be fixed in project.el itself, similar to projectile.

**Comment by mpolden** [comment]
True, but narrowing to remote project files seems like a niche use-case to me. Maybe it could be configurable?

**Comment by minad** [comment]
It is already configurable by setting `consult-project-function`. I don't see a reason to offer a customization option on top.
