### ISSUE TITLE
How to do completing-read-multiple?

### ISSUE THREAD

**Issue by armindarvish** [minad/consult#816]
@minad What is the right way of achieving completingg-read-multiple but with consult add-ons? I see in the issues that at some point `consult-completing-read-multiple` was deprecated, but is there a way to use consult and achieve multiple selection with crm?

**Comment by minad** [comment]
There is no Consult extension for `completing-read-multiple`. The reason is that `completing-read-multiple` is fairly limited. The candidates are collected as a comma-separated list in the prompt, which is an inconvenient UI if candidate strings are long. I recommend against using it except for a few restricted scenarios (simple list of symbols, buffer names, etc.).

I consider using Embark the better alternative. You can use Embark to act on single candidates and also on multiple candidates (see `embark-select`). This is better than generalizing commands to use `completing-read-multiple` instead of `completing-read`, e.g., imagine an extra command `find-file-multiple` as generalization of `find-file`.

The difference here is basically that the action loop on the candidates happens outside the command if Embark is used, in contrast to inside the command if the command uses `completing-read-multiple`. As a result, we end up with overall simpler commands which can then be glued together flexibly via Embark.
