### ISSUE TITLE
`consult-yank-from-kill-ring' doesn't allow to yank in vterm. 

### ISSUE THREAD

**Issue by nicolas-graves** [minad/consult#822]
I'm using consult 0.35. 
I noticed that the function consult-yank-from-kill-ring fails to yank in *vterm* with the message
```
insert-for-yank: Buffer is read-only: #<buffer *vterm*>
```

For evil-mode's paste, yanking in *vterm* works well, I would love to be able to do the same with consult-yank-from-kill-ring. Thanks !

**Comment by minad** [comment]
Hi! 

Thanks for the report. 

Can you please check if `yank-from-kill-ring` works with Vterm on Emacs 28 or newer? Consult is basically the same command as `yank-from-kill-ring` only with a preview mechanism. Take a look a the code of `yank-from-kill-ring` and `consult-yank-from-kill-ring` for comparison - they are the same. If `yank-from-kill-ring` doesn't work, `consult-yank-from-kill-ring` won't work.

It seems that some special handling is needed, since Counsel seems to have the same problem. See the [workaround in the Vterm README](https://github.com/akermu/emacs-libvterm/tree/master#counsel-yank-pop-doesnt-work). Furthermore it seems that Vterm remaps `yank` to its own `vterm-yank` command.
Special Vterm integration is out of scope in Consult. Therefore one has to add a similar advice for Consult to the user configuration. I would appreciate if the necessary integration code is documented in the wiki.

**Comment by minad** [comment]
A similar question has been asked before. Duplicate #242
