### ISSUE TITLE
`consult-buffer` ignores `switch-to-buffer-in-dedicated-window` rule

### ISSUE THREAD

**Issue by gopar** [minad/consult#823]
When using `consult-buffer`, it ignores the value in `switch-to-buffer-in-dedicated-window` (which says what to do when user wants to switch to a buffer when they are in a dedicated window). I have mine to `nil` which should not switch buffer and error out. 

This is not the behavior seen, instead consult opens another buffer in another window.

Is there something i'm missing?
Thx for the amazing work! \o/

**Comment by minad** [comment]
Hi! Thanks for the report. 

I also have set `switch-to-buffer-in-dedicated-window=nil`. But I also have `switch-to-buffer-obey-display-actions=t`, such that `switch-to-buffer` does not error out, respects the dedicated window and opens in another window. Only if `switch-to-buffer-obey-display-actions=nil` we get the error. 

Turns out the only place where `switch-to-buffer-in-dedicated-window` is respected is in the interactive spec of `switch-to-buffer` and only if `switch-to-buffer-obey-display-actions=nil`. See https://github.com/emacs-mirror/emacs/blob/2af83f215ce83eda5a3eba21c352e6cd7435fbb1/lisp/window.el#L8952-L8972.

Now I could replicate the entire logic of the interactive spec in `consult-buffer` including the `force-same-window` argument, or just leave things the way they are. I think it is okay to keep `consult-buffer` as is given that the behavior is not exactly equivalent due to preview anyway. It is a drop-in replacement but this does not neccesarily mean that all the legacy settings translate one to one.

Using `switch-to-buffer-obey-display-actions=t` seems to be the more future-proof setting since then your display actions are respected. Unfortunately I believe `consult-buffer` still previews windows incorrectly in some of these cases. It may be worth looking closer at such cases. Iirc there have been discussions about this before on the issue tracker.
