### ISSUE TITLE
Can we have an option to show file buffer only for `consult--source-project-buffer`?

### ISSUE THREAD

**Issue by cxa** [minad/consult#824]
Since most time we only care about opened files, not other buffers.

Currently I can only hack like this, it's ugly and I hope we could has an option to customize.

```elisp
(plist-put consult--source-project-buffer
               :item
               (lambda ()
                 (when-let (root (consult--project-root))
                   (consult--buffer-query :sort 'visibility
                                          :directory root
                                          :as #'buffer-name
                                          :predicate #'buffer-file-name)))
```

**Comment by minad** [comment]
Hi! I prefer to not add customization options for the sources since it isn't clear where to stop regarding the customization. There are all kind of detail tweaking users may want to apply to the sources. Replacing source properties like the `:item` function is the way to go if you want to change a source.
