### ISSUE TITLE
`after-init-hook` leaking into `consult--preview-post-command-hook`

### ISSUE THREAD

**Issue by sthesing** [minad/consult#830]
I'm not sure this is an issue since it seems to be related to the upstream [bug #46326](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46326) with the broken `add-hook`. However, I thought it might be of interest, since @minad expressed the hope that this might be fixed upstream with Emacs 29. It's seems to be still a thing in Emacs 29.1. Also, I harbour the selfish hope that someone might haven an idea to work around or mitigate this :-)

Emacs Version: 29.1
OS: GNU/Linux
Consult version: tried both 0.35 and 20230806.1802 (installed via package.el)

When I use consult-theme, I get an error message that `consult-preview-post-command-hook` tried to call one of my custom-set-variables as a function, e.g. when running an otherwise blank installation of Emacs with this init.el: 
```elisp
;;;; init.el   -*- lexical-binding: t; -*-
(package-initialize)
(require 'consult)
(setq completion-styles '(substring basic))

(customize-set-variable 'load-prefer-newer t)
(add-hook 'after-init-hook #'customize-save-customized)
```

I get the following error:
```
Error in post-command-hook (consult--preview-post-command-hook): (void-function t)
```

If I set another variable instead, e.g.:
```elisp
(customize-set-variable 'package-archive-priorities
                        '(("gnu"    . 99)   
                          ("nongnu" . 80)
                          ("stable" . 70)   
                          ("melpa"  . 0)))
```
I get:
```
Error in post-command-hook (consult--preview-post-command-hook): (invalid-function '(("gnu" . 99) ("nongnu" . 80) ("stable" . 70) ("melpa" . 0))
```

One way to mitigate this is to use `customize-save-variable` instead of `customize-set-variable`, which makes the hook unnecessary. However, my setup makes very frequent use of the latter, and using the `after-init-hook` limits the writing to disk to just once at the end of the init process.

I experimented with alternatives to using `add-hook` here, i.e. I tried to adapt some of the example workarounds proposed in minad/corfu#133, but my elisp literacy seems to be insufficient. Does anybody have an idea what I could use instead of `add-hook` here?  Or other ideas?

I hope this issue is not just a nuisance. Sorry and feel free to close if it is.

**Comment by minad** [comment]
Hi,

I managed to reproduce this problem and obtain a stack trace for this problem with the following code:

~~~ elisp
;;;; init.el   -*- lexical-binding: t; -*-
(package-initialize)
(require 'consult)
(setq completion-styles '(substring basic))

(customize-set-variable 'load-prefer-newer t)
(add-hook 'after-init-hook #'customize-save-customized)

(setq debug-on-error t)

;; The !!! mark the changed code and enable debugging.
;; Debugging is usually disabled in post command hooks.
;; See https://github.com/minad/vertico#debugging-vertico 
(defun consult--preview-append-local-pch (fun)
  (let ((hook (make-symbol "consult--preview-post-command-hook")))
    (fset hook                               ;; !!!
	  (lambda ()                         ;; !!!
	    (condition-case e                ;; !!!
		(funcall fun)                ;; !!!
	      ((debug error)                 ;; !!!
	       (signal (car e) (cdr e))))))  ;; !!!
    (setq-local post-command-hook
                (append
                 (remove t post-command-hook)
                 (list hook)
                 (and (memq t post-command-hook) '(t))))))
~~~

This is the stack trace I've got:

~~~ elisp
Debugger entered--Lisp error: (void-function t)
  (t)
  eval((t))
  custom-theme-recalc-variable(load-prefer-newer)
  enable-theme(user)
  enable-theme(ef-autumn)
  consult-theme(ef-autumn)
  #f(compiled-function (action theme) #<bytecode 0x5a1401280232b4a>)(preview ef-autumn)
  #f(compiled-function () #<bytecode -0x627f722969e6229>)()
  #f(compiled-function () #<bytecode 0x1b0ecab89a9b776d>)()
  funcall(#f(compiled-function () #<bytecode 0x1b0ecab89a9b776d>))
  (condition-case e (funcall fun) ((debug error) (signal (car e) (cdr e))))
  consult--preview-post-command-hook()
~~~

This means we can limit the debugging to `custom-theme-recalc-variable`. Just run `(custom-theme-recalc-variable 'load-prefer-newer)` to trigger the bug. The function looks like this:

~~~ elisp
(defun custom-theme-recalc-variable (variable)
  "Set VARIABLE according to currently enabled custom themes."
  (let ((valspec (custom-variable-theme-value variable)))
    ;; We used to save VALSPEC under the saved-value property unconditionally,
    ;; but that is a recipe for trouble because we might end up saving session
    ;; customizations if the user loads a theme.  (Bug#21355)
    ;; It's better to only use the saved-value property to stash the value only
    ;; if we really need to stash it (i.e., VARIABLE is void).
    (condition-case nil
        (default-toplevel-value variable) ; See if it doesn't fail.
      (void-variable (when valspec
                       (put variable 'saved-value valspec))))
    (unless valspec
      (setq valspec (get variable 'standard-value)))
    (if (and valspec
	     (or (get variable 'force-value)
		 (default-boundp variable)))
        (funcall (or (get variable 'custom-set) #'set-default) variable
		 (eval (car valspec))))))
~~~

It seems that we already get the invalid value in the first line `(custom-variable-theme-value 'load-prefer-newer)`. It returns `((t))`. I inspect the `(symbol-plist 'load-prefer-newer)`. This is what I've got:

~~~ elisp
(standard-value nil
 custom-version "24.4"
 variable-documentation 776394
 theme-value ((user (t)) (changed nil))
 customized-value nil
 saved-value (t)
 saved-variable-comment nil
 force-value t
 variable-comment nil)
~~~

The `theme-value` property is set to `((user (t)) (changed nil))` and `custom-variable-theme-value` returns the `cdar` of that, which is `((t))`, which is then leading to the erroneous funcall. I am not sure why this happens but I suspect that your use of `customize-save-customized` is wrong and leads to an invalid sexp stored in init.el. I wonder why you want to store your changed variables in the init.el in the first place, since you change them before manually. Unfortunately this doesn't solve your problem, but maybe you get some clue on what is wrong.

**Comment by sthesing** [comment]
Thank you, that is indeed helpful!
