### ISSUE TITLE
Implement consult integration for other packages and consult high level architecture

### ISSUE THREAD

**Issue by mhlr** [minad/consult#833]
I am thinking about adding consult integration to some of the packages I use frequently.
I am having trouble understanding what is required. Is there an extension API that needs to be implemented?

I do not have a good model of how consult works internally. Is there documentation of the high-level structure architecture?

**Comment by minad** [comment]
Hi! 

This question is a bit broad and unspecific. I assume that for most packages no special Consult integration is needed or recommended, since you can and should use the builtin `completing-read` Emacs API instead. The advantage of using `completing-read` is that you stay agnostic of the completion UI and you avoid unnecessary dependencies.

There are a few scenarios where Consult integration makes sense and where you can consider to use `consult--read` instead of `completing-read`. Consult offers preview during completion (`:state` argument of `consult--read`, used for example by `consult-buffer` or `consult-line`) and supports asynchronous completions (`consult--async-*` functionality, used for example by `consult-grep`). Are your packages going to take advantage of these specific features? I suggest to take a look at some of the existing `consult-*` packages for examples.

Does this help you?
