### ISSUE TITLE
Open consult ripgrep candidate in other/split window?

### ISSUE THREAD

**Issue by rickalex21** [minad/consult#834]
Hello,

I'm wanting to bind `c-s` and `c-v` in the minibuffer to open consult ripgrep candidates in a split window
or in a vert window.  For normal files it works fine but for consult ripgrep candidates it tries to open
the candidate as a file `../../path/to/file.org:7:13:...`. I tried to `replace-regexp-in-string` with no success.

```lisp
(keymap-set minibuffer-local-map "C-v" 'my/embark-find-file-other-window-vsplit)
;;(keymap-set minibuffer-local-map "C-s" 'my/embark-find-file-other-window-split)
(keymap-set minibuffer-local-map "C-s" 'my/vertico-split-candidate)
(defun my/vertico-split-candidate()
  "Description"
  (interactive)
  (let* ((candidate (vertico--candidate))
        (file (replace-regexp-in-string ":.*$" "" candidate )))
    (if (string-match-p ":" candidate)
      (find-file-other-window file)
      (my/embark-find-file-other-window-split))
  (vertico-exit)))

(defun my/embark-find-file-other-window-vsplit ()
  "Open the file in vert window."
  (interactive)
  (embark--quit-and-run (lambda (file)
                          (windmove-display-right)
                          (find-file-other-window file)) 
                        (plist-get (car (embark--targets)) :target)))

(defun my/embark-find-file-other-window-split ()
  "Open the file in split window."
  (interactive)
  (embark--quit-and-run (lambda (file)
                          (windmove-display-down)
                          (find-file-other-window file)) 
                        (plist-get (car (embark--targets)) :target)))

```

Thanks

**Comment by minad** [comment]
I think you should approach the problem differently via Embark actions instead of directly using vertico--candidate and embark--targets. If you add a split open action to the consult-grep action map you can then still bind the actions to a key like C-v afterwards via keyboard macros. See embark-consult-goto-grep for the current default action. You can define a similar action which opens the destination in another window. Maybe @oantolin has some more suggestions?
