### ISSUE TITLE
annotation of abbrev symbols in completion buffer not working as expected

### ISSUE THREAD

**Issue by mbkamble** [minad/consult#835]
Hi. I have created a bunch of abbreviations for long account names in beancount-mode. The abbrevs are pretty volatile in my short term memory, so I thought of using consult--read to help display the available abbrevs and quickly select the desired one. 
I am using consult and marginalia.

To create a command for inserting abbrev, I wrote the following function:
```elisp
(defun insert-abbrev-partiallyworking (abbr)
  "Insert an abbreviation from the local abbrev table of the current buffer"
  (interactive
   (list (consult--read
	  (mapcar #'symbol-name
		  (abbrev--table-symbols
		   'local-abbrev-table))
	  :prompt "Abbrev: "
	  :annotate (lambda (abbr) (concat "\t\t\t" (abbrev-expansion abbr) "  EOS")))))
  (insert abbr))
```
That does not work. What shows up is this:
![image](https://github.com/minad/consult/assets/6557925/5cf9b9bd-a0b8-4884-be4b-aeb8cfa453b2)

So after some hacking, I came up with the following tweak by capturing the local-abbrev-table and providing it to abbrev-expansion:
```elisp
(defun mbk/insert-abbrev (abbr)
  "Insert an abbreviation from the local abbrev table of the current buffer"
  (interactive
   (let ((tbl local-abbrev-table))
     (list (consult--read
	    (mapcar #'symbol-name
		    (abbrev--table-symbols
		     'tbl))
	    :prompt "Abbrev: "
	    :annotate (lambda (abbr) (concat "\t\t\t" (abbrev-expansion abbr tbl)))))))
  (insert abbr))
```

And then the completion buffer shows the expansion as annotation
![image](https://github.com/minad/consult/assets/6557925/6868ce82-67dd-424e-8504-40a4076c4ee5)

I would like to understand why the first one deos not work while the second one does

**Comment by oantolin** [comment]
The annotation function runs in the minibuffer, but the abbreviation is local to the buffer you were in before. You could wrap the body of the annotation function in `(with-minibuffer-selected-window ...)` (or in `(with-current-buffer (window-buffer (minibuffer-selected-window)) ...)`) so that it runs in the previous window, but I think your solution of capturing the value of `local-abbrev-table` is better since it avoids a lot of buffer & window switching.

You can test that the annotation function runs in the minibuffer with something like:

```elisp
(consult--read
 '("six" "half a dozen")
 :prompt "Pick: "
 :annotate (lambda (cand) (format " %s in %s" cand (current-buffer))))
```

**Comment by mbkamble** [comment]
Many thanks for the clarification @oantolin. It is clear to me now
