### ISSUE TITLE
IDEA: Start consult-flymake on the current error.

### ISSUE THREAD

**Issue by jgarte** [minad/consult#841]
Hi,

WDYT if `consult-flymake` would start on the current error instead of jumping to the top of the error list.

Could we add a `defcustom` to configure that?

More context:

It jumps up here:

![image](https://github.com/minad/consult/assets/47760695/c99c1b36-a03c-4059-b47c-24ab5a46f4a3)

Instead of here:

![image](https://github.com/minad/consult/assets/47760695/aad89fa2-89b5-4368-970f-0e930be228df)

![image](https://github.com/minad/consult/assets/47760695/0b029172-7f3f-413a-ad54-90f7e4778f37)

**Comment by minad** [comment]
No, we cannot. Such requests have been made a few times for different commands, e.g., `consult-outline`. The problem is that jumping to a specific candidate is not supported by the completion UIs through the `completing-read` API. The best we could do is to split the list and wrap it around as `consult-line` does. See https://github.com/minad/consult/wiki#pre-select-nearest-heading-for-consult-org-heading-and-consult-outline-using-vertico as an example for the hacks needed to make this work.

**Comment by jgarte** [comment]
Thanks for the infos.

I'm just going to go with [popon](https://codeberg.org/akib/emacs-flymake-popon).

**Comment by scturtle** [comment]
```elisp
  (defvar consult--current-line nil)
  (defun consult--set-current-line (&optional arg1 arg2)
    (setq consult--current-line (line-number-at-pos)))
  (defun consult-vertico--update-choose (&rest _)
    (when consult--current-line
      (setq vertico--index
            (or (seq-position vertico--candidates consult--current-line
                              (lambda (cand line) (>= (string-to-number (nth 1 (split-string cand " "))) line)))
                (1- (length vertico--candidates)))))
    (setq consult--current-line nil))
  (advice-add #'consult-flymake :before #'consult--set-current-line)
  (advice-add #'vertico--update :after #'consult-vertico--update-choose)
```
