### ISSUE TITLE
How do I remove the initial hash # symbol?

### ISSUE THREAD

**Issue by arael** [minad/consult#842]
When I launch the consult-find command I get an initial hash on the prompt '#'.

This messes up the results. For example if I search for foo and these are my entries:

```
foo
...
one/two/three/foo
four/five/six/foo
```

the first entry will get buried down instead of being the first option. Like this:

```
aaa/bbb/foo
...
one/two/three/foo
four/five/six/foo
foo
```

This happens because instead of 'foo', the default search is '#foo'. Every time I have first to delete that '#' and then search.

How do I remove that initial '#'?

Thank you very much.

**Comment by minad** [comment]
The initial hash doesn't mess up anything. It is there for a purpose, see the README. If you still want to configure this, see the variable consult-async-split-style. Please try to figure such questions out yourself first, since the issue tracker is mainly meant for bug reports. There exists the Emacs customize UI. I recommend to check out all the customization variables of a package as a starting point. This doesn't only apply to Consult but also other Emacs packages. Thanks!

**Comment by arael** [comment]
No problem. Will not bother anymore.
