### ISSUE TITLE
consult-line: add commands which skip over visible matches

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/consult#95]
A lot of the times, I have several lines on the same page that match the string. That's fine, but I wish I could type C-v and M-v to go to the next page (it's not the right word for consult-line), e.g. pass all matches that I currently can see on the screen and go to the match that isn't on the screen. It would drastically reduce the amount of keystrokes needed by the user. This should only be enabled with the preview, of course.

**Comment by minad** [comment]
Not a bad idea! This means like skipping multiple entries in the candidate list at once until we arrive at a match which is non-visible. These commands could be bound in the minibuffer keymaps. Unfortunately this sounds a bit completion-system dependent and would probably need a separate implementations for selectrum/icomplete. Generally, I am not eager to add many features which rely on completion system specifics. But if the implementation turns out to be sufficiently simple and not too intrusive I may consider adding something like this.

**Comment by oantolin** [comment]
Probably a single `consult--completion-next-match-hook` is all the extra API needed to implement this. It sounds like it could be done with that and the existing `consult--completion-match-hook`.

**Comment by minad** [comment]
> Probably a single consult--completion-next-match-hook is all the extra API needed to implement this.

Yes, sure but I am not that eager to introduce more completion system specific hooks, in particular if they are only useful for a single command. I am already not super happy with this match-hook. The other two candidate-hook and refresh-hook are used at more places and seem to be more general purpose.

**Comment by minad** [comment]
I think this is out of scope for consult and I don't have an intention to implement this.

* Requires yet another completion-specific hook
* Requires modification of the keymap (we would require users to bind this manually)

But if someone is willing to work on this, please feel free to open a PR. No guarantee that we will merge it in the end, but it could be a better starting point for a more informed discussion.
