### ISSUE TITLE
[Q/Bug] consult-grep (with ripgrep or ugrep) is slower than counsel-rg

### ISSUE THREAD

**Issue by NightMachinery** [minad/consult#950]
counsel-rg is much faster than consult. In fact, counsel-rg mostly feels realtime to me (especially when the query has more than around 10 characters)(without the `consult-async-split-style` hack), while consult is very slow. Typing a character takes around a second to update the result on an M2 Macbook.

```
(counsel-rg query dir args (or prompt "> "))
```
```
(consult--grep
       (or prompt engine)
       #'consult--ripgrep-make-builder
       dir
       query)
```

I have used consult with ugrep as well, and that also has this problem. This makes me believe that the bottleneck is with consult itself. 

Perhaps using `--null`  is expensive?

**Comment by minad** [comment]
Consult update delays can be adjusted with consult-async-* variables. It could be that you perceive Consult as slower since it doesn't restart the search as often.

For a meaningful comparison more information is needed and a recipe based on emacs -Q. Did you try to capture a profile? See https://github.com/minad/consult?tab=readme-ov-file#bug-reports.
